### ISSUE TITLE
Website == RTD?

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#1003]
Just raising the question about the OCIO website and documentation in general. I wanted to ask peoples opinions about whether the Website should be equivalent to the ReadTheDocs pages, or we we should have a separately curated website/landing page that links to the RTD site?

I can see the argument for both systems, so just wanted some outside input...

Example landing pages:
https://sites.google.com/site/openimageio/home
https://www.openvdb.org/
https://www.openexr.com/
https://www.opencue.io/

RTD only:
https://opentimelineio.readthedocs.io/en/latest/

**Comment by doug-walker** [comment]
Thanks for starting this thread Sean!  

Personally, I like the OpenCue example.  It looks modern and professional.  So I do like the idea of having the home page be something more cool looking than just a RTD page.  However I don't think it needs to be a full site like we have now -- it could be just a landing page that then points to RTD, GitHub, the ocio-dev/user forums, ASWF, and perhaps a Wiki, etc.

OpenCue and OpenVDB have the ASWF branding on their sites so we should reach out and learn more about their process and whether there are some LF resources we could tap into.

**Comment by michdolan** [comment]
Thanks Sean! Completely agree. Noting too that LF has a creative services team that can do graphic design work if needed. I believe they are designing a new OpenEXR logos currently. We can source community help too of course, but if needed they are there to help.

**Comment by KelSolaar** [comment]
Here is something un/related but/and very useful copied verbatim from [one of our issues](https://github.com/colour-science/colour/issues/523):

---

This article has some good information that could be useful to apply to our documentation: https://www.divio.com/blog/documentation/. The gist of it is a clear delineation between those 4 pillars:

## TUTORIALS
A tutorial:

- is **learning-oriented**
- allows the newcomer to get started
- is a lesson

_Analogy: teaching a small child how to cook_

## HOW-TO GUIDES
A how-to guide:

- is **goal-oriented**
- shows how to solve a specific problem
- is a series of steps

_Analogy: a recipe in a cookery book_

## EXPLANATION
An explanation:

- is **understanding-oriented**
- explains
- provides background and context

_Analogy: an article on culinary social history_

## REFERENCE
A reference guide:
 
- is **information-oriented**
- describes the machinery
- is accurate and complete

_Analogy: a reference encyclopaedia article_

**Comment by carolalynn22** [comment]
I agree with Doug, too. Like the idea of a modern, well designed, easy to navigate landing page, with links out to relevant info, wherever that may exist. Most flexibility and maintainability long term. 

If we can work with LF for logo design, I think that's a good option, and also might provide a sense of consistency and familiarity within the ASWF projects.
