### ISSUE TITLE
Option to process data channels

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1028]
An OpenColorIO ColorSpace has a property called isdata that is intended to be set to "true" for non-RGB image data such as alpha channels, normals, Z-depth, position, object IDs, etc.  OCIO gives these channels special treatment by not applying most color transforms.  For example, if the source or destination of a ColorSpaceTransform is a ColorSpace whose isdata is set to true, no processing is applied -- it is effectively a no-op.  This is usually a very sensible thing to do since it would usually be undesirable to apply color processing to data channels.

However, as we consider how to display data channels on a monitor, the situation is less clear cut.  Indeed, there are already some exceptions along these lines in OCIO.  For example, the DisplayTransform in some cases will apply certain operations such as the LinearCC and DisplayCC.  Even in these cases though, DisplayTransform does not apply the actual display/view transform.

In most applications, data channels are typically displayed simply by sending the values to the display unmodified, effectively considering them as being in the monitor color space.  For alpha channels in particular, this generally works quite well.  For other data such as normals (which typically have negative values) and Z-depth (which may span a large range much above 1) it could be argued that some processing would make the data easier to visualize.

The real issue however is the arrival of HDR displays.  Many of these displays are calibrated to have an ST-2084 (PQ) response.  This means that sending a normalized value of 1 to the display will be a request to display that pixel at 10,000 nits.  Sending an alpha channel without color management to such a display results in a very bad user experience!

In situations such as this, it would be very useful for OCIO to allow applications the ability to request that data color spaces are processed.

The proposal is to add methods setDataBypass and getDataBypass to the ColorSpaceTransform and DisplayTransform classes.  The default would be true, which would correspond to the current behavior -- data color spaces do not get processed.  However, applications would be able to set it to false for situations as described above where it is actually necessary to process data color spaces.

**Comment by michdolan** [comment]
Good point. One tricky aspect to this is that even if you wanted to display a data channel through the PQ, you would only want to apply the device encoding portion of the display transform, but bypass any creative "look". You would essentially want to preserve the relative appearance of the data on the display. Perhaps it should still bypass the view transform, but not the display colorspace? Or at least have the option to do so?

**Comment by doug-walker** [comment]
Michael, my thinking was that the config would define a view specifically for a type of data (such as an alpha channel).  For example, it could make the alpha channel appear as it would have on an sRGB monitor without color management.  So the entire display/view processing could be applied in that case.

**Comment by sobotka** [comment]
I think the view for data is a much needed result, and look forward to this implementation.

In your proposal Doug, if I am reading you correctly, I am guessing that a data’s view transform would honour the display colourimetry, thereby rendering the data in a somewhat “display agnostic” fashion?

Terrific stuff folks.

**Comment by michdolan** [comment]
Ok, thanks for the explanation Doug. That makes sense.

**Comment by doug-walker** [comment]
Troy, yes, it would be far more independent of the display than bypassing color management.

**Comment by doug-walker** [comment]
Closing as this has now been implemented.
