### ISSUE TITLE
Refactoring DisplayTransform

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1029]
DisplayTransform, along with ColorSpaceTransform, form the heart of OCIO.  This is where all the business logic for connecting color spaces lives.  However, DisplayTransform is quite complicated, with many features that do not seem widely used (linearCC, colorTimingCC, channelView, displayCC, looksOverride).  Also, the implementation of colorTimingCC and channelView are not well suited to all apps.  More importantly, in OCIO v1 it thows if direction==inverse.  

It seems that there are two someone separate requirements here:

1)  Have a clear and robust transform that allows apps to easily request the result of the display/view section of an OCIO config.  Note that this includes the processing of any LookTransforms that are part of that view.  The code should be as simple as possible and should have a properly implemented inverse (which is not true today).

2)  Provide an example for how to implement a viewing pipeline that could be used as the basis for a DCC application's viewport.  This would include all the current capabilities of DisplayTransform, including channel swizzling, and the ability to do adjustable exposure and gamma controls.

Note that in previous PRs, we have added the apphelpers directory (outside of OCIO core) which is intended to serve as a set of templates for application developers.  The goal is to provide best practices that could help promote consistency across applications as well as provide good examples of OCIO usage.

The first part of the proposal is to simplify and refactor DisplayTransform so that it only implements what the display/view section of a config file does.  It would have a properly implemented inverse (that properly utilizes the from_ref and to_ref transform directions), along the lines of how ColorSpaceTransform works.

The new DisplayTransform would apply any LookTransforms that are specified in a view.  It would also offer a setLooksBypass and getLooksBypass method that would allow applications to offer a control to easily toggle a view's looks on and off.  Note that this simpler control would replace the looksOverride functionality for DisplayTransform.

Like ColorSpaceTransform, the new DisplayTransform will be a no-op if the source or destination is a data color space.  Note that this is a change from the current DisplayTransform, which has a fairly complicated set of logic around what gets applied and what does not.

The second part of the proposal is to add a ViewingPipelineTransform class under the apphelpers directory.  This transform would fully support all of the current functionality of DisplayTransform including LinearCC, ColorTimingCC, channelView, DisplayCC, and looksOverride.  It would call the refactored DisplayTransform to implement that part of the processing.

Note that one could argue that some of the behavior of the current DisplayTransform actually does not represent an ideal viewing pipeline for a DCC viewport.  However, we feel it is important as a first step for ViewingPipelineTransform to maintain the current DisplayTransform behavior to ease the transition for any current users.  Improvements to that behavior deserve further discussion and are best done as a separate step.

We would also add extensive unit tests for both DisplayTransform and ViewingPipelineTransform.

Finally, we propose changing the name of the new DisplayTransform to DisplayViewTransform.  This has several benefits:
 - It recognizes the fact that both a display and view must be selected.
 - It makes it clear that the original DisplayTransform no longer exists in its original form.

Note: This proposal received support when it was presented at an OCIO v2 working group meeting.  Here are the notes:

-- Doug showed a diagram of the existing processing logic and a proposed simplification.  Proposal is to take all the extra features and move them into an app helpers directory outside the core library (the app helpers idea was discussed at the November meeting).
-- Kevin:  Agree that the requirements vary a lot between apps.  The existing DisplayTranform is missing color correction related features that we need.
-- Mark:  I didn't even realize some of that stuff was there.  Agree it should be simplified.
-- Michael:  I've seen apps that use all of the currrent DisplayTransform features (except for looksOverride).  The ColorTimingCC is sometimes used to build a CDL interactively.  This is then saved to become the context-based Look for a given shot.  But as long as the existing functionality remains available, no objection to moving/renaming it.
-- Michael:  Looking at apps today, they are not very uniform in how their viewports work.  It would be nice to try and encourage more consistency, that is one purpose that DisplayTransform serves.
-- Doug:  Totally agree.   In fact we would like to make it even clearer how to properly add exposure and gamma sliders to a viewing pipeline (using the new ExposureContrast op with dynamic parameters).  And that is the idea behind the app helpers directory, to serve as examples or best-practices for app developers to look at.
-- The group agreed that simplifying DisplayTransform was a good idea.  We will move forward with a PR of that and the app helpers.

**Comment by michdolan** [comment]
This sounds like a good plan to me. I also agree with your arguments for renaming `DisplayTransform`. 

Would `ViewingPipelineTransform` inherit from Transform? If it can't be used as a transform (i.e. to construct a processor, or be added to a color space definition), I wonder if `Transform` should be dropped from the name,

Perhaps it could be called something like `LegacyViewingPipeline` (aligning with the `LegacyGpuShaderDesc`), or if that class will be the example of how to implement OCIO into a viewer, it could be called something else. I completely agree with the concept though.

**Comment by doug-walker** [comment]
The ViewingPipelineTransform would not inherit from Transform.  It would have a getProcessor method.  We used the "transform" name since it is a port of the original DisplayTransform, but we are open to the idea of just calling it ViewingPipeline, if that works for you?  At some point, the LegacyViewingPipeline name might be appropriate, but at the present time we don't have a preferred ViewingPipeline to replace it with.  So we'd prefer to wait until that is in place before adding the "Legacy" prefix.

**Comment by michdolan** [comment]
I think `ViewingPipeline` sounds good, but worth discussing at the working group meeting in case others prefer your original name. I realized after some more thought that there are other classes (`ViewTransform`) that don't inherit from `Transform` but use the name, so might be a non-issue.

**Comment by doug-walker** [comment]
Closing as this has been implemented.  And by the way, we did adopt Michael's suggested use of the LegacyViewingPipeline naming in a follow-up App Helpers PR.
