### ISSUE TITLE
Add a color space property to describe the encoding

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1031]
The ColorSpace class in OpenColorIO currently has a number of descriptive properties such as bitdepth, equalitygroup, family, and isdata.

In addition, it would be very helpful for applications to be able to know the basic type of encoding of a color space.  For example, it is well known that the performance of various types of image processing algorithms varies based on the type of encoding.  Applying a spatial filter to a scene-linear image gives a different subjective result than if applied to the same image encoded in a log color space.  Likewise certain algorithms such as keying or tracking may assume that the color encoding is roughly perceptually uniform and thus may have difficulties with scene-linear images.

At first glance, the family attribute seemed like a potential way to specify this information.  In the OpenColorIO user guide, family is defined as "Allows for logical grouping of colorspaces within a UI" and the examples are "log" and "display".  

However, looking at example configs such as ACES, the family attribute is used to group color spaces by purpose and vendor, for example "Input/ARRI".  So the emphasis is on organizing the UI.  Furthermore, in a recent PR, the ColorSpaceHelpers classes were added and have a feature to facilitate building hierarchical menus for application UIs based on the family attribute.  

So it has become clear that the main benefit of the family is for applications to better organize their UI.  Furthermore, it is clear that the vocabulary of the family attribute is unconstrained and based on very config-specific details.  The family attribute is thus not well-suited to carry the color space encoding information.

Therefore this proposal is to add an "encoding" attribute to the ColorSpace class, including setEncoding and getEncoding methods (similar to family).  This would also be supported in the YAML serialization of a color space.  The attribute would be purely informative and would not affect the processing provided by OpenColorIO.

Furthermore, the proposal is that the attribute have (unlike family) a specifically defined terminology.  Similar to roles, there will be nothing to prevent config authors from using other strings.  However, having a clear set of predefined values for the common cases is what will make this attribute useful to application developers.

The proposed values and definitions are:

"scene-linear" -- A scene-referred encoding where the numeric representation is proportional to scene luminance.  Examples: ACES2065-1, ACEScg.

"display-linear" -- A display-referred encoding where the numeric representation is proportional to display luminance.  Example: CIE XYZ values measured off of a display or projection screen.

"log" -- A scene-referred encoding where the numeric representation is roughly proportional to the logarithm of scene-luminance (often with some divergence in the shadows as with most camera log encodings).  Examples:  ACEScct, ACEScc, ARRI LogC, Sony S-Log3/S-Gamut3.

"sdr-video" -- A display-referred encoding where the numeric representation is proportional to an SDR video signal.  Examples: Rec.709/Rec.1886 video, sRGB.

"hdr-video" -- A display-referred encoding where the numeric representation is proportional to an HDR video signal.  Examples:  Rec.2100/PQ or Rec.2100/HLG.

"data" -- A non-color channel.  Note that typically such a color space would also have the isdata attribute set to true.  Examples:  alpha, normals, Z-depth.

**Comment by michdolan** [comment]
There's also categories now too. we'll definitely need to document how each of the three classification systems are intended to be used to avoid confusion. 

I do like the idea though of having a predictable way to understand the the encoding at a glance.

**Comment by doug-walker** [comment]
Closing as this has been implemented.
