### ISSUE TITLE
Allow applications to filter views based on color space

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1032]
OpenColorIO allows defining multiple views for each display.  In many cases, certain views will be intended for use with certain types of color spaces.  For example, a Raw view may be intended for data color spaces and a Film view may be intended for scene-linear or log color spaces.  However, there is presently no easy way for applications to filter the list of views based on the color space of the image being shown in a viewport.  The application typically must present all the views and require the user to manually switch them.  This can become tedious when switching between images in a variety of color spaces (e.g. switching between scene-linear images, video images, and alpha channels).  

Ideally, it would be possible for an application to know which view would be preferred for each color space in order to minimize the amount of manual view switching users must do and provide a viewport result which looks correct by default.  It would also help apps be able to automatically generate plausible thumbnails and preview images.

This proposal is to allow config authors to provide additional information that would allow applications to filter the list of views based on the color space being viewed.  Specifically it would allow a config to contain a viewing_rules section analogous to the file_rules section that was added in a recent PR.  A view would then be allowed to refer to one of these viewing rules.  Here is an example:

```
viewing_rules:
    - !<Rule> {name: video-spaces, colorspaces: [sRGB, Rec709]}
    - !<Rule> {name: data-spaces, colorspaces: [alpha, normals]}

displays:
  sRGB:
    - !<View> {name: Video, view_transform: colorimetry, display_colorspace: sRGB, rule: video-spaces}
    - !<View> {name: Raw, colorspace: nc10, rule: data-spaces}

```
This is helpful for situations where a given view is intended for use with just a few specific color spaces.  However in other situations, it would be helpful to be able to define rules to be used with a broader set of color spaces.

In issue #1031, it is proposed to add an "encoding" attribute to color spaces to allow grouping color spaces into groups such as "scene-linear", "log", "sdr-video", and "data".  This proposal therefore provisions for being able to define a rule based on the encoding attribute of a color space rather than a set of named color spaces.  For example:

```
viewing_rules:
    - !<Rule> {name: scene-linear-or-log, encodings: [scene-linear, log]}

displays:
  sRGB:
    - !<View> {name: ACES, view_transform: ACES-sdr-video, display_colorspace: sRGB, rule: scene-linear-or-log}

```
The colorspaces and encodings attributes may contain a single value or a list of values.  It will be illegal for a rule to define both a list of colorspaces and encodings simultaneously.  

Also, similar to the file_rules, it will be allowed for a rule to define a set of custom key/value pairs like this:
`    - !<Rule> { name: scene-linear-rule, encodings: scene-linear, custom: {key1: value1, key2: value2} }
`
The key names and values are arbitrary strings.  This may be useful to control application-specific behavior. 

New methods will be added to the Config class to allow applications to get a filtered list of views.  The existing API is:
```
   int getNumViews(const char* display);
   const char* getView(const char* display, int index);
```
This will remain with the current behavior and will ignore the rule attribute of views.  A new API will be added that also takes the name of a color space:
```
   int getNumViews(const char* display, const char* colorspaceName);
   const char* getView(const char* display, const char* colorspaceName, int index);
```
This will use the viewing rules to filter the views for the given display based on the color space.  Views that do not have a rules attribute are always returned (so if no rules are present, the results are the same as the original API).

Note that the active_views may still be used to remove views that are not appropriate for a given user or workstation.  If the active_views list is non-empty, any views that are not in that list will not appear in the results of any of the above API calls.  Furthermore, active_views will continue to sort (that is, determine the index order) the list of views in all of the above calls.

**Comment by sobotka** [comment]
Much needed and excellent work.

The following would simply provide a granular enumeration under the various rules categories, if I am reading this correctly?

```
displays:
  sRGB:
    - !<View> {name: ACES, view_transform: ACES-sdr-video, display_colorspace: sRGB, rule: scene-linear-or-log}
```

**Comment by doug-walker** [comment]
Troy, for the example you quoted, a call to the Config method getNumViews("sRGB", "foo") would include the "ACES" view in the returned count if the color space "foo" has the new encoding attribute which contains a string listed in the rule (either "scene-linear" or "log" in this case).  For example:
```
colorspaces:
  - !<ColorSpace>
    name: foo
    encoding: scene-linear
```

**Comment by doug-walker** [comment]
Closing as this has been implemented.
