### ISSUE TITLE
Create Python bindings for libutils

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1034]
I think it could be worthwhile to create a optional, secondary Python lib which binds `libutils` for utilizing the convenience of the various helpers, and helping to interface with OpenImageIO's Python bindings, and PyOpenGL, etc. There are quite a few cases in a pipeline for implementing these concepts in Python tools (which primarily leverage C++ libs under the hood), so it would be great to offer the full suite of implementation tools in both languages.

**Comment by ChinYing-Li** [comment]
Not so familiar with python bindings for cpp, but can help with this before the documentation related GH issues are out.

**Comment by michdolan** [comment]
Hi @ChinYing-Li 

I've started some work on this but would be more than happy to have help. I'll create a PR this evening with my work so far to show you what I'm doing. There are three libraries to bind as part of this and we could collaborate if you're interested.

**Comment by ChinYing-Li** [comment]
@michdolan 
An update on the progress: 
A `HeadlessApp` instance can't make EGL context current when using the `PyOpenColorIO_oglapphelpers` library, yet there's no such error during GPU unit testing. I'll open a draft PR once the problem is solved.
