### ISSUE TITLE
Replace GLX dependency with EGL dependency

### ISSUE THREAD

**Issue by ChinYing-Li** [AcademySoftwareFoundation/OpenColorIO#1039]
Quoting @jfpanisset : 
"" Currently OpenColorIO uses GLUT in tests/gpu/GPUUnitTest.cpp to create a 
window to render OpenGL tests, which in turn depends on GLX. I'm assuming 
these days it's linking against FreeGLUT, and it is apparently possible to use 
EGL instead of GLX for creating the rendering context. The advantage is that it 
might be possible to do away with having to stand up an X server for the CI 
pipeline, and whereas EGL rendering is supported inside NVIDIA containers
 (with built-in support starting in Docker 19.03), GLX is not. "

**Comment by ChinYing-Li** [comment]
In fact, freeglut also [seems to support headless rendering](https://sourceforge.net/p/freeglut/mailman/message/29619660/) but has to go through a X server.

**Comment by ChinYing-Li** [comment]
Hi, a bit of guidance needed. In order to support headless rendering,  I refactored```OglApp```, which is now a base class, from which derived ```ScreenApp``` and ```HeadlessApp```. 
This means that wherever ```OCIO::OglApp & app``` is passed as a function parameter, I have to substitute it with ```OCIO::OglAppRcPtr```. (```typedef OCIO_SHARED_PTR<OglApp> OglAppRcPtr```) 
So far, I don't see if there would be any drawbacks of this approach, and would like others' input on my approach. Thanks in advance.

**Comment by hodoulp** [comment]
Note: Discussion started in #547

**Comment by hodoulp** [comment]
Hi,

The approach seems to be the right one, and most of the code is already using a `OCIO::OglAppRcPtr` so the transition should be fine.

However, `EGL` is nVidia specific and OCIO must **not** stick to a specific vendor. Even if the CI build system is running on nVidia graphic cards that should not be mandatory for our users (e.g. using an app to debug or investigate a color transformation) & contributors (e.g. running GPU unit tests on their machine).  How do you plan to handle that?

Ideally the code should detect the graphic card vendor and auto adjust itself to the right 'headless implementation' (i.e. perhaps using `glGetString(GL_VENDOR)`?).

Here is a list of apps needing oglApp, with a transition proposal:
* ociochecklut -> `HeadlessApp`
* ocioconvert -> `HeadlessApp`
* ociodisplay -> `ScreenApp`
* ocioperf -> `HeadlessApp`
* GPUHelper -> `HeadlessApp`, that's the use case to handle.

**Comment by ChinYing-Li** [comment]
Thank you for the input. My work-around for the vendor specific problem is to use the EGL implementation of Mesa, which should be available on most if not all Linux machines.

**Comment by hodoulp** [comment]
Some useful links: https://www.khronos.org/egl & https://devblogs.nvidia.com/egl-eye-opengl-visualization-without-x-server/

**Comment by doug-walker** [comment]
@ChinYing-Li, thanks for your work on this!  

I'm worried about relying on Mesa for non-Nvidia hardware.  We have tried using Mesa several times over the years and it has resulted in large numbers of GPU unit test failures.  Perhaps Mesa would work better now, but if not, we would need to find another solution.  It is definitely a requirement that the GPU unit tests continue to run on AMD/ATI hardware (which apparently don't have EGL support yet?).

**Comment by jfpanisset** [comment]
These Blender threads seem to point at recent efforts to bring back EGL headless rendering, as well as comments about needing to request "Core" rather than "Compatibility" profiles from the driver. 

https://developer.blender.org/T54638
https://developer.blender.org/D6585

So perhaps some useful info to be mined there?

**Comment by ChinYing-Li** [comment]
Steps are as follows:

1. **Install Mesa with EGL backend**
(TO BE UPDATED)

2. **Get findEGL.cmake**
```
git clone git://anongit.kde.org/extra-cmake-modules
cd extra-cmake-modules
mkdir build
cd build
cmake .. # or run : cmake -DCMAKE_INSTALL_PREFIX=/usr .. &&
make
sudo make install
```
This will install the extra-cmake-module module, which contains findEGL.cmake.

3. **Build OpenColorIO with the option OCIO_USE_HEADLESS**
Remember to add the line below at the `sudo cmake` step.
```
-D OCIO_USE_HEADLESS=ON
```

**Comment by ChinYing-Li** [comment]
Thanks for all the pointers! Interestingly, I did not encounter the issue mentioned in the blender posts.

**Result of `GPU Unit tests`**
```
cyli@cyli-MacBookAir:~/repo/OCIO_exp_build/tests/gpu$ ./test_gpu_exec
GPU unit tests used N19OpenColorIO_v2_0dev11HeadlessAppE

GL Vendor:    Intel Open Source Technology Center
GL Renderer:  Mesa DRI Intel(R) HD Graphics 5000 (HSW GT3)
GL Version:   3.0 Mesa 20.0.4
GLSL Version: 1.30

EGL Vendor:    Mesa Project
EGL Version:   1.4

OpenColorIO_Core_GPU_Unit_Tests

# test results ommitted 
#    .
#    .
#    .

[145/147] [RangeOp / arbitrary_1_no_clamp                    ] - PASSED - (MaxDiff: 1.19209e-07 at pix[43709][0])
[146/147] [RangeOp / arbitrary_2                             ] - PASSED - (MaxDiff: 1.19209e-07 at pix[29207][1])
[147/147] [RangeOp / arbitrary_2_no_clamp                    ] - PASSED - (MaxDiff: 4.76837e-07 at pix[58016][2])

0 tests failed
```

**Comment by hodoulp** [comment]
> extra-cmake-modules
Other pull requests (#1016) are moving `cmake` version from 3.10 to 3.12, would that be enough for `findEGL`?

**Comment by ChinYing-Li** [comment]
@hodoulp 
Sorry that I have to delete the pull-request since I accidentally signed-off other people's commits and could not revert them. 
To answer your first question:
_Note 1: You can see build breaks with github actions by clicking on 'details' corresponding to the failing build._
The break on OSX is because glut header is not included.
