### ISSUE TITLE
Python tests always build even if OCIO_BUILD_PYTHON is off

### ISSUE THREAD

**Issue by LazyDodo** [AcademySoftwareFoundation/OpenColorIO#1050]
#1025 updated the python tests, but forgot to un-comment the `OCIO_BUILD_PYTHON` test in cmake [that protected it](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/tests/CMakeLists.txt#L23), meaning they are always on now and you can't build OCIO without python.

**Comment by hodoulp** [comment]
Good catch @LazyDodo 

Would you mind doing the pull request?

**Comment by LazyDodo** [comment]
Sorry, the CLA in place for this project prevents me from doing so.

**Comment by hodoulp** [comment]
You only need to register as an individual contributor or as a corporate contributor (with your legals approval first).

**Comment by LazyDodo** [comment]
That will only happen if there is a sizable/worthwhile contribution, the removal of 2 mistakenly placed `#`'s in a build script is quite some ways away from reaching that bar.

**Comment by LazyDodo** [comment]
Thanks troy!

**Comment by sobotka** [comment]
No problem!

I should have put the acknowledgement to @LazyDodo in the commit message. Perhaps @hodoulp can do it on the commit.

**Comment by LazyDodo** [comment]
that really doesn't really matter, don't worry about it.
