### ISSUE TITLE
Validate that all (public) classes, functions etc. are listed in the docs

### ISSUE THREAD

**Issue by Simran-B** [AcademySoftwareFoundation/OpenColorIO#1060]
The Doxygen -> Sphinx bridge *breathe* comes with a script `breathe-apidoc` to generate .rst files for all classes, structs, namespaces and files. This is useful to generate an API overview, but these files are then plainly added in alphabetical order, like:

```
.. toctree::
   :glob:

   class/*
```

Sean's approach is to use Sphinx directives for each unit, like:

```
.. doxygenfunction:: OpenColorIO::Baker::Create
```

https://github.com/scoopxyz/OpenColorIO-Docs/blob/master/docs/api/c_baker.rst

Functions etc. need to be added one by one, but with the advantage of being able to structure them in a meaningful way (including tabs for C++ and Python).

It's easy to miss something and it can get easily out of sync as the code changes, therefore some kind of checker script would be useful to validate that everything was added and is up-to-date. Some ideas:
- Own parser / regex for code and docs (brittle), compare if the symmetric difference of both sets is empty
- Hook into Sphinx/docutils to get access to its internal data structures / AST to get both sets
- Subclass/replace the doxygen directives to get the docs set

**Comment by scoopxyz** [comment]
Hey @Simran-B thanks for making this. I too am questioning the ability to keep on top of manually referenced API...

Doxygen has the concept of "groups" (https://www.doxygen.nl/manual/grouping.html) but I don't know if this carries over into Breathe...

**Comment by lgritz** [comment]
@scoopxyz It does. I use it extensively in the OIIO docs.

**Comment by scoopxyz** [comment]
Ah, good to know

**Comment by Simran-B** [comment]
So it is possible to declaratively group e.g. class methods in code instead of referencing individual members in the docs. Good to know indeed. But how would the tabs for C++ and Python then be done? Is it possible to combine with grouping in code, or would it mean to lose tabs and have separate areas in the docs for both APIs?
