### ISSUE TITLE
Create GH Issue for each section/task of OCIO v2 docs

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1067]
To help with the push of documenting OCIO v2 in preparation for being feature complete, we'll need to divide up the work to help contributors participate in the effort. We'll need to create GH issues for each task or logical block of content needing to be done based on the created documentation outline.

Each created issue should be added to the "Documentation Revamp" GH project for tracking. This issue can house discussion around how to break up this work as-needed.

**Comment by scoopxyz** [comment]
Layout of tasks...

# Working New Sphinx Build
- Enable ReadTheDocs build hook
- Add requirements file for RTD to pip install before build
- Push Python docstring extraction/macro/build PR
- Extract pybind11 /tools/mkdoc.py during build process through CMake
- Move sphinx template to vuepress theme
- Restructure hierarchy of .rst files
- override vuepress css to align with logo/colour-scheme

# Content
- Finalize ToC structure
- Write content...

# Design
- Logo
- Colour Scheme

# Website
- Pick suitable static site generator or HTML5 template
- Make temporary branch to replace `gh-pages` before release date

**Comment by ChinYing-Li** [comment]
@scoopxyz After looking into your recent PR, I think you are almost done with the "new sphinx build" tasks. Is there any other stuff that can be done in parallel?
