### ISSUE TITLE
[docs] Setup ReadTheDocs webhook

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#1070]
@michdolan or @doug-walker 

Would you be able to setup the webhook for RTD via the GitHub settings. The How-To is here:
https://docs.readthedocs.io/en/stable/webhooks.html#github

I'll send the project RTD URL over slack, just in case it imparts any elevated access/permission.

**Comment by michdolan** [comment]
Sure, I'll look into this.

**Comment by michdolan** [comment]
Ok, the webhook is setup. Let me know if it's not working as expected.

**Comment by scoopxyz** [comment]
Hmm, doesn't appear to be I'm getting permissions errors. Could you sign into ReadTheDocs with your GitHub account so I can add you as a maintainer.
You might have to the one to kick off the sync.

**Comment by scoopxyz** [comment]
@michdolan just a ping again, if you're able to setup a RTD account and click the following in the Admin panel:

![image](https://user-images.githubusercontent.com/22137450/88420259-853ca780-cdde-11ea-87f0-bdeea37cef32.png)
