### ISSUE TITLE
[docs] ReadTheDocs Maintainers

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#1071]
Anyone that wants to be able to manage/configure the OpenColorIO project on ReadTheDocs... please create an account there, or use your GitHub account, and tell me so I can add you to the list.

**Comment by carolalynn22** [comment]
I signed up via my GitHub.

**Comment by michdolan** [comment]
I signed up via my GitHub as well.

**Comment by doug-walker** [comment]
Same here, please add me.  Thanks Sean!

**Comment by scoopxyz** [comment]
Added you Doug.
@michdolan `michdolan` doesn't seem to work, did you use another name for the account?
