### ISSUE TITLE
Typo in Python Bindings GpuShaderCreator

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#1072]
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/b2d0d3b4653c5537d4aca7fc131cee3cd20261ad/src/bindings/python/PyGpuShaderCreator.cpp#L152-L153

get/set Language

**Comment by Deepak-suresh14** [comment]
@scoopxyz can you assign this to me , I am a newbie

**Comment by doug-walker** [comment]
This was fixed.
