### ISSUE TITLE
[diversity] Use inclusive language

### ISSUE THREAD

**Issue by Simran-B** [AcademySoftwareFoundation/OpenColorIO#1079]
As discussed in the TSC meeting on 2020-07-27 and the [ASWF #diversity Slack channel](https://academysoftwarefdn.slack.com/archives/C0152KSAJSJ/p1594730786066000), the term "sanity check" should be avoided as it is considered [ableist language](https://www.selfdefined.app/definitions/sanity-check/). I checked the OCIO source code for other terms, but there are just a few ones that should potentially be substituted.

1. _sanity check_: validate (perform check), smoke test, validity / plausibility / soundness check
2. _sane_, _insane_, _sanity_: valid, invalid, validity (syntactic?)
3. _dumb_: basic? (draft implementation)
4. _lame-ass_: boring, unpleasant, crude? (support code)
5. _whitelist_: [approved list](https://github.com/communitybridge/docs/search?q=whitelist&unscoped_q=whitelist), allow-list (CLA)
6. _master_: main? (Git branch)

1 and 2 are urgent to be renamed in time for v2, as they are used in a public interface. 3, 4 and 5 are trivial to replace. 6 would be a huge task... related: https://github.com/github/roadmap/issues/63

I also found the terms _stupid_, _crazy_ and _crippled_ in third-party code (comments/test data), but changing that seems out of scope.

**Comment by hodoulp** [comment]
Hi @Simran-B, Can we close the issue?

**Comment by Simran-B** [comment]
Yes and no... it is kind of a reminder for me to also check other ASWF projects and add something about inclusive language to the documentation.

**Comment by hodoulp** [comment]
If you want to keep track of other ASWF projects, the best would be to create a defect in their repo.
On the other hand having a disclaimer in the documentation is a great idea.

**Comment by Sayantani-sunshine** [comment]
Can I work in this issue?

**Comment by doug-walker** [comment]
@Simran-B , we have a volunteer for this issue.  I know a lot of this has already been implemented.  Please let us know if there is anything left to do or else close the issue.  Thx!
