### ISSUE TITLE
A cache for Processors

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1084]
Some applications would benefit from having a cache for Processor instances.  For example, some applications import hundreds of files and wind up requesting a conversion between the same pair of color spaces many times.  This is slow and could waste memory.  As another example, timeline-based applications have strict performance requirements and cannot wait to create a new Processor on each shot.

The OCIO context variable mechanism poses challenges in the development of a useful cache.  A naive solution would be to simply invalidate the entire cache whenever the context changes at all.  However, this would make it worthless for timeline-based applications since it is common for at least some part of the context to change on every shot.  Ideally, OCIO would be able to determine which context variables were used for the creation of a given Processor and use this information to invalidate the cache intelligently.

The generation of the cache key needs to be very fast, to make it suitable for timeline-based applications.

In addition to the original Processor, the optimized Processor, the CPUProcessor, and the GPUProcessor would be cached.

Unlike the existing file cache, which is global, the processor cache would be part of a config instance.

The API would provide a way to turn off the caching (e.g. for debugging purposes).

As discussed at a recent OCIO v2 working group meeting, we have been working on a cache and are creating this issue to collect thoughts and requirements.

**Comment by zachlewis** [comment]
This would be great. I'd love to be able to "pre-cache" a processor for a set of set of contexts in applications with multi-shot timelines. 

Would the cache persist when toggling it on and off?

Could the caches be serialized? I.e., as a catalog of ctfs for different permutations of context variables? That could be really handy.

**Comment by doug-walker** [comment]
@zachlewis , yes, an application should be able to build all of the Processors in a "pre cache" step in order to load the cache.  Requesting any of those Processors a second time should be very fast.

What we have will clear the cache when it is turned off.  We feel that this is an important part of turning it off, so we want to keep it that way.  However someone could add a third mode (beyond off and on) that would not flush the cache but also not add any new ones.

Our implementation of the cache itself will not support serialization.  You may already serialize arbitrary Processors as CTF, so maybe that helps for what you have in mind.  Although building the cache is not something you want to do while playing back a timeline, it's not like it takes a really long time to do either, so it's not clear that a feature for serializing the cache is worth the effort.

**Comment by hodoulp** [comment]
@zachlewis, The work is now completed and merged if you see some improvements you can still log another issue.
