### ISSUE TITLE
Unit testing python bindings of oglapphelpers

### ISSUE THREAD

**Issue by ChinYing-Li** [AcademySoftwareFoundation/OpenColorIO#1086]
Opening the issue for discussions.

After thinking this through, here are the options I come up with:

1. Python bind `OCIOGPUTest`  so that we can write the python equivalent of cpp GPU unit tests.
2. Write a custom python class `PyOCIOGPUTest` and write the python equivalent of cpp GPU unit tests; This is the approach I am taking now.
3. Come up with less complicated python unit tests that, unlike the cpp version, does not compare numerical results of gpu to that of cpu. For example, to test the python binding of `OpenGLBuilder::buildProgram` and `OpenGLBuilder::getProgramHandle`, we can something like the pseudo-code below: 
```
import PyOpenColorIO_oglapphelpers as OCIO_ogl
import PyOpenGL as GL

shaderdesc = OCIO.GpuShaderDesc
builder = OCIO_ogl.OpenGLBuilder(b)
some_string = "some client shader program"
build.buildProgram(some_string)

handle = build.getProgramHandle()
glValidateProgram( handle )
validation = glGetProgramiv( handle, GL_VALIDATE_STATUS )

assert(validation, GL_TRUE)
```
This approach creates a dependency `PyOpenColorIO`, hence not so ideal.

Approach number 2 seems like an overkill to mesince we are testing whether "the binding is correct" plus "other cpp classes/functions being called also works correctly ",  while I think the actual goal should be only the former. Though it may be a good reference for python developers so they don't have to look into cpp code to find out how to use PyOCIO.

Would love to know other pros and cons of each approach,

**Comment by hodoulp** [comment]
Not being a Python expert I notice that the 'writing' is more something like:
`import opencolorio as ocio`
or
`import opencolorio.oglapp as ogl`

Note: The module names seem to always be lower case.
