### ISSUE TITLE
"OCIO_INSTALL_EXT_PACKAGES" value check is case sensitive and does not raise an exception if an invalid value is passed.

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO#1103]
Hi,

Title says it all!

I was trying to figure out why the dependencies weren't pulled and I typed `-DOCIO_INSTALL_EXT_PACKAGES=all` instead of `-DOCIO_INSTALL_EXT_PACKAGES=ALL`.

The comparison should probably be case insensitive and raising an exception if an invalid value is passed.

Cheers,

Thomas

**Comment by michdolan** [comment]
Fixed by #1104 

Comparison is now case insensitive and an invalid value will result in fatal configuration error.
