### ISSUE TITLE
"Config.addDisplayView" requires passing "looks" while it was optional with "Config.addDisplay".

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO#1105]
Hi,

I noticed that `Config.addDisplayView` which seems to replace `Config.addDisplay` in OCIO 2 requires passing **looks** which I feel should be optional as it was with  `Config.addDisplay`:

```python
Traceback (most recent call last):
  File "/Users/kelsolaar/Documents/Development/colour-science/ampas/OpenColorIO-Config-ACES/opencolorio_config_aces/config/generate/config.py", line 234, in <module>
    generate_config(data, 'config.ocio')
  File "/Users/kelsolaar/Documents/Development/colour-science/ampas/OpenColorIO-Config-ACES/opencolorio_config_aces/config/generate/config.py", line 201, in generate_config
    config.addDisplayView(display, view, colorspace)
TypeError: addDisplayView(): incompatible function arguments. The following argument types are supported:
    1. (self: PyOpenColorIO.Config, display: str, view: str, colorSpaceName: str, looks: str) -> None
    2. (self: PyOpenColorIO.Config, display: str, view: str, viewTransform: str, displayColorSpaceName: str, looks: str, ruleName: str, description: str) -> None
Invoked with: <PyOpenColorIO.Config object at 0x10aea4670>, 'sRGB Monitor', 'sRGB - sRGB', 'View - sRGB Monitor - sRGB'
```

Cheers,

Thomas

**Comment by hodoulp** [comment]
Hi @KelSolaar 
The `looks` argument for `Config::addDisplayView()` is optional so an empty string argument should work (refer to [OpenColorIO.h at line 612](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/include/OpenColorIO/OpenColorIO.h#L612) for the explanation).

**Comment by doug-walker** [comment]
@KelSolaar , the C++ API has not changed from v1.  Just as in v1, the idea is to pass an empty string if you don't have any looks.  As Michael wrote on Slack, the Python version could certainly be enhanced to make the Look argument optional.  But, as Patrick wrote above, the C++ version should stay as it was.

**Comment by KelSolaar** [comment]
> Hi @KelSolaar 
> 
> The `looks` argument for `Config::addDisplayView()` is optional so an empty string argument should work

Hi @hodoulp,

Sorry if I sound pedantic but this is a required argument as you have to pass a value, empty string is effectively one. An optional argument is an argument that adopts a default value as part of the function signature and does not need to be passed at all when calling the function.

Typically in Python you should not have to pass an empty string here and it was not the case with OCIO 1, so this feels certainly like a regression. Not only old code will break instantly which is not great as your first experience trying OCIO 2 but usability has reduced for the Pythonistas.

Also I might have missed it but I did not see anywhere that the method was renamed in the docs and found it by introspecting the Python object.

**Comment by doug-walker** [comment]
The section of the docs that describes upgrading to v2 does list it as one of the changes.  But we should do more to make it clearer.

**Comment by KelSolaar** [comment]
Ah thanks, I missed it! Maybe a large table describing the changes?

**Comment by hodoulp** [comment]
Hi @KelSolaar,

At the next TSC meeting I will bring the optional argument for the Python bindings to the attention of everyone. Having a rule for C++ does not mean to have the same for Python, and the optional arguments are common practice in Python.

The C++ API backward compatibility is a major focus from v2 in order to ease the transition from v1 to v2. Even if new features imposes renamings and/or changes we try to stay close to the original methods/classes, and to document the changes. So, that must also apply to the Python bindings. But we now must to agree on the rule (accepted or not) and how to implement it (optional argument, several methods, etc.).

**Comment by KelSolaar** [comment]
Thanks @hodoulp! I can't come as they are very early for me but glad you brought it and I saw it in the TSC notes in #1107 and I can see that @michdolan is already on it via #1108.
