### ISSUE TITLE
Good first documentation issue -- finish the cmd-line tools section

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1115]
The documentation for the command-line tools is here:

https://opencolorio.readthedocs.io/en/latest/guides/using_ocio/using_ocio.html#tool-overview

Some of the tools (ocioconvert, ociodisplay, etc.) have virtually no information.  Those tools need to have proper documentation like the other ones.

For new contributors, first read the Quick Start for Contributors:
https://opencolorio.readthedocs.io/en/latest/quick_start/for_contributors.html

Then edit this RST file:
docs/guides/using_ocio/tool_overview.rst

See this file for how to preview your work:
docs/V2_DOC_README.md

Then submit your PR for the updated RST file!

**Comment by zachlewis** [comment]
I'll take the case!

**Comment by doug-walker** [comment]
Thank you Zach!

**Comment by zachlewis** [comment]
Please, it's pretty much the least I can do. In a few weeks' time, I should be free to contribute to more documentation in general, whatever you guys need help with.

No promises, but I'll try to have something to look at before the docs meeting this Friday (I'll show up to that too -- noon, EST, right?)


I'll harass you guys on Slack with any specific questions.

**Comment by zachlewis** [comment]
yikes -- i accidentally unassigned myself while trying to update the task

**Comment by doug-walker** [comment]
Closing this as it was done with PR #1164.
