### ISSUE TITLE
Write OpenFX plug-ins for OCIO v2

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1117]
Particularly as we wait for applications to integrate OCIO v2, it would be awesome to have OpenFX plug-ins that use the new library to aid testing.  

Looking for a volunteer to take this on!   The Autodesk team will be happy to consult and it could be a nice learning opportunity for someone.

Also, please note that there are some existing OpenFX plug-ins for OCIO v1 that could be studied as examples, however we are looking for new plug-ins to be written from scratch that could be included in the OCIO repo.
Natron:
https://github.com/MrKepzie/openfx-io/tree/master/OCIO
TuttleOFX:
https://github.com/tuttleofx/TuttleOFX/tree/develop/plugins/image/process/color/OCIO

We would especially like to have plug-ins to wrap ColorSpaceTransform, DisplayViewTransform, and FileTransform.  The goal would be to leverage the new v2 features where possible.  These could also serve as a nice reference for application developers looking to upgrade to v2.

Resources for OpenFX
-----------------------
The Open Effects Association website:
http://openeffects.org/

OpenFX Programming Guide on ReadTheDocs:
https://openfx.readthedocs.io/en/doc/Guide/index.html

OpenFX repo on GitHub, which contains example plug-ins:
https://github.com/ofxa/openfx

List  of host apps that may be used to test the plug-ins:
https://en.wikipedia.org/wiki/OpenFX_(API)

Recommended approach:

1) Download the official OpenFX example plug-ins, compile them, and test that they work in your host app of choice.
2) Read the Programming Guide.
3) Start with one of the example programs such as openfx/Examples/Invert or Basic and start modifying it to call OCIO.

**Comment by abhisht51** [comment]
Hi, 
I would like to volunteer for this opportunity.

**Comment by doug-walker** [comment]
Thanks @abhisht51 for volunteering!  Please check out the Contributor Quick Start guide and join us on Slack.  
https://opencolorio.readthedocs.io/en/latest/quick_start/for_contributors.html

And let us know how we can assist you!

**Comment by doug-walker** [comment]
Abhist51 was not able to make progress this project, so we are still looking for someone to take this on.  Any volunteers out there that could help us with this?  This is a high priority project for us.

**Comment by EmperorYP7** [comment]
I would like to work on this issue. It'll be great if you guide me through this.

**Comment by doug-walker** [comment]
An initial set of OFX plug-ins were added in PR #1371.  Closing as fixed.
