### ISSUE TITLE
FileTransform Python API constructor

### ISSUE THREAD

**Issue by remia** [AcademySoftwareFoundation/OpenColorIO#1121]
Hey,

While using / testing the v2 API, I noticed that the PyOpenColorIO.FileTransform constructor used with a single argument returns an error due to the default interpolation being `INTERP_UNKNOWN`. To have it work, you need to explicitly set the `interpolation` parameter.

```
config = PyOpenColorIO.Config.CreateRaw()

my_transform = PyOpenColorIO.FileTransform("/path/to/lut.spi1d")
processor = config.getProcessor(my_transform).getDefaultCPUProcessor()
res = np.array(processor.applyRGB([0.5, 0.5, 0.5]))
> PyOpenColorIO.Exception: 1D LUT does not support interpolation algorithm: unknown
```

Maybe this default value could be replaced with INTERP_DEFAULT instead of INTERP_UNKNOWN, so that it works out of the box as you could expect from a Python API. https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/OpenColorIO/transforms/FileTransform.cpp#L37

There may be others transforms affected, granted that you would not typically use transforms directly but it's useful to test / debug things !

**Comment by doug-walker** [comment]
@remia , you raise a good point.  We will take an action item to make a PR to propose a fix.

**Comment by hodoulp** [comment]
@remia The pull request takes longer than expected because we use that opportunity to improve the support of the interpolation. You should see a pull request soon.

**Comment by hodoulp** [comment]
@remia The issue is fixed by Bernard's works. When you have time could check and close the issue? thanks.

**Comment by remia** [comment]
Just ran the test script again and it works as expected, thanks @BernardLefebvre !
