### ISSUE TITLE
Documentation: Investigate hierarchy issues in sidebar

### ISSUE THREAD

**Issue by carolalynn22** [AcademySoftwareFoundation/OpenColorIO#1136]
Some interesting things going on in the sidebar navigation:

https://opencolorio.readthedocs.io/en/latest/concepts/_index.html#concepts

So here, on the side, only Overview and Publications show up, though seemingly Introduction, Internal Architecture Overview, and Glossary would be on the same level and therefore should show up.

**Comment by chrisbrejon** [comment]
Meeting of 2020/09/11, after further investigation, we have double-checked and it is normal that overview and publications are listed in the side bar as they are listed in the _index.rst and have a folder for each one. Therefore we could probably have a look at why "Introduction" and "Internal Architecture Overview" are listed on the same level.
