### ISSUE TITLE
Ubuntu install on windows to write documentation

### ISSUE THREAD

**Issue by chrisbrejon** [AcademySoftwareFoundation/OpenColorIO#1145]
Hello everyone, 

following the meeting of September 18th of 2020, I create this issue to keep track of our conversation on slack.
The idea is to make a tutorial for windows users and non-developers who would like to participate on the V2 Documentation Effort.

Here is a summary :
- My first error was to install the wrong version of Ubuntu. I needed to download Ubuntu 20.04 LTS at this link : 
https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab

- Once this was done, I had to install some requirements. The command listed in this page : https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/docs/V2_DOC_README.md did not work for me.  
Here is the error I got :
```
pip install -r docs/requirements.txt
Command 'pip' not found, but there are 18 similar ones.
```
So, I used these commands instead : 
```
sudo apt install cmake
sudo apt install python3-pip
pip3 install -r docs/requirements.txt
```
I honestly don't know if the cmake one was necessary. Then I got more issues : 
`sphinx-build: command not found`
which was weird since I did the install : `pip3 install -r docs/requirements.txt`

Here is the message I got after the install :
`Successfully installed Sphinx-3.2.1 alabaster-0.7.12 babel-2.8.0 breathe-4.21.0 commonmark-0.9.1 docutils-0.16 imagesize-1.2.0 packaging-20.4 pygments-2.7.0 pyparsing-2.4.7 pytz-2020.1 recommonmark-0.6.0 snowballstemmer-2.0.0 sphinx-press-theme-0.5.1 sphinx-tabs-1.3.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4`

Then Simran indicated me that : _Looks like Sphinx got installed, but you might have to add it to the PATH environment variable if you want to be able to call sphinx-build without specifying its path._

I executed this command : `find / -name "sphinx-build"`
which gave me : 
`/home/chrisbrejon/.local/bin/sphinx-build`

So I ran `export PATH=/home/chrisbrejon/.local/bin:$PATH` and `sphinx-build --version`
Even if Simran stated that : _the PATH change isn't permanent I believe, you might want to add the export command to a script which executes automatically, e.g. see_ https://askubuntu.com/questions/887442/how-to-permanently-set-an-environment-variable
I didn't look into that because it looked super complicated.

Then I had to run `sudo apt install firefox` and got another error : `Error : no DISPLAY environment variable specified`
Simran suggested that _I think the problem is that virtual Ubuntu is a terminal with no display, so no browser inside this guest system_

So @carolalynn22 suggested to run one of these commands : 
```
   1  export DISPLAY=:0 # in WSL 1
   2  export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0 # in WSL 2
   3  export LIBGL_ALWAYS_INDIRECT=1
```
_If you are on WSL 1, do line 1. if 2, do line 2. then run line 3 - then try your firefox command again_

I ran the second command and got this error : `unable to init server: broadway display type not supported..`
Which made me give up.

Simran did note that this worked for him : 
```
sudo apt update
sudo apt install python3-pip
```
Then @michdolan stated that : _Just wanted to re-mention one point regarding getting Sphinx and other dependencies installed. As long as you have Python 3 and pip installed, you can build the OCIO docs without installing any other dependencies using the following:_
```
mkdir build
cd build
cmake ../. -DOCIO_INSTALL_EXT_PACKAGES=ALL -DOCIO_BUILD_DOCS=ON .
make docs
```
_So no need to install Sphinx or get_ `sphinx-build` on `PATH` _or any of that. CMake, Python 3, and pip are the only requirments for that to work._

_If you have VSCode installed too, you can run_ `code .`  _from the OCIO source dir and there are plugins to preview RST without a browser or needing to build with Sphinx (for the most part)_ 

_If you need browser support from Windows installed Ubuntu, I would recommend just opening your Linux directory via Windows Explorer and double clicking the_ `index.html`  _in the build, which will launch your browser with the site_

------------------------------------------------------------------------------------------------------------------------------------

We could setup a meeting with @michdolan to start from scratch and then write a tutorial with very simple steps. Please note that I am hoping for a simple setup, nothing like web server approach or complicated stuff.

Thanks,
Chris

**Comment by hodoulp** [comment]
Without having all the answers I can highlight few extra steps to make the doc generation work.

Here are the steps I used on Windows 10, WSL, ubuntu 18:
- `sudo apt update`
- `sudo apt install python3-pip`
- `wget https://bootstrap.pypa.io/get-pip.py`
- `sudo python3 get-pip.py`
- `cmake -DCMAKE_BUILD_TYPE=Release -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_GPU_TESTS=OFF -DOCIO_BUILD_PYTHON=ON -DOCIO_BUILD_DOCS=ON -DPython_EXECUTABLE=/usr/bin/python3 ../.`

Note 1: `ubuntu 18` is Python 2 by default but `ubuntu 20` is Python 3 by default so, the extra argument for Python executable added to `cmake` should be useless in `ubuntu 20`.
-> `python --version` outputs the Python version

Note 2: The `pip` module and `pip` executable seem both mandatory to build the documentation. If true that must be changed to only use the `pip` module.

Note 3: The `cmake` command reduces the compilation time by compiling only what is strictly needed by the documentation.

**Comment by hodoulp** [comment]
> My first error was to install the wrong version of Ubuntu. 

`ubuntu 18` and `ubuntu 20` should both work except that the Python version is different as explained above.

> I honestly don't know if the cmake one was necessary. 

Needed to compile the project in order to have the python bindings.

> Then Simran indicated me that : Looks like Sphinx got installed, but you might have to add it to the PATH environment variable if you want to be able to call sphinx-build without specifying its path.

While compiling the documentation I noticed several of these warnings. Do not worry about that.

**Comment by Simran-B** [comment]
> While compiling the documentation I noticed several of these warnings. Do not worry about that.

There are warnings about Sphinx plugins not being in PATH indeed, but this was actually about the `sphinx-build` command itself. Installing Sphinx does not add it to PATH automatically.

While no browser can be run inside the guest Ubuntu system because of the lack of a display, one can serve the files through a web server (Python 3 has a built-in module for that) and access them with the host's (Windows) browser:

    python -m http.server --directory _build

One can also open the HTML files directly without serving them. The Ubuntu file system can be accessed via `\\wsl$\Ubuntu-20.04` in Explorer. In my case the URL to view the docs homepage is `file://wsl%24/Ubuntu-20.04/home/simran/OpenColorIO/docs/_build/index.html`.

**Comment by hodoulp** [comment]
@chrisbrejon & @michdolan Is the issue still valid?

**Comment by chrisbrejon** [comment]
Time flies... I cannot believe it has been more than a month already. Sorry I have been quite busy at work and would like to give this install a second opportunity. I'll let you know in a couple of weeks if that's fine with you. Thanks !

**Comment by hodoulp** [comment]
@chrisbrejon That's fine. You could perhaps coordinate your effort with @michdolan current work before taking some time to continue your investigations.

**Comment by chrisbrejon** [comment]
Hey everyone, sorry for the late reply. I am trying the install a second chance following the steps from @hodoulp 
I have these errors : 
```
 wget https://bootstrap.pypa.io/get-pip.py
--2021-01-14 20:21:14--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.12.175, 2a04:4e42:1b::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.12.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1886796 (1.8M) [text/x-python]
get-pip.py: Permission denied
Cannot write to ‘get-pip.py’ (Success).
```
And then this as well : 
```
$ cmake -DCMAKE_BUILD_TYPE=Release -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_GPU_TESTS=OFF -DOCIO_BUILD_PYTHON=ON -DOCIO_BUILD_DOCS=ON
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
I am running ubuntu 20.04.1 LTS on windows 10...
Sorry about that,
Chris

**Comment by chrisbrejon** [comment]
Hey everyone,
I am going to close this issue if you're fine with that.
Sorry to not have been able to contribute at all.
Chris
