### ISSUE TITLE
Installation with Python failing on MacOSX

### ISSUE THREAD

**Issue by jordibares** [AcademySoftwareFoundation/OpenColorIO#1165]
I have been doing a clean installation of a new laptop and found myself with an installation faliure, I am not sure is me or something has fundamentally change in the brew-core but the --with-python option is not working for me.

I would love to hear from others and perhaps check if it is something broken or I need more coffee.

The process is pretty straight forward

1) Installing homebrew
2) installing opencolorio as stated in the manual (https://opencolorio.readthedocs.io/en/latest/quick_start/installation.html)

       > brew install opencolorio --with-python

3) it fails and throws this message

      Error: invalid option: --with-python

**Is this the result of brew-core not supporting options? is the installation process now obsolete?**

4) I have also tried to install Python 3.8.6 via pyenv, this is my zshrc

`
# Python Setup using PyEnv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# OCIO Setup
export OCIO="/Users/jordi/Dropbox/Repos/aces/OpenColorIO-Configs/aces_1.0.3/config.ocio"
source /usr/local/Cellar/opencolorio/1.1.1_2/share/ocio/setup_ocio.sh
`

Thanks in advance.

**Comment by KelSolaar** [comment]
Hi Jordi,

*brew install opencolorio* should just work, that is how I got it set up on
my Macbook:

Kali:~ kelsolaar$ brew info opencolorio
> opencolorio: stable 1.1.1 (bottled), HEAD
> Color management solution geared towards motion picture production
> https://opencolorio.org/
> /usr/local/Cellar/opencolorio/1.1.1_2 (22 files, 3.8MB) *
>   Poured from bottle on 2020-07-19 at 19:09:51
> From:
> https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/opencolorio.rb
> License: BSD-3-Clause
> ==> Dependencies
> Build: cmake ✘, pkg-config ✔
> Required: little-cms2 ✔, python@3.8 ✘
> ==> Options
> --HEAD
> Install HEAD version
> ==> Caveats
> OpenColorIO requires several environment variables to be set.
> You can source the following script in your shell-startup to do that:
>   /usr/local/share/ocio/setup_ocio.sh
> Alternatively the documentation describes what env-variables need set:
>   https://opencolorio.org/installation.html#environment-variables
> You will require a config for OCIO to be useful. Sample configuration files
> and reference images can be found at:
>   https://opencolorio.org/downloads.html
> ==> Analytics
> install: 219 (30 days), 680 (90 days), 3,032 (365 days)
> install-on-request: 69 (30 days), 267 (90 days), 1,241 (365 days)
> build-error: 0 (30 days)
>

Cheers,

Thomas Mansencal - colour-science.org <https://www.colour-science.org> -
thomasmansencal.com <http://www.thomasmansencal.com>

**Comment by KelSolaar** [comment]
Hi Jordi,

`brew install opencolorio` should just work, that is how I got it set up on
my Macbook:

```shell
Kali:~ kelsolaar$ brew info opencolorio
opencolorio: stable 1.1.1 (bottled), HEAD
Color management solution geared towards motion picture production
https://opencolorio.org/
/usr/local/Cellar/opencolorio/1.1.1_2 (22 files, 3.8MB) *
  Poured from bottle on 2020-07-19 at 19:09:51
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/opencolorio.rb
License: BSD-3-Clause
==> Dependencies
Build: cmake ✘, pkg-config ✔
Required: little-cms2 ✔, python@3.8 ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
OpenColorIO requires several environment variables to be set.
You can source the following script in your shell-startup to do that:
  /usr/local/share/ocio/setup_ocio.sh

Alternatively the documentation describes what env-variables need set:
  https://opencolorio.org/installation.html#environment-variables

You will require a config for OCIO to be useful. Sample configuration files
and reference images can be found at:
  https://opencolorio.org/downloads.html
==> Analytics
install: 219 (30 days), 680 (90 days), 3,032 (365 days)
install-on-request: 69 (30 days), 267 (90 days), 1,241 (365 days)
build-error: 0 (30 days)
```

**Comment by jordibares** [comment]
Ohhh.. thanks KelSolar, that is GREAT.

**Comment by michdolan** [comment]
@jordibares did @KelSolaar 's explanation solve this for you? Okay to close this issue? Thanks

**Comment by hodoulp** [comment]
@jordibares, please close the issue if you have the answer to your question or update it; otherwise, I will close the issue. Thanks.
