### ISSUE TITLE
OCIO UI/UX standards

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1174]
As discussed in today's TSC meeting, the OCIO v2 stabilization period provides a good opportunity to discuss and agree upon standards and recommendations around UI/UX considerations while implementing OCIO v2 in host applications. Consistent UX will be really important particularly with many new UI-specific features.

This issue is intended to be an initial home for this discussion, including suggestions and mockups for how the color management experience can be improved through consistent OCIO v2 UX. #1117 could also be a good opportunity to test some of these ideas. If you have opinions on this topic, please share and present your ideas. Ultimately we would like to consolidate the outcome of this conversation into OCIO documentation with visual examples if possible.

**Comment by sobotka** [comment]
Only one note here, the display linear EOTF transform to finish off the display colourimetry side would be invaluable for DCC compositing.
