### ISSUE TITLE
Remove TRANSFORM_DIR_UNKNOWN

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1175]
The "unknown" value for the "direction" enums (for transform, view transform, and color space) requires a lot of error handling code throughout the library.  We feel that the "unknown" value is not bringing any benefits and that it would be simpler if all transforms are simply initialized in the forward direction.  We propose removing the "unknown direction" enumeration values from the API and cleaning up/simplifying the code to take advantage of not having to worry that the direction could be "unknown".

**Comment by zachlewis** [comment]
Good riddance. Are any of the other "unknown" enums beneficial?

**Comment by hodoulp** [comment]
@zachlewis, you can log an issue to those you think must be removed.
