### ISSUE TITLE
vcpkg - Update to support OCIOv2 when ready

### ISSUE THREAD

**Issue by hodoulp** [AcademySoftwareFoundation/OpenColorIO#1179]
Here are the current `vcpkg` discussions around OpenColorIO v1:
https://github.com/microsoft/vcpkg/issues/14113
https://github.com/microsoft/vcpkg/issues/14132

Here are the `vcpkg` configuration files:
https://github.com/microsoft/vcpkg/tree/master/ports/opencolorio
https://github.com/microsoft/vcpkg/tree/master/ports/opencolorio-tools

**Comment by michdolan** [comment]
If anyone has other package managers they would like OCIO support added to, please open additional issues for those. Any help is appreciated. I've started laying ground work for pypi support as an example, but happy to surrender that work to someone with time if there's interest as well.

**Comment by EvanAW** [comment]
Update: An issue for this has been opened in vcpkg’s repository 
https://github.com/microsoft/vcpkg/issues/18004, and a frequent contributor has assigned it to themselves.

**Comment by demoulinv** [comment]
vcpkg is now updated to v2.1.

**Comment by doug-walker** [comment]
Closing this as fixed.
