### ISSUE TITLE
PR #1167 broke OCIO version detection

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/OpenColorIO#1186]
In PR #1167, alterations to OpenColorABI.h.in removed a defined symbol  OCIO_VERSION in favor of  OCIO_VERSION_STR (which did not exist before).

This breaks other projects that depend on OpenColorIO and expect this symbol to be present. Among other problems, this means that if somebody had a FindOpenColorIO.cmake that looked for OCIO_VERSION to determine the version number, now that fails. If it switches to looking for OCIO_VERSION_STR, then it will fail if it encounters OCIO 1.x. Probably detecting the version in this way is how people enable/disable code paths that allow them to support 1.x or 2.x depending on what it finds, and in this chicken and egg problem, it doesn't know which to look for if it doesn't know which version it's dealing with. It could try to look for BOTH, but that's ugly and in any case it doesn't solve the problem of existing software breaking as soon as it encounters OCIO 2.x. 

I would recommend restoring OCIO_VERSION, even if you keep it undocumented and treat it as a deprecated synonym for OCIO_VERSION_STR, so that people depending on the old symbol don't have their builds broken.

**Comment by hodoulp** [comment]
Good catch.
