### ISSUE TITLE
spi-vfx and spi-anim configs fail validation

### ISSUE THREAD

**Issue by fnordware** [AcademySoftwareFoundation/OpenColorIO#1194]
If you run `ociocheck --iconfig spi-vfx/config.ocio`, you get a validation error:

`FileTransform can't use unknown interpolation. File: 'version_8_whitebalanced.spimtx'.`

The error is thrown [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/OpenColorIO/transforms/FileTransform.cpp#L100).

Does this mean the config needs an update?

Another question: should applications call validate() or should they just run if the config loads successfully?

**Comment by hodoulp** [comment]
Thanks @fnordware for the reporting the problem.

I tried on the latest commit from master, and it fails.

**Comment by doug-walker** [comment]
Thanks Brendan!  The config does not need an update, you found a bug in how we are handling the "unknown" interpolation attribute.  

Currently, loading a config checks that a v1 config does not use any v2 features but it does not run a validation on it.  So yes, I would recommend that you do run validate after loading a config.

**Comment by doug-walker** [comment]
@fnordware , this but was fixed in PR #1215.  Thanks for the report!
