### ISSUE TITLE
Update the version for a release candidate

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1196]
Per Larry's suggestion on the OCIO v2 mailing list, we should tag a version as a first release candidate to facilitate testing.  We first need a PR to adjust the version to identify itself as the 2.0.0rc1 version.

Here is the request from Larry that provides the more detailed rationale:

> Really testing this in a studio setting means making an internal release, then building the various downstream packages using that release, and so on, until we can really put it through its paces.
> 
> It would be very helpful if there were versioning and tagging support for this -- for example if you could tag a "developer preview" or "beta" and set a unique version number for it. This serves several purposes for the studios who are testing:
> 
> * It gives testers a hint about exactly which points the OCIOv2 dev team thinks are relatively stable testing points, versus just randomly picking whatever commit is at the top of tree (example: yesterday's top of OCIO master broke the build of OIIO, but tomorrow's will not).
> 
> * If we report problems, it gives us a precise nomenclature for telling you which of several possible snapshots exhibits the problems.
> 
> * It gives us a way to distinguish releases for our build and distribution process. For example, if the version today is reporting that it is 2.0.0, and that number will not change or be in any way distinguishable until the very day that the final v2 is released, how can our build systems and downstream packages tell the difference between the November testing preview, versus the final 2.0? How can we make a proper `#if OCIO_SOMETHING > XYZ` to do proper conditional compilation if the API or behavior changes between now and the release? How can a downstream package build request the testing previews versus the final release (once several "flavors" of 2.0 are installed on our systems)? 
> 
> All the reasons that make a studio need a different reported version for 1.0.0 and 1.0.1 also make us desire unique reported versions for testing previews.

**Comment by KelSolaar** [comment]
Thanks this is great, I can now point to a particular version :)

**Comment by doug-walker** [comment]
Following discussion at the TSC, it was decided to use 'beta1' rather than 'rc1' for this first tag.  This has now been implemented.  The tag (on the master branch) is 'v2.0.0-beta1'.
