### ISSUE TITLE
Getting the type of a transform returns the parent class.

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO#1211]
Hi,

As discussed on Slack, `type(my_builtin_transform)` returns the parent class, i.e. `<class 'PyOpenColorIO.Transform'>` and not `BuiltinTransform`.

Currently using something like that for comparing, which is not super elegant: `transform.getTransformType() == ocio.TransformType.TRANSFORM_TYPE_BUILTIN`

Cheers,

Thomas

**Comment by frankieeder** [comment]
Hey Thomas,

I've been meaning to try to start digging into the OCIO backend a bit and finally have some extra time in my schedule. I started taking a peek at this issue (that Colab notebook you put in Slack was super helpful), and on a first glance it seems to me like it might be related to some quirks with polymorphism in PyBind where it might be binding to an incorrect pointer type. Just to confirm, we would be looking to be able to do a more standard typing functionality like `type(transform) == ocio.TransformType.TRANSFORM_TYPE_BUILTIN`, like what seems to be possible for all other transforms, correct?

I'd be happy to try to give this a shot in the near future if someone could assign me to it.

Best,

Frankie

**Comment by doug-walker** [comment]
Assigning to you @frankieeder , thanks for your help!

**Comment by michdolan** [comment]
Thanks for your help @frankieeder . The goal would be to support this:

`type(transform) == ocio.BuiltinTransform`

Where it returns the `Transform` child class. Please note that there is some code in place in https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/bindings/python/PyOpenColorIO.h which supports `Transform` type downcasting in pybind11 via `polymorphic_type_hook`. This results in behavior like iterating a `GroupTransform` returning it's various child `*Transform` instances instead of all parent `Transform` instances.

**Comment by frankieeder** [comment]
Got it! Thanks for the additional detail as well, looking into it now.

**Comment by michdolan** [comment]
@frankieeder there are some additional clues in related issue #1254

**Comment by zachlewis** [comment]
To consolidate issues, here's what I wrote for #1254:

check it:

>>> import PyOpenColorIO as ocio

>>> group_transform = ocio.Config().getProcessor(
...         BuiltinTransform("ARRI_ALEXA-LOGC-EI800-AWG_to_ACES2065-1")
...     ).createGroupTransform()

>>> print(f"Looks as expected: \n\n", group_transform)

Looks as expected: 

<GroupTransform direction=forward, transforms=
        <LogCameraTransform base=10, logSideSlope=0.24719 0.24719 0.24719, logSideOffset=0.385537 0.385537 0.385537, linSideSlope=5.55556 5.55556 5.55556, linSideOffset=0.0522723 0.0522723 0.0522723, linSideBreak=0.010591 0.010591 0.010591, direction=inverse>
        <MatrixTransform direction=forward, fileindepth=unknown, fileoutdepth=unknown, matrix=0.6802055051062792 0.2361366016064812 0.08365789328723973 0 0.08541497974214032 1.017470878607042 -0.1028858583491822 0 0.002056521669296831 -0.06256250038479215 1.060505978715495 0 0 0 0 1, offset=0 0 0 0>>
however...

>>> print("[type(xf) for xf in group_transform])

[<class 'PyOpenColorIO.Transform'>, <class 'PyOpenColorIO.MatrixTransform'>]
As you can see, the second transform "unpacks" as a MatrixTransform instance, but the first transform is an instance of PyOpenColorIO.Transform -- meaning, none of the expected LogCameraTransform attributes or methods are attached to the instance.

**Comment by remia** [comment]
> Where it returns the Transform child class. Please note that there is some code in place in https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/bindings/python/PyOpenColorIO.h which supports Transform type downcasting in pybind11 via polymorphic_type_hook

Looks like adding `LogCameraTransform` and `BuiltInTransform` in there would solve this.

**Comment by michdolan** [comment]
Good catch @remia . That's definitely the issue here.

**Comment by frankieeder** [comment]
Thanks for the pointers all - I'm on it now (I've had some issues getting my dev environment set up). This is my first time contributing to OCIO, so I'm wondering if it would also be worth writing some Python tests per the contributing guide, and if so, whether I should include those and the patch on the same branch.

**Comment by michdolan** [comment]
Adding tests in the same PR would be great. Thanks!

**Comment by frankieeder** [comment]
Opened #1260 for review!

**Comment by doug-walker** [comment]
Closing as this was fixed in PR #1277.
