### ISSUE TITLE
Add support for new Imath repo for Half dependency

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1218]
With OpenEXR 3.0 on the horizon, Imath has been moved to a dedicated repository: https://github.com/AcademySoftwareFoundation/Imath

Since OCIO depends on Half, we should work toward supporting the new lighter-weight repo in OCIO_INSTALL_EXT_PACKAGES builds. This will also need to be tested in the "latest" nightly CI build, which pulls the most recent upstream tag.

**Comment by hodoulp** [comment]
The first official release of `Imath` 3.0.0 is planned for the 1st of April.

**Comment by AngryPenguinPL** [comment]
OpenEXR 3.0.4 and Imath 3.0.4 released few days ago. Is there any work being done to add support for the 3.X series?

**Comment by doug-walker** [comment]
This was done in 2.1.  Closing as fixed.
