### ISSUE TITLE
Serializing a v1 config must not omit required elements

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1236]
In OCIO v2, a v2 config is allowed to omit default or repetitive items.  However, if the config version is set to 1, these values should not be omitted so that the config is readable via an app using a v1 library.

For example, v1 would write an ExponentTransform like this:
`!<ExponentTransform> {value: [2.2, 2.2, 2.2, 1]}`
and v2 would write it like this:
`!<ExponentTransform> {value: 2.2}`

The v2 library should use the v1 syntax if the config version is 1.

**Comment by zachlewis** [comment]
Is this the same thing as "Serializing a v2 config may omit non-required elements"?

For instance, if I don't specify a color space allocation with the python API, the v2 config serializes as "uniform" regardless. 
(And it's worth mentioning the Python API only accepts "fully articulated" R,G,B tuples at the moment)

**Comment by doug-walker** [comment]
Closing this as fixed via PR #1244.
