### ISSUE TITLE
Python bindings: __str__ & __repr__ improvements

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1256]
In the Python bindings we are currently mapping the C++ `operator<<` output of supporting objects to `__str__`  instead of `__repr__` . The primary reasoning behind this was that the string output of a `Config` object prints the entire config, which can be enormous when dumped into a traceback (since Python will use `__repr__` in that case). That being said, for most other classes the output is likely more useful. 

`<LogCameraTransform base=10, logSideSlope=0.24719 0.24719 0.24719, logSideOffset=0.385537 0.385537 0.385537, linSideSlope=5.55556 5.55556 5.55556, linSideOffset=0.0522723 0.0522723 0.0522723, linSideBreak=0.010591 0.010591 0.010591, direction=inverse>`

vs.

`<PyOpenColorIO.LogCameraTransform at 0x11ab278f0>`

This is also a consideration in terms of documentation generation, since some docstrings which return static Python objects end up having an arbitrary object ID in the frozen RST, which creates a maintenance problem for updating documentation (since it will change every time the docs are rebuilt).

My proposal is that we switch over to `__repr__` for all objects except `Config`, which would maintain the `__str__` mapping. We could consider creating a custom `__repr__` method for `Config` just for Python use as well, with the config name, path, etc.

A note to anyone interesting in working on this. Most objects in our bindings share a `defStr` function from this header:
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/bindings/python/PyUtils.h

**Comment by BernardLefebvre** [comment]
Working on it.
Note that path is not saved in config.
