### ISSUE TITLE
Increase precision of computed LogCameraTransform parameters in LogC-AWG BuiltinTransform

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1258]
@nick-shaw noticed discrepancies between the Log C v3 EI800 ACEScsc and IDT definitions that more or less could be described as a difference in LogCameraTransform parameter precision -- the IDT computes logSideSlope with rational numbers (~0.24718963831867058 by my calculations), and the ACEScsc uses a less precise approximation (0.24719); net result is a measurable difference between the two functions, although I'm not sure how much significance to attribute to the difference. 

Granted, this should be reconciled in ACES itself, but I thought it was worth drawing attention to now, in the event ACES decides to conform to more precise parameterization. 

(Presumably, most of the BuiltinTransforms could employ more precise coefficients, but I'm sure the current parameterizations consciously mirror the ACEScsc  definitions)

I guess the questions are:
  1. Should we increase the precision of the LogC BuiltinTransform's `logSideSlope` parameter? 
  2. As a rule of thumb, how much precision is too much (i.e., unnecessary) precision? 8 digits or so?
  3. If we leave things alone for now, and AMPAS updates the LogC v3 EI800 ACEScsc transform to match the IDT after OCIO v2 is released, [how] would that be addressed in future versions of OCIO v2?

**Comment by nick-shaw** [comment]
To hold my hand up to this, while it is true that it was me who noticed the discrepancy, it was also me who wrote the CSC CTL, so the imprecise constants being there in the first place is my fault!

**Comment by doug-walker** [comment]
@zachlewis, the code in aces-dev ACEScsc.Academy.LogC_EI800_AWG_to_ACES.ctl seems to use the same value as OCIO transforms/builtins/ArriCameras.cpp, namely 0.2471896383.  Where do you see 0.24719?

The other minor issue with the IDT is that it uses a 1d-LUT whereas the CSC uses an actual power function, so that could also cause a small difference (although it is a 65536 entry LUT, so not much). 

I would have expected that the level of precision being used currently would be pretty good.  How are you measuring the difference and what is the max difference you found?

We would certainly welcome a PR that uses better precision if one of you gentlemen (or @JGoldstone) feel motivated to do so.  The underlying OCIO operator uses double precision, so you could increase the number of significant digits in the constants to 17.

**Comment by zachlewis** [comment]
Oy -- I'm sorry for the confusion, I should have looked closer (read: actually looked) at the code. Ignore me, those constants look solid. 

FWIW, here's how I came to my incorrect conclusion:
```
>>> import PyOpenColorIO as ocio
>>> proc = ocio.Config().getProcessor(ocio.BuiltinTransform('ARRI_ALEXA-LOGC-EI800-AWG_to_ACES2065-1'))
>>> print(proc.createGroupTransform[0])
```
```
<LogCameraTransform base=10, logSideSlope=0.24719 0.24719 0.24719, logSideOffset=0.385537 0.385537 0.385537, linSideSlope=5.55556 5.55556 5.55556, linSideOffset=0.0522723 0.0522723 0.0522723, linSideBreak=0.010591 0.010591 0.010591, direction=inverse>
```

I noticed that `logSideSlope` was rounded to 0.24179, while `linSideOffset` for example, is rounded to 0.0522723.
But I can see pretty plainly that the values are rounded only for the string representation:

```
>>> print(proc.write('Color Transform Format'))
```
```
print(proc.write('Color Transform Format'))
<?xml version="1.0" encoding="UTF-8"?>
<ProcessList version="2" id="$fb58b83f0035bdc8fb0b66cd13205668">
    <Log inBitDepth="32f" outBitDepth="32f" style="cameraLogToLin">
        <LogParams base="10" linSideSlope="5.55555555555556" linSideOffset="0.052272275" logSideSlope="0.2471896383" logSideOffset="0.3855369987" linSideBreak="0.0105909905" />
    </Log>
    <Matrix inBitDepth="32f" outBitDepth="32f">
        <Array dim="3 3">
  0.680205505106279   0.236136601606481  0.0836578932872397
 0.0854149797421403    1.01747087860704  -0.102885858349182
0.00205652166929683 -0.0625625003847921     1.0605059787155
        </Array>
    </Matrix>
</ProcessList>
```
So, I jumped to conclusions, and conflated a discrepancy Nick had pointed out re: the ACES CTL library with what I thought I was seeing in OCIO. Upon closer inspection, Nick was drawing attention to a discrepancy in a different part of the LogC computation anyway.

So I was wrong.

Dead wrong.

And I'm sorry.




Perhaps it's worth increasing the maximum precision in the string representation for LogCameraTransforms?

I do know the Log C v3 EI800 coefficients for the general form provided in the [Alexa Log C curve in VFX](https://www.arri.com/en/learn-help/learn-help-camera-system/white-papers) white paper are precise up to 6 decimal places; which, compared to coefficients derived from @JGoldstone's [v3_IDT_maker](https://github.com/ampas/aces-dev/blob/master/transforms/ctl/idt/vendorSupplied/arri/alexa/v3_IDT_maker.py), produces an ever so slightly different curve; although I'm not sure if it's a difference that can be appreciated at 10 bits.


Anyway, since you made it this far,  here are the LogC v3 EI800  linear scene exposure factor coefficients computed to 100 decimal places. 

```
ALEXA_LogC_v3_EI800_coefs = {
 'base': 10,
 'linSideBreak': 0.01057958259063980724094625273660638165631673133868116922772627806371390032891237278780238822291795921,
 'linSideOffset': 0.05233565227422328476281953631395106696528890585567332367486448131149424937817974109792602929620081212,
 'linSideSlope': 5.555555555555555,
 'linearSlope': 5.367654795272962564806039874585349028533314071040173869691488120358864549419888378227948398434566505,
 'logSideOffset': 0.3855305331234310637606977503400120574120751052031981577049742865473611825956329949128934024496712603,
 'logSideSlope': 0.2471896383186705722290850457051319819521268454328109773745463555288022957275491838421051700909932454,
}
```

💯

**Comment by doug-walker** [comment]
@zachlewis, we were about to make a PR with your proposed values but they are substantially different from what is in aces-dev, ACEScsc.Academy.LogC_EI800_AWG_to_ACES.ctl.  In other words, I was expecting just to add more digits.  Yours start diverging as soon as the fourth digit.  Could you shed some light on why they are so different?  Thanks!

**Comment by nick-shaw** [comment]
If it's useful, this is the code I used to generate the constants that are in the CSC:
```python
import numpy as np

EI = 800.0

midGraySignal = 0.01
encodingGain = 500.0 / 1023.0 * 0.525
encodingOffset = 400.0 / 1023.0
cut = 1.0 / 9.0
slope = 1.0 / (cut * np.log(10.0))
offset = np.log10(cut) - slope * cut
gain = EI / 400.0
encGain = (np.log2(gain) * -0.11 / 3.0 + 1.0) * encodingGain
gray = midGraySignal / gain



encOffset = encodingOffset
for i in range(3):
    nz = ((95.0 / 1023.0 - encOffset) / encGain - offset) / slope
    encOffset = encodingOffset - np.log10(1.0 + nz) * encGain

print("EI:", EI)
print("midGraySignal:", midGraySignal)
print("cut:", cut)
print("slope", slope)
print("offset", offset)
print("encOffset", encOffset)
print("gain", gain)
print("encGain", encGain)
print("gray", gray)
print("nz", nz)
```

**Comment by zachlewis** [comment]
> @zachlewis, we were about to make a PR with your proposed values but they are substantially different from what is in aces-dev, ACEScsc.Academy.LogC_EI800_AWG_to_ACES.ctl. In other words, I was expecting just to add more digits. Yours start diverging as soon as the fourth digit. Could you shed some light on why they are so different? Thanks!

Definitely, definitely go with what Nick suggests -- he actually knows what he's talking about, and I was just trying to be a smartass, computing values to 100 decimals (I was expecting you guys would just leave the builtin as-is!); anyway, in doing so, I also adjusted the number of iterations used for determining the "join", cuz I seemed to recall that "3 was good enough for 10-bit". Dumb.


Non-smartass-values using default numpy precision, derived from the above code:


```
ALEXA_Log_C_v3_EI0800 = {
    "linSideBreak": (cut - nz) * 0.18,
    "linSideSlope": (1.0 / 0.18),
    "linSideOffset": nz,
    "logSideSlope": encGain,
    "logSideOffset": encOffset,
    "linearSlope": encGain * slope / 0.18,
    "base": 10,
}
```

```
ALEXA_Log_C_v3_EI0800 = {
        'logSideSlope': 0.24718963831867058,
        'logSideOffset': 0.38553699869244257,
        'linSideSlope': 5.555555555555555,
        'linSideOffset': 0.052272275025168784,
        'linearSlope': 5.367654795272963,
        'linSideBreak': 0.010590990495469618,
        'base': 10
}
```
