### ISSUE TITLE
PyOpenColorIO Processor.getDynamicProperty() doesn't return a Python type

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1262]
Stumbled on this issue in the Python bindings for `v2.0.0-rc1`

`DynamicProperty` can be returned from a `CPUProcessor`, but not from `Processor`. We are wrapping `DynamicProperty` in a `PyDynamicProperty` wrapper, which is not being used in this case.

```
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: PyOpenColorIO.Processor, type: PyOpenColorIO.DynamicPropertyType) -> OpenColorIO_v2_0rc1::DynamicProperty
```

**Comment by BernardLefebvre** [comment]
Will fix
