### ISSUE TITLE
Add texture value accessor to GpuShaderDesc Texture and Texture3D Python objects

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1263]
Currently the Python GpuShaderDesc iterators for getting texture and 3D texture info only expose attributes about those textures but not their data. Texture values are accessed through dedicated methods which are index based. That works, but feels a bit clunky now that I am implementing it in a tool. We should ideally be able to do this:

```
for tex in shader_desc.get3DTextures():
    name = tex.textureName
    data = tex.getValues()
```

Rather than:

```
for i, tex in enumerate(shader_desc.get3DTextures()):
    name = tex.textureName
    data = shader_desc.get3DTextureValues(i)
```

**Comment by BernardLefebvre** [comment]
I can try
