### ISSUE TITLE
Python GpuShaderCreator/GpuShaderDesc missing uniform interface

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1264]
The Python binding for `GpuShaderDesc` and `GpuShaderCreator` is currently missing `UniformData`, `getNumUniforms`, `getUniform`.

**Comment by michdolan** [comment]
`getShaderText` is missing too.

**Comment by michdolan** [comment]
@BernardLefebvre I can fix this one, but wanted to check if you were working on it already?

**Comment by BernardLefebvre** [comment]
@michdolan you can go ahead, I did not look into this one.
