### ISSUE TITLE
PyOpenColorIO.so attempts to link to incorrect libHalf-2_4.a path (when Half is compiled as part of the build process)

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1302]
This is only affecting my linux (Ubuntu-18.0.4) builds -- not my osx builds (which use the exact same build scripts).

Strangely, I'm nearly certain nothing has changed on my end since I last successfully built 2.0.0rc1 a couple weeks ago (as that was the last thing I did on my linux machine, and all dependencies are very carefully controlled for with rez, so system updates aren't likely to be the culprit); but today, I'm experiencing the same failure whether building the 2.0.0 release or pulling the "v2.0.0-rc1" tag. 

I haven't investigated much further, and I'd like to triple-check things on my end, but this might suggest an upstream change with libHalf master branch (presuming the OCIO build isn't pulling a specific libHalf commit...)

Behold! An angry terminal:
```
...
-- Installing Half (IlmBase): /sw/dev/zlewis/internal/rez_repo/libs/OpenColorIO/build/ff4bd6c0aed20c905d928272af431e962084b5c6/ext/dist//home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/lib/libHalf-2_4.a (version "2.4.0")
...
-- Installing pystring: /sw/dev/zlewis/internal/rez_repo/libs/OpenColorIO/build/ff4bd6c0aed20c905d928272af431e962084b5c6/ext/dist/lib/libpystring.a (version "1.1.3")
...
```

Note the different install locations for Half and pystring.
The behavior with pystring is correct, and representative of what happens with other missing libraries. `libpystring.a` is compiled to `<build_dir>/ext/dist/lib`

Half, on the other hand, allegedly installs to `<build_dir>/ext/dist/<install_prefix>/lib` -- which is, in fact, a dirty, filthy lie. `libHalf-2_4.a` in fact correctly ends up in the same location as the other freshly-built formerly-missing external libraries; but the incorrect path is referenced when linking PyOpenColorIO.so, and subsequently breaks the build process:

```
...
g++: error: ext/dist//home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/lib/libHalf-2_4.a: No such file or directory
ninja: build stopped: subcommand failed.
16:00:22 ERROR    BuildError: The custom build system failed.
```

**Comment by michdolan** [comment]
This may be related to a change we made to how OCIO finds OpenImageIO for building apps (between rc1 and final). We moved away from relying on the OIIO CMake config (for now) and are instead using the OIIO provided CMake find module. 

This was because the newer OIIO CMake module calls to the OpenEXR CMake module, which when using our isolated Half target can create a CMake target conflict (since OpenEXR's CMake module doesn't find the Imf targets, etc.). 

One possible solution, if you are relying on the static dependencies being built into OCIO, is to call cmake with `-DOCIO_INSTALL_EXT_PACKAGES=ALL`, which will force the Half target to use a lib in ext rather than trying to find it, which may be what is tripping this up.

**Comment by zachlewis** [comment]
Hmmm... actually, setting `-DOCIO_INSTALL_EXT_PACKAGES=ALL` actually revealed that the same problem happens with expat as well!

```
c++: error: ext/dist//home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/lib/libexpat.a: No such file or directory
c++: error: ext/dist//home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/lib/libHalf-2_4.a: No such file or directory
ninja: build stopped: subcommand failed.
```

No problem building or linking the other dependencies...
...although I did just notice that pybind11 finds and uses a different python interpreter than the one I'm building PyOpenColorIO against...!

```
...
...
-- Found Python: /home/zach/packages/python/3.7.4/platform-linux/arch-x86_64/os-Ubuntu-18.04/bin/python3.7 (found version "3.7.4") found components: Interpreter Development 
...
-- pybind11 v2.6.1 
-- CMake 3.17.0
-- Found PythonInterp: /opt/rez/bin/python (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
...
```

(I've been providing a Python_ROOT environment variable... but I'll experiment with setting the various python Cmake options explicitly for the executable and libs.)

**Comment by zachlewis** [comment]
(sorry, that second part should probably be a separate ticket. need to explore further, to see if it's a zach thing or not)

**Comment by michdolan** [comment]
Paths like `ext/dist//home/zach/packages/OpenColorIO` seem suspect. It seems like these:
```
ext/dist//home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/lib/libexpat.a
ext/dist//home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/lib/libHalf-2_4.a
```
should be something like:
```
/home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/ext/dist/lib/libexpat.a
/home/zach/packages/OpenColorIO/2.0.0.0/ff4bd6c0aed20c905d928272af431e962084b5c6/ext/dist/lib/libHalf-2_4.a
```
Can you share your exact cmake command and some insight into your directory structure for reference?

**Comment by zachlewis** [comment]
**Figured it out!**

I was setting "-DCMAKE_INSTALL_LIBDIR=<install_prefix>/lib" (needlessly I suppose).

If you're curious, I use [rez](https://github.com/nerdvegas/rez) at home (osx-10.14.6, ubuntu-18.04) and at work (centos-7.4) -- it's a platform-agnostic package manager used fairly widely in VFX for resolving reliable environments for building and running stuff. And here's my [OCIO rez package definition](https://gist.github.com/zachlewis/397c2c622042646c6cbe150824858212).

Rez lets you build multiple "variants" of a package all in one go -- for instance, for OCIO, I'm building six variants per platform/arch/os: python-2.7, python-3.7, and python-3.8, shared and static. That gnarly `ff4bd6c0aed20c905d928272af431e962084b5c6` is a hash representing a single variant (['platform-linux', 'arch-x86_64', 'os-Ubuntu-18.04', 'python-3.7.4', '.shared-0']). 

When you build stuff with rez, it creates a separate build directory for each variant (in my case, `/sw/dev/zlewis/internal/rez_repo/libs/OpenColorIO/build/<variant_hash>`); and when it installs stuff, it installs to a central repository (in my case `~/packages/<package_name>/<package_ver>/<variant_hash>`). Because I was setting the DCMAKE_INSTALL_LIBDIR option to the OCIO install path, I suppose expat and half got excited and passed that information on to the linker (even though the libraries were in fact correctly output to `<build_path>/ext/dist`). 

Anyway... that solves that. One thing I wasn't able to figure out is why pybind11 selects the wrong python interpreter, but there are more cmake flags I could play with to see if I could force it to do the right thing. Fortunately, for the python-3.7 and 3.8 variants, even though the pybind11 build process selected the system python-3.6 interpreter, all the tests pass; and for python-2, it finds the correct interpreter (i.e., from my python-2.7.16 rez package).

Feel free to stick a fork in this ticket. Thanks Michael!
