### ISSUE TITLE
Strange getTextureValues problem when upgrading to OCIO 2.0.0 Release from OCIO 2.0.0 RC1 

### ISSUE THREAD

**Issue by luanbach** [AcademySoftwareFoundation/OpenColorIO#1304]
I've created the following function based on the ociodisplay example app and glsl.cpp.

    void generateLut1D(std::vector<float>& output, std::string& outSamplerName,
                                   unsigned int& width, unsigned int& height, const OCIO::GpuShaderDescRcPtr shaderDesc)
    {
      const unsigned maxTexture2D = shaderDesc->getNumTextures();
      for (unsigned idx = 0; idx < maxTexture2D; ++idx) {
        const char *textureName = nullptr;
        const char *samplerName = nullptr;

        OCIO::GpuShaderDesc::TextureType channel = OCIO::GpuShaderDesc::TEXTURE_RGB_CHANNEL;
        OCIO::Interpolation interpolation = OCIO::INTERP_LINEAR;
        shaderDesc->getTexture(idx, textureName, samplerName, width, height, channel, interpolation);

        if (!textureName || !*textureName || !samplerName || !*samplerName || width == 0) {
          throw OCIO::Exception("Failed to generate 1DLut texture.");;
        }

        const float *values = nullptr;
        shaderDesc->getTextureValues(idx, values);
        if (!values) {
          throw OCIO::Exception("Failed to get 1DLut texture values.");;
        }
    
        const auto channelCount = 3;
        const auto sampleSize = channelCount * width * height;
        output.insert(output.end(), &values[0], &values[sampleSize]);
        outSamplerName = samplerName;
      }
    }

This function worked perfectly up to the OCIO v2 RC1. When I updated to OCIO 2.0.0 Release build this function crashed at the line `output.insert(output.end(), &values[0], &values[sampleSize]);` It's as if the returned values pointer is invalid, I couldn't walk that pointer to read the content.
The only change made is the version of the OCIO 2.0.0 library from RC1 to Release. 

This is happening on the MacOS platform.

Does anyone have an idea of what has changed in the release build and what I should be doing instead?

**Comment by hodoulp** [comment]
Hi @luanbach,

When looking at the code I first notice that you've hard-coded the channel size which should not be. A LUT data could be `RGB` or `Red only` so, the code must be:
`const auto channelCount = channel == OCIO::GpuShaderDesc::TEXTURE_RGB_CHANNEL ? 3 : 1;`

The second point is that the method loops over all the LUTs (1D or 2D) needed for a specific color transformation but the method only expects one LUT. So, the returned `output` content will be the concatenation of all LUTs but returned `width` and `height` will come from the last LUT.

Note: The `OCIO::GpuShaderDesc` instance already contains & owns all the information around a specific color transformation so you could perhaps avoid copying it again into another instance. That's something I would investigate to avoid potential performance hit.

Hoping it will help you.

Patrick

**Comment by luanbach** [comment]
Hi @hodoulp,

Thanks for the reply.

I have thought about the channel count, the setting of `OCIO::GpuShaderDesc::TextureType channel = OCIO::GpuShaderDesc::TEXTURE_RGB_CHANNEL;` should have created a channel count of 3?

As to the 2nd point, I have yet to see a transformation with more than one LUT, but I guess I should check for that.

The last point is that we have our own rendering pipeline so we needed just the LUT texture data and the shader code that has been generated and creating resources for those in our own pipe line.

I'm not clear on why the update from RC1 to Release would break this code, though. As the code in GpuShader doesn't seem to have been changed in months.

Kind regards
Luan

**Comment by luanbach** [comment]
@hodoulp You are correct about the channelCount. Thanks. I guess I'll have to check for multiple textures as well. Any idea what was changed for this behaviour?

**Comment by hodoulp** [comment]
The LUT data is now 'optimized' to only keep the Red channel when all channels are identical.

With OCIOv2, the color transformation could contain any number of 1D, 2D & 3D LUTs (i.e. GPU textures) which is an important difference with the OCIOv1 GPU code path (where at most one 3D LUT was expected).

**Comment by luanbach** [comment]
Thank you.
