### ISSUE TITLE
Please explain in README how to build the python binding once the OpenColorIO library is installed

### ISSUE THREAD

**Issue by yurivict** [AcademySoftwareFoundation/OpenColorIO#1308]
There is one ```libOpenColorIO.so```, but there can be multiple python versions installed at the same time.

It should be possible to build the python binding once ```OpenColorIO``` is installed.

Could you please document in README how to build just the python binding?

**Comment by zachlewis** [comment]
As I understand it, currently, the build system requires that one builds the main OCIO libraries each and every time, regardless of whether one is interested in only building one of the optional components and linking to an existing build. I don't think this was an oversight, but maybe @michdolan or @hodoulp could provide additional insight...

(personally, I've been re-building static OCIO libs for multiple versions of PyOpenColorIO.so without a problem...)

**Comment by yurivict** [comment]
> As I understand it, currently, the build system requires that one builds the main OCIO libraries each and every time [...]

Problems with this are:
* Inefficiency: instead of building only python-related parts user has to rebuild everything.
* Install target still reinstalls all built libraries even though they were already installed.
