### ISSUE TITLE
Update homebrew to install OCIO v2, including all command-line tools

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1311]
We need to get homebrew updated to install OCIO v2.  This should simplify matters for many Mac users who have difficulty building OCIO from source.

**Comment by mjtitchener-fn** [comment]
I might be missing somether here but it looks like Homebrew has already been updated to 2.0.0 by someone.

https://formulae.brew.sh/formula/opencolorio

https://github.com/Homebrew/homebrew-core/commits/25a8b734e666b5976b797fd6cfae807e586e1e80/Formula/opencolorio.rb

<img width="734" alt="Screenshot 2021-02-16 at 15 13 50" src="https://user-images.githubusercontent.com/72390925/108082106-9e9e8d00-7069-11eb-9fba-6102b5e4c61e.png">

**Comment by doug-walker** [comment]
It does not install OIIO, so tools such as ocioconvert are missing.  The build options in the brew script also seem wrong.  

This issue is still open, if someone has time to work on it.

**Comment by mjtitchener-fn** [comment]
You're quite right Doug. Sorry, I forgot to look into this further as I've been using my own 2.0.0 build.

**Comment by nick-shaw** [comment]
The [Homebrew script](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/opencolorio.rb) has been updated to OCIO 2.0.1, but although you see a load of `openimageio dependency` stuff scroll past during the install, sadly it still does not install the OIIO dependent OCIO tools.

**Comment by doug-walker** [comment]
Given that Remi upgraded PyPI to install the command-line tools, and the fact that this issue has been open for several years and probably none of us have the necessary Homebrew expertise, I'm closing this.
