### ISSUE TITLE
Improve ocioperf by removing the OpenImageIO (OIIO) dependency

### ISSUE THREAD

**Issue by hodoulp** [AcademySoftwareFoundation/OpenColorIO#1314]
The command line tool `ocioperf` helps to investigate any performance hits independently from its integration in a host (Maya, Nuke, etc.). This first version provides the support to read an image (using OIIO). That's useful but it unfortunately increases the cyclic dependency problem between OpenColorIO and OpenImageIO.

The proposal is to replace an arbitrary external image by a in-memory generated one in float with an arbitrary value range (i.e. [0.0, 1.0], [-1.0, +2.0], etc.).

**Comment by hodoulp** [comment]
Hi @kanakgautam ,
Happy to see your interest in the OpenColorIO projet.

The change consists to remove the dependency to OpenImageIO from `ocioperf`, and replace it by a generated in-memory image. If you have interest in that task, the first step is to build the OpenColorIO library on your machine, and run unit tests. 

When successful, you can then remove the dependency to OpenImageIO, and generate an in-memory image. It means a RGBA float array with values [-1.0f, 2.0f] and a size of 1024. Both are applicable to the four color components. 

As extra, you can add command line arguments to specify the range (e.g. --range -1.0 2.0) and the number of values (e.g. --values 1024). 

In the context of the `Google Summer of Code` the two first steps are good enough to comply with the OpenColorIO prerequisite.

**Comment by kanakgautam** [comment]
Thanks a lot @hodoulp, I'll try to follow the steps you mentioned and send a PR asap. I'll let you know if I face any issues.

**Comment by doug-walker** [comment]
Closing.  This was fixed in PR #1516.
