### ISSUE TITLE
Errors building v1.1.1 against Python3.7 on Windows

### ISSUE THREAD

**Issue by tlm2021** [AcademySoftwareFoundation/OpenColorIO#1321]
Hello there,

I'm working on a migration to Python3, and I'm having trouble getting OpenColorIO building. I've used vcpkg to get started, but I'm quickly a bit down my own path.

For starters, there's a couple placed where in `OCIOMacros.cmake` that still have the Python2 print syntax when building on Windows ([1](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/v1.1.1/share/cmake/OCIOMacros.cmake#L142
), [2](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/v1.1.1/share/cmake/OCIOMacros.cmake#L208)).

I'm also not using the vcpkg version of Python, which is both not the version I need and doesn't have the source directories. Rather, I'm pointing to a local copy of Python3.7 that includes both. (Though I'm noticing that having those extra libs in the same directory as the Python executable is far from a universal convention, so more logging or docs around this requirement would be good).

After that, the core libraries build fine, but I hit this error when it gets to the Python bindings:
```
FAILED: src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyMain.cpp.obj 
C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe   /TP -DPYOCIO_NAME=PyOpenColorIO -DPyOpenColorIO_EXPORTS -DUSE_SSE -ID:\vcpkg\buildtrees\opencolorio\src\7e704498fe-32e68b4241\export -Iexport -Isrc\pyglue -ID:\sources\Python3\Win64\include -ID:\vcpkg\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /wd4275 /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /Fosrc\pyglue\CMakeFiles\PyOpenColorIO.dir\PyMain.cpp.obj /Fdsrc\pyglue\CMakeFiles\PyOpenColorIO.dir\ /FS -c D:\vcpkg\buildtrees\opencolorio\src\7e704498fe-32e68b4241\src\pyglue\PyMain.cpp
D:\vcpkg\buildtrees\opencolorio\src\7e704498fe-32e68b4241\src\pyglue\PyMain.cpp(153): error C2059: syntax error: '__declspec(dllexport)'
D:\vcpkg\buildtrees\opencolorio\src\7e704498fe-32e68b4241\src\pyglue\PyMain.cpp(154): error C2447: '{': missing function header (old-style formal list?)
```

Looking at that line [in the source](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/ebdec4111f449bea995d01ecd9693b7e704498fe/src/pyglue/PyMain.cpp#L107) that references the `OCIO_NAMESPACE_ENTER` macro. I don't see that included defined anywhere in the source files being built, but there is a definition in the [aftereffects tree](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/v1.1.1/src/aftereffects/vc/vc9/OpenColorABI.h).  That file also appears in an `export` directory in my build output directory (`[build_root]/export/OpenColorABI.h`)

My suspicion is that the `OpenColorABI.h` file should part of the build environment somehow, but isn't. Is that right? If so, how should I go about including it? If not, any other suggestions?

**Comment by tlm2021** [comment]
Hmm, how nervous should I be about building bindings against OCIO 2.0 before our whole facility switches the config formats?

The Python2->Python3 migration is already quite a tricky prospect. If that upgrade now also requires changes to the core color pipeline that's ... less than ideal.

**Comment by zachlewis** [comment]
"Changes to the core color pipeline" could mean a few different things... but the general theme is, you needn't feel _too_ nervous. 
OCIO-2.0 shouldn't have any trouble reading or writing 1.x configs -- so, if you're using an OCIO-v1-config-based-pipeline in your facility, everything should work at least well as before.
There's also a new GPU pipeline, but the legacy pipeline is also available.

 It's probably a good idea to build and link against static OCIO v2 libs, to avoid conflicts with shared OCIO v1 libs; and there are CMake options available for providing custom namespaces (eg, `-DOCIO_NAMESPACE=OpenColorIO_MyStudio`) or library suffixes (eg, `-DOCIO_LIBNAME_SUFFIX=foo`), if that helps to assuage concerns.

The public API has changed a little, so you'll likely need to update OCIO v1 pipeline code. As far as the python API goes, the changes are pretty easy to reconcile / benign at worst, and welcome improvements at best. 

Have a peek at the [upgrading to v2 guide](https://opencolorio.readthedocs.io/en/latest/upgrading_v2/_index.html#upgrading-to-v2)... admittedly, its focus is more on new features than using v2 libs with a v1 config / pipeline, but between that and the API docs, hopefully that will give you a better sense of whether its worth adapting v1 code to the v2 API along with your py2 -> py3 migration now, or if makes better sense for you to hold off on the py3 migration until your facility is closer to being ready to switch to v2 configs.

**Comment by tlm2021** [comment]
Thank you @zachlewis! That's exactly what I was looking for.

Looking at that guide, some of the notes to config authors had me concerned. As someone who doesn't author those, I wanted to scope out roughly how much I'd be biting off if I dove in and tried it.

Thanks for having a Python3 compatible release!
