### ISSUE TITLE
Add "--display" and "--view" options to ociobakelut tool

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1323]
Currently, `ociobakelut` makes it super easy to bake a LUT that converts from one colorspace to another. For example:
```
ociobakelut --inputspace 'logc' --outputspace 'acescg' --format cinespace logc_to_acesg.csp
```

It would be just **wonderful** if we could optionally specify a display + view instead of an output space. For instance:
```
ociobakelut --inputspace 'logc' --display 'DCI-P3' --view 'K1S1' --format cinespace logc_k1s1_p3.csp
```

**Comment by doug-walker** [comment]
Someone that wants to work on this could check out ocioconvert or ociowrite and do something similar.  Those just use one command line argument followed by the display and view strings.  That could potentially be done here as well and would be simpler to parse.

**Comment by zachlewis** [comment]
That's an excellent idea.

**Comment by KevinJW** [comment]
I usually try use a look for my view transforms so I can use the --looks option for this, as another hack I also use a Look with a environment/context variable as the input to a file transform to support adding LUTs to the baked files even when using a config.

Kevin

**Comment by remia** [comment]
I'll try to have a look at this issue next, including the refactor mentioned in the PR.
