### ISSUE TITLE
Error when building with OCIO_BUILD_APPS=OFF

### ISSUE THREAD

**Issue by remia** [AcademySoftwareFoundation/OpenColorIO#1334]
Extracting from an old issue as this is still present.

When building with `-DOCIO_BUILD_APPS=OFF`, I have a compilation error while building the `test_gpu_exec` target:

```
.../OpenColorIO/tests/gpu/GPUUnitTest.cpp:18:10: fatal error: 'oglapp.h' file not found
```

My current understanding is that the condition for the oglapphelpers target include in the build process may not be correct, https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/libutils/CMakeLists.txt#L4 at this point in the normal process, it seems that `test_gpu_exec` is not defined no matter what. This is because the `tests` directory is added after `src` (that itself includes `libutils`) here https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/CMakeLists.txt#L255. This is just a quick analysis, don't take my word for granted though.

_Originally posted by @remia in https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1261#issuecomment-762213735_

**Comment by hodoulp** [comment]
I did some tests with `master`:
- make (Linux) -> `cmake -DOCIO_BUILD_APPS=OFF ../.` and it works well
- ninja (Linux) -> `cmake -GNinja -DOCIO_BUILD_APPS=OFF ../.` and it works well
- make (MacOS) -> `cmake -DOCIO_BUILD_APPS=OFF ../.` and it **fails**
- ninja (MacOS) -> `cmake -GNinja -DOCIO_BUILD_APPS=OFF ../.` and it **fails**

**Comment by hodoulp** [comment]
@remia You found the problem. When using the targets the order of declarations in the root CMakeFiles.txt (lines 252 to 259) must be inverted so that a lower layer (e.g. utils, libutils, etc.) knows if an upper layer (apps, gpu tests, etc.) needs it.

**Comment by hodoulp** [comment]
@remia merged in `master`.
