### ISSUE TITLE
Overaggressive parsing of color space names in parseColorSpaceFromString()

### ISSUE THREAD

**Issue by code-monkey** [AcademySoftwareFoundation/OpenColorIO#1356]
If I feed the source filename `/tmp/caraway-seeds.jpg` into `parseColorSpaceFromString()` it returns `raw` as the source color space.  Perhaps the function should expect a non-alphanumeric character separator around the color space?

Tested in OCIO 1.1.1, though doing a cursory look at the HEAD code, it seems to still have this behaviuor.

**Comment by doug-walker** [comment]
The new File Rules feature introduced in OCIO v2 adds the ability to use Regular Expressions, so you could create patterns to use a delimiter character.
