### ISSUE TITLE
Building OCIO apps fails because it doesn't look for OpenEXR

### ISSUE THREAD

**Issue by JenusL** [AcademySoftwareFoundation/OpenColorIO#1358]
When building OCIO apps, OIIO is an dependecy. However, OIIO is in turn looking for OpenEXR, which isn't searched for at all by cmake. This means that even if I put the location of openexr to CMAKE_PREFIX_PATH, it's never added to the build config. Only way to build it is to put the OpenEXR include files in the same location as something else that is found.
This is on Windows with OCIO RB-2.0, OIIO release and OpenEXR 2.5.5
Expected behavior is that when building the OCIO-apps it should search for OpenEXR and add it.

Here's the error messages

```
C:\vfxplatform_build\dist\oiio\include\OpenImageIO/Imath.h(13): fatal error C1083: Cannot open include file: 'OpenEXR/OpenEXRConfig.h': No such file or directory [C:\vfxplatform_build\build\
OpenColorIO\src\apps\ociolutimage\ociolutimage.vcxproj]

C:\vfxplatform_build\dist\oiio\include\OpenImageIO/Imath.h(13): fatal error C1083: Cannot open include file: 'OpenEXR/OpenEXRConfig.h': No such file or directory [C:\vfxplatform_build\build\
OpenColorIO\src\apps\ociodisplay\ociodisplay.vcxproj]
```

**Comment by JenusL** [comment]
Yeah sure.
```
set current=%cd%

cd build\OpenColorIO

cmake -G "Visual Studio 16 2019" -A x64 -T v141 ^
      -D CMAKE_PREFIX_PATH="%current%\local;%current%\dist\openexr;%current%\dist\oiio;%current%\ext\dist\doxygen" ^
      -D GLEW_LIBRARIES="%current%\ext\dist\glew-cmake\lib\glew-shared.lib" ^
      -D CMAKE_INSTALL_PREFIX="%current%\dist\OpenColorIO" ^
      -D OCIO_BUILD_DOCS=ON ^
      ..\..\src\OpenColorIO

cmake --build . --target install --config Release -- /maxcpucount:16
```

I tried setting OpenEXR_ROOT as well but that didn't do anything. What I did was I ended up putting the openexr files in %current%\local because that folder was added to includes becuase of other packages found there.

**Comment by hodoulp** [comment]
As OpenEXR is not directly used in OCIO, I suspect that `OpenEXR_ROOT` cannot help. But I remember that the OpenImageIO public API requires an access to the OpenEXR public API in order to access the `half` type.

I checked my batch file, and I found that I directly added a OpenEXR include file access to the cmake command:
`-DCMAKE_CXX_FLAGS=-I%COMPILED_THIRD_PARTY_HOME%/OpenEXR-2.4.0/include`

**Comment by hodoulp** [comment]
That could be the solution. I removed that line from my batch file, and the build now fails with the same 'kind' errors.
```
F:\OpenSource\3rdParty\compiled-dist_rls\OpenImageIO-2.1\include\OpenImageIO/simd.h(31): fatal error C1083: Cannot open include file: 'OpenEXR/ImathVec.h': No such file or directory [F:\OpenSource\ocio_1\build_win_rls\src\libutils\oiiohelpers\oiiohe
lpers.vcxproj]
F:\OpenSource\3rdParty\compiled-dist_rls\OpenImageIO-2.1\include\OpenImageIO/simd.h(31): fatal error C1083: Cannot open include file: 'OpenEXR/ImathVec.h': No such file or directory [F:\OpenSource\ocio_1\build_win_rls\src\apps\ociolutimage\ociolutim
age.vcxproj]
F:\OpenSource\3rdParty\compiled-dist_rls\OpenImageIO-2.1\include\OpenImageIO/simd.h(31): fatal error C1083: Cannot open include file: 'OpenEXR/ImathVec.h': No such file or directory [F:\OpenSource\ocio_1\build_win_rls\src\apps\ociodisplay\ociodispla
y.vcxproj]
```

**Comment by lgritz** [comment]
OIIO's exported cmake configs include the right `find_dependency(OpenEXR)`, but only if OIIO was built against exr >= 2.5, because for <= 2.4, OpenEXR's cmake config exports were not reliable.

**Comment by doug-walker** [comment]
I don't think this is still relevant with the current versions of the libraries.  Please re-open if it is still a problem for you.
