### ISSUE TITLE
Add displayview inverse mode for command-line tools

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1360]
The command-line tools ocioconvert, ocioperf, and ociowrite provide an option to specify an input space and a display and view rather than a pair of color spaces.  When a pair of color spaces is specified, swapping the order is equivalent to inverting the transformation, but that trick doesn't work when using the display/view mode.  So a new command-line option should be added to allow this.  Under the hood, it simply sets the direction of the resulting transform to the inverse direction.  So most of the work is just handling the argument parsing.

For the command syntax, I propose adding a --inverse switch option.  (It should also be functional for the non-display-view arguments.)  (Also open to --invert, or "--dir inverse" if people prefer.)

In the case of ocioconvert, the forward syntax looks like:
ocioconvert [options] --view inputimage inputcolorspace outputimage displayname viewname
and the proposed inverse syntax should look like:
ocioconvert [options] --inverse --view inputimage displayname viewname outputimage outputcolorspace

For ocioperf and ociowrite, the forward syntax looks like:
ociowrite --displayview inputColorSpace display view --file outputfile
and the proposed inverse syntax is:
ociowrite --inverse --displayview display view outputColorSpace --file outputfile
but I would also be open to:
ociowrite --inverse --displayview inputColorSpace display view --file outputfile
if people feel that it is better to not change the order.

**Comment by KelSolaar** [comment]
Like it, great idea!

**Comment by hisergiorojas** [comment]
I would like to work on this issue.

**Comment by doug-walker** [comment]
Thanks, that would be appreciated @hisergiorojas.  We would like to include this in OCIO 2.1, which means that we need it merged by the end of the month.

**Comment by doug-walker** [comment]
This would be a great issue for someone new to the project to work on.  Pretty easy to do.

**Comment by doug-walker** [comment]
Closing as fixed via PR #1648.
