### ISSUE TITLE
`RB-2.0` include/OpenColorIO/OpenColorAppHelpers.h

### ISSUE THREAD

**Issue by elsandosgrande** [AcademySoftwareFoundation/OpenColorIO#1366]
While compiling Olive with a build of OpenColorIO that was built from the `RB-2.0` branch, I ran into an issue fixed by https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1324/commits/0eee77a61d14153053e643e5ec6cf32c84d03f29 in `master`: 
![image](https://user-images.githubusercontent.com/40576902/114281949-921f2b00-9a41-11eb-9a1b-f5228618d79b.png)

---

Yes, I could have tried to override `CMAKE_CXX_FLAGS` to remove `-Werror`, which is set by CMake by default, but I don't know exactly how many flags are a part of `CMAKE_CXX_FLAGS` by default (I only modify `CMAKE_CXX_FLAGS_[build type]` if I need/want to modify the compiler flags, since I know exactly how many flags are a part of it by default, which is evident in the compiler flags in the screenshot above).

**Comment by hodoulp** [comment]
Thanks @elsandosgrande to report the problem. The fix already exists in `master` and that's a candidate for integration in `RB-2.0`.

**Comment by elsandosgrande** [comment]
Is there any sort of timeframe for it, or is everything still being worked out?

**Comment by hodoulp** [comment]
There are steps to follow before communicating any dates such as TSC approval, TSC content approval, back-port & merge of all selected pull requests, etc.

In case the build break is blocking for you, the fix is only to remove the extra `;`

**Comment by elsandosgrande** [comment]
Yeah, I've already removed it; I was just wondering how long it might take for changes to be made to a release branch. It also helps to know when to undo the change so as to avoid the conflict in the Git repository, though that's not that big of an issue.

Thanks for the reply!

**Comment by hodoulp** [comment]
Fixed by PR #1378
