### ISSUE TITLE
Implement the ACES 1.3 gamut compression transform

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1402]
AMPAS has just released ACES 1.3 and the main feature of this release is a new gamut compression transform.  Here are some key links:
https://github.com/ampas/aces-dev/blob/dev/transforms/ctl/lmt/LMT.Academy.GamutCompress.ctl
https://github.com/ampas/aces-vwg-gamut-mapping-2020/blob/master/model/docs/gamut-compress-documentation.md
https://paper.dropbox.com/doc/1BByr3dSQvpjlYcOJlVgR
https://community.acescentral.com/t/gamut-compression-fka-mapping-documentation-deliverable/3539

It would be great to have someone make a PR to implement this in OCIO. 

Here are some suggestions for how to approach this.

1)  Implement a new style for the FixedFunctionOp.  Based on discussion at the Gamut Mapping Implementation VWG, it sounds like this should expose the parameters.  However, we should be clear that this is not technically the ACES transform since that has a fixed set of parameters.

2)  Implement a new style for the BuiltinTransform that hardcodes the official parameters for the ACES transform.  This one should have something like "ACES 1.3" in the name.

I will recommend that the matrix from AP0 to AP1 before the actual compression and the matrix from AP1 to AP0 afterwards are placed in the BuiltinTransform rather than in the FixedFunction so that the optimizer is able to drop these or combine them with other matrices for better performance.

**Comment by KelSolaar** [comment]
The actual CTL reference code is here: https://github.com/ampas/aces-dev/blob/dev/transforms/ctl/lmt/LMT.Academy.GamutCompress.ctl

**Comment by zachlewis** [comment]
I'd like to give this a shot. If I can do it, pretty much anyone can.

**Comment by remia** [comment]
Great @zachlewis! I was also interested on getting involved, so feel free to ask if you need a hand.

**Comment by nick-shaw** [comment]
Great to see people are keen to jump on this. I’m sure it won’t be necessary, but feel free to give me a should if anything is unclear. And do reference the CTL @KelSolaar linked, rather than Jed’s repo, as his version diverges slightly from the AMPAS one.

**Comment by KelSolaar** [comment]
> And do reference the CTL @KelSolaar linked, rather than Jed’s repo, as his version diverges slightly from the AMPAS one. 

At this point Jed's variant has significantly drifted both in term of implementation and look: the compression function is different based on a conic equation, i.e. parabola, and is I think much flatter, i.e. preserve less saturation.

**Comment by doug-walker** [comment]
Thank you Nick and Thomas for drawing the distinction between Jed's repo and the current ACES work.  I have updated the links above.

**Comment by zachlewis** [comment]
> Great @zachlewis! I was also interested on getting involved, so feel free to ask if you need a hand.

Absolutely -- @remia, feel free to take a stab at it if you haven't already. I still need to get my CLA stuff in order, and I've got tons on my plate as it is -- I definitely don't want to hold things up.

To the point, though, I'm really pleased to see how painless the process of getting a simple parametric algorithm into OCIO / CTF is.

**Comment by michdolan** [comment]
#1404 is now merged. Thanks @remia !
