### ISSUE TITLE
Exception when using a no-op look with LegacyViewPipeline

### ISSUE THREAD

**Issue by karlhendrikse** [AcademySoftwareFoundation/OpenColorIO#1423]
If a `LegacyViewPipeline` is set up to use a look and the look works out to be a no-op, `LookTransform::GetLooksResultColorSpace` returns `""` but `LegacyViewingPipelineImpl::getProcessor` still tries to create a look transform and append it to the group:

    if (!looks.empty())
    {
        const char * inCS = dtInputColorSpace->getName();
        const char * outCS = skipColorSpaceConversions ? inCS :
                             LookTransform::GetLooksResultColorSpace(configIn, context,
                                                                     looks.c_str());
        auto lt = LookTransform::Create();
        lt->setSrc(inCS);
        lt->setDst(outCS);
        lt->setLooks(looks.c_str());
        lt->setSkipColorSpaceConversion(skipColorSpaceConversions);

        group->appendTransform(lt);

        // Adjust display transform input color space.
        dt->setSrc(outCS);
    }

This causes `LookTransform::validate` to throw an exception `"LookTransform: empty destination color space name."` later.

I think it can be fixed by adding a check (at least, it works for me):

    if (!looks.empty())
    {
        const char * inCS = dtInputColorSpace->getName();
        const char * outCS = skipColorSpaceConversions ? inCS :
                             LookTransform::GetLooksResultColorSpace(configIn, context,
                                                                     looks.c_str());
        if (outCS && *outCS)
        {
            auto lt = LookTransform::Create();
            lt->setSrc(inCS);
            lt->setDst(outCS);
            lt->setLooks(looks.c_str());
            lt->setSkipColorSpaceConversion(skipColorSpaceConversions);

            group->appendTransform(lt);

            // Adjust display transform input color space.
            dt->setSrc(outCS);
        }
    }

This is reproducible with a look like this:

      - !<Look>
        name: a
        process_space: "b"
        transform: !<GroupTransform>
            children:
                - !<CDLTransform> {slope: [1, 1, 1], offset: [0, 0, 0], power: [1.0,1.0,1.0]}

**Comment by remia** [comment]
Thanks @karlhendrikse for the thorough report, I can look into it if nobody have currently started it.

**Comment by doug-walker** [comment]
That would be great @remia !  No one is working on this AFAIK.

**Comment by hodoulp** [comment]
Merged in `master`, and soon in `v2.0.x`
