### ISSUE TITLE
Python bindings missing transform copy

### ISSUE THREAD

**Issue by remia** [AcademySoftwareFoundation/OpenColorIO#1434]
Is there an easy way to copy Transforms from the Python binding like in v1 with `CreateEditableCopy()` ? Seems like this is missing in v2.

I tried the `copy.deepcopy()` by the way but it dont’t work because the object not are pickle-able, we would need to add `py::pickle pybind11` definitions which is probably too convoluted for what we want.

**Comment by michdolan** [comment]
Originally we had implemented it, but since Python doesn't support `const` it didn't work the same way. In Python all of the transforms are always editable. I agree it would be good to support a proper Python implementation of OCIO object copying though.

**Comment by remia** [comment]
Yeah that make sense, and copying might still be needed in some cases indeed.

Will have a look at it.

**Comment by remia** [comment]
Closing as this was merged in `main`.
