### ISSUE TITLE
2.0.1 fails to find yaml-cpp

### ISSUE THREAD

**Issue by yurivict** [AcademySoftwareFoundation/OpenColorIO#1451]
I have ```yaml-cpp-0.7.0``` installed but ```OpenColorIO-2.0.1``` fails to find it:
```
-- Could NOT find yaml-cpp (missing: yaml-cpp_LIBRARY) (found suitable version "0.7.0", minimum required is "0.6.3")
-- Installing yaml-cpp: /disk-samsung/freebsd-ports/graphics/opencolorio/work/.build/ext/dist/lib/libyaml-cpp.a (version "0.6.3")
```

```yaml-cpp-0.7.0``` installs both cmake and pkgconfig files:
```
$ pkg info -l yaml-cpp
yaml-cpp-0.7.0:
[...]
	/usr/local/lib/cmake/yaml-cpp/yaml-cpp-config-version.cmake
	/usr/local/lib/cmake/yaml-cpp/yaml-cpp-config.cmake
	/usr/local/lib/cmake/yaml-cpp/yaml-cpp-targets-release.cmake
	/usr/local/lib/cmake/yaml-cpp/yaml-cpp-targets.cmake
[...]
	/usr/local/libdata/pkgconfig/yaml-cpp.pc
[...]
```

You still use custom script ```share/cmake/modules/Findyaml-cpp.cmake``` that fails.

OS: FreeBSD 13

**Comment by yurivict** [comment]
Docker doesn't support FreeBSD.

Please install this [ISO image](https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/13.0/FreeBSD-13.0-RELEASE-amd64-disc1.iso) into a VirtualBox VM.

**Comment by doug-walker** [comment]
There's been a fair amount of improvements to the Yaml configuration since this was opened.  Please re-open if the issue still exists.
