### ISSUE TITLE
Building Docs Generates Long Paths on Windows

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO#1461]
Hi,

As I was trying to get a _completionist_ build on Windows, I was unsuccessful because of files generated being longer than the 260 characters limit:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write
lines to file "x64\Release\copy_docs_api_python_frozen_pyopencolorio_allocationfromstring_rst\copy_doc.A7455CAE.tlog\copy_docs_api_python_frozen_pyopencol
orio_allocationfromstring_rst.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 ch
aracters, and the directory name must be less than 248 characters. [E:\D\D\T\opencolorio\build\platform-windows\arch-AMD64\msvc-19.1\python-3.7\opencolori
o\docs\copy_docs_api_python_frozen_pyopencolorio_allocationfromstring_rst.vcxproj]

My prefix is admittedly long but the docs directories and filename are ridiculously long too, the following one is already over 170 characters:

`copy_docs_api_python_frozen_pyopencolorio_allocationfromstring_rst\copy_doc.A7455CAE.tlog\copy_docs_api_python_frozen_pyopencolorio_allocationfromstring_rst.lastbuildstate`

**Comment by hodoulp** [comment]
I faced a file path length issue when compiling OCIO for Maya on Windows, and I used `CMAKE_OBJECT_PATH_MAX` to set the size to 400. The default is 255 on Windows. But OCIO changes the length to 300 on all platforms if not defined. You can try 400 or more to see if it works in your case.
