### ISSUE TITLE
TSC, Committer Nomination: Rémi Achard, DNEG

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1473]
Per the guidelines of the OCIO `GOVERNANCE.md`, this issue is to nominate adding Rémi Achard as a voting member of the OCIO TSC, an official representative on the TSC for DNEG, and as an OCIO repository committer.

Rémi has been contributing to OCIO since 2018 and actively participating in TSC meetings for the last year, with recent contributions including automated Python wheel generation as a part of the OCIO CD pipeline, and implementation of the ACES 1.3 gamut compression transform. Rémi is a Software Engineer at DNEG with more than 10 years experience in the image processing and computer graphics fields, and regularly participates in OCIO pull request reviews and issue discussions, offering valuable feedback and guidance to library and tool changes. I think Rémi is an excellent candidate for helping to guide the OpenColorIO project forward.

Thanks for your consideration.

**Comment by carolalynn22** [comment]
Absolutely! 👍 👍 👍

**Comment by doug-walker** [comment]
As Michael wrote, Remi has been making numerous well-engineered contributions to OCIO, has great industry knowledge, and I agree he would make a great TSC member!

**Comment by hodoulp** [comment]
Yes! 👍 👍 👍

**Comment by remia** [comment]
Thanks everyone, would be happy to continue contributing to the project as part of the tsc!

**Comment by mjtitchener-fn** [comment]
Bit late but agreed! 👍🏻 Rémi would be a great addition!
