### ISSUE TITLE
Update eXpat to 2.4.1

### ISSUE THREAD

**Issue by hodoulp** [AcademySoftwareFoundation/OpenColorIO#1491]
The current eXpat version is 2.2.8 (Sep 13, 2019), it would be time to investigate upgrading the library to the latest release i.e. 2.4.1 (May 23, 2021).

Maya source code analysis detected some issues with the 2.2.8 versions which should be fixed with version 2.2.10.

**Comment by amyspark** [comment]
[Alpine Linux](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/opencolorio) already ships 2.1 with expat 2.4.1.

**Comment by hodoulp** [comment]
Merged in `main`
