### ISSUE TITLE
OCIO is not compatible with OIIO 2.3

### ISSUE THREAD

**Issue by hobbes1069** [AcademySoftwareFoundation/OpenColorIO#1509]
Seeing as the packages are tightly coupled, there probably should have been better communication about API changes, nonetheless there seems to be an API incompatibility:
```
[ 86%] Linking CXX executable ociolutimage
cd /builddir/build/BUILD/OpenColorIO-2.1.0/redhat-linux-build/src/apps/ociolutimage && /usr/bin/cmake -E cmake_link_script CMakeFiles/ociolutimage.dir/link.txt --verbose=1
/usr/bin/g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 CMakeFiles/ociolutimage.dir/main.cpp.o -o ociolutimage  -Wl,-rpath,/builddir/build/BUILD/OpenColorIO-2.1.0/redhat-linux-build/src/OpenColorIO: ../../apputils/libapputils.a ../../OpenColorIO/libOpenColorIO.so.2.1.0 /usr/lib64/libOpenImageIO.so 
/usr/bin/ld: /usr/lib64/libOpenImageIO.so: undefined reference to symbol '_ZN16OpenImageIO_v2_310ParamValue11clear_valueEv'
/usr/bin/ld: /usr/lib64/libOpenImageIO_Util.so.2.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/apps/ociolutimage/CMakeFiles/ociolutimage.dir/build.make:103: src/apps/ociolutimage/ociolutimage] Error 1
```

**Comment by zachlewis** [comment]
Hi there. Would you mind giving the main OCIO branch a shot? There were some discrepancies in how both libraries were handling the move to the standalone imath library which were reconciled shortly after the 2.1 release, that I think might resolve the linking trouble you're having.

FWIW, I wasn't able to build OCIO against OIIO-2.3 either prior to #1488, but now everything works fine.

**Comment by hobbes1069** [comment]
With the PR applied as a patch the builds are completing. Thanks!

https://koji.fedoraproject.org/koji/taskinfo?taskID=76693314

**Comment by lgritz** [comment]
Yes, can that fix please be backported to a 2.1 patch release?

**Comment by hodoulp** [comment]
That's the plan to have a 2.1.1 soon. But we are currently waiting for a major OSL translation improvement before doing it (currently under review internally at Autodesk). Please bring the topic to the TSC meeting if you feel we need to create a 2.1.1 asap.

**Comment by hodoulp** [comment]
The patch release 2.1.1 is now done.
