### ISSUE TITLE
CMake handling of the C++ standard suggestions

### ISSUE THREAD

**Issue by Sarcasm** [AcademySoftwareFoundation/OpenColorIO#1525]
@hodoulp : regarding this discussion https://github.com/AcademySoftwareFoundation/aswf-sample-project/pull/8#issuecomment-952962520, I prefer to answer your question here:

> To smooth integrations, do you think that we can improve the C++ version support in OpenColorIO?
> -- @hodoulp

I think `CMAKE_CXX_STANDARD` (and things many things starting with `CMAKE_` like `CMAKE_CXX_STANDARD_REQUIRED` and `CMAKE_CXX_EXTENSIONS`) should not be set, or even checked in the CMake files, as it is done here:

https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/2d4701e5abc4c95594faae384c6d54fd8b6e3a6b/share/cmake/utils/CppVersion.cmake#L8-L19

I think the quoted code has these 2 issues:

1. The project will not compile with a C++20-capable compiler, it's looks like an unnecessary limitation, a minimum standard seems more future-proof than a hardcoded list of standards.

   ```cmake
   $ cmake -DCMAKE_CXX_STANDARD=20 ..
   CMake Error at CMakeLists.txt:21 (message):
     CMAKE_CXX_STANDARD=20 is unsupported.  Supported standards are: 11, 14, 17.
   ```

2. CMake is smart enough to detect the C++ standard the compiler support by defaults or that was set in the `CXXFLAGS/CMAKE_CXX_FLAGS`, as explained in the top-level message of my PR https://github.com/AcademySoftwareFoundation/aswf-sample-project/pull/8 and in my CMake notes here https://sarcasm.github.io/notes/dev/cmake.html#c-standard.

   However, we can see the code will not respect the compiler standard and will instead overwrite with C++11.

   ```cmake
   $ cmake -G Ninja -DCMAKE_CXX_FLAGS=-std=c++20 ..
   -- The CXX compiler identification is GNU 11.1.0
   -- Detecting CXX compiler ABI info
   -- Detecting CXX compiler ABI info - done
   -- Check for working CXX compiler: /usr/bin/c++ - skipped
   -- Detecting CXX compile features
   -- Detecting CXX compile features - done
   -- Setting C++ version to '11' as none was specified.
   ...
   $ ninja -v
   [1/2] /usr/bin/c++   -std=c++20 -std=gnu++11 -MD -MT ...
   ```

So I think the `target_compile_features(OpenColorIO PUBLIC cxx_std_11)` is the correct an sufficient code mostly.
I wouldn't set the `CMAKE_CXX_STANDARD` bits in the CMake files at all, just in CI.

Regarding the issues with dependencies requiring C++14, if they use the same method, e.g. `target_compile_features(oslcomp PUBLIC cxx_std_14)`, the CMake transitive "contamination" should work ok.

**Comment by remia** [comment]
Thanks for raising these points @Sarcasm, here is what I got from the discussion so far:
* We should remove the strict `set(CMAKE_CXX_STANDARD 11)` when no `CMAKE_CXX_STANDARD` is specified as the `target_compile_features` will already make sure we have at least a C++11 ready compiler,
* Replace the CMake `FATAL_ERROR` by a warning when the standard is not in the supported list to allow package maintainers or others advanced users to use newer language versions if desired,
* We could add the latest standard (at least C++20) to the nightly build to make sure we discover new wanring / errors early, this would probably be beneficial for the code quality as well, I can confirm what @hodoulp said OCIO doesn't compile on mac OS 11.6 Clang 13 neither.

On the usage of the 3 `CMAKE_CXX_` variants I think it's a good pragmatic approach given that we have lot of targets and also external dependencies built through `ExternalProject_Add`.
