### ISSUE TITLE
[Python] Syntax issue in NamedTransform setEncoding() parameter

### ISSUE THREAD

**Issue by MrLixm** [AcademySoftwareFoundation/OpenColorIO#1540]
Hello, 

When using the Python API, 
the [NameTransform](https://opencolorio.readthedocs.io/en/latest/api/namedtransform.html).setEncoding() method have its parameter with a typo. The parameter name is stated as being `encodig` while it should be `encoding`

Cheers.
Liam.

**Comment by remia** [comment]
Thanks for reporting @MrLixm, I included the fix the linked PR.

**Comment by remia** [comment]
Closing as this was merged in `main`.
