### ISSUE TITLE
Python: Segfault adjusting format metadata

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1577]
The following seems to reliably segfault:

```
import PyOpenColorIO as ocio

gt = ocio.GroupTransform()

fmd = gt.getFormatMetadata()

fmd.addChildElement(ocio.METADATA_INFO, '')  # no problem adding elements

fmd.addChildElement(ocio.METADATA_INFO, '')  # no problem adding multiple elements with same name

_ = fmd.getChildElements()[0]

fmd.addChildElement(ocio.METADATA_INFO, '')  # segfaults after above line
```

 :thinking:

**Comment by remia** [comment]
Hi @zachlewis,

I tried on macOS 12.0.1 with the pip wheel for 2.1.1 and on main without managing to reproduce the segfault, can you give more details on your environment?

**Comment by zachlewis** [comment]
Heya @remia -- thanks for looking in to this. 

You're right, it seems to be something in my dev environment, which had a lot of stuff going on. I've verified that I _cannot_ reproduce the segfault under normal circumstances. I'm really only seeing the segfault when I run the above in a venv interpreter via PyCharm's interactive Python Console. 

That being said, this seems like more of a Zach problem than an OpenColorIO problem, so I'm gonna close this issue. Although I would be curious to know if anyone else is experiencing segfaults in PyCharm. 

Thanks again, Remi.
