### ISSUE TITLE
File resolution issue when path root is a symlink

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1595]
Here's a weird one.

I have a symlink `/jobs` which resolves to `/Volumes/work/jobs`. 

If my config's Search Paths reference paths that start with `/jobs/...`, OCIO isn't able to find anything; but if I use `/Volumes/work/jobs/...`, everything works fine.

This is on macos-11.3.

**Comment by zachlewis** [comment]
This is definitely a macOS-10.15+ issue. 

Turns out, those aren't normal symlinks at the root -- they're firmlinks. Long story short, one can edit `/etc/synthetic.conf` to symlink stuff under `/`.  There's good info [here](https://derflounder.wordpress.com/2020/01/18/creating-root-level-directories-and-symbolic-links-on-macos-catalina/).

Our issue is resolved with the above workaround (pointing to the resolved, fully-qualified path).

I have a note that this behavior *may* be a regression from OCIO-1, but I can't verify for myself at the moment.
(It fixes a config that worked with Nuke-11 but broke with Nuke-13.1; but I can't determine if this is an effect of also having upgraded from macOS-10.14 -- i.e., it's possible the config was never tested with Nuke-11 / macOS-10.15+. 

Anyway. Noted for posterity.

**Comment by doug-walker** [comment]
Closing this as it is not clear that any action is needed in OCIO.
