### ISSUE TITLE
Build failure with vcpkg when enabling tools compilation

### ISSUE THREAD

**Issue by demoulinv** [AcademySoftwareFoundation/OpenColorIO#1602]
As an information, the issue [[opencolorio:x64-windows] build failure #23154](https://github.com/microsoft/vcpkg/issues/23154) regarding OpenColorIO has been submited on Microsoft vcpkg repo.

**Comment by remia** [comment]
Thanks for the report @demoulinv. I didn't understood from the build log extract, is that a static build ? Could that be related to what was mentioned near the end of #1581 ?

**Comment by LilyWangLL** [comment]
[install-x64-windows-dbg-out.log](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/8094857/install-x64-windows-dbg-out.log)
This is full log. And this should be not related with #1581
