### ISSUE TITLE
OFX plug-ins will not load in Nuke on macOS without manually editing the rpath

### ISSUE THREAD

**Issue by mjtitchener-fn** [AcademySoftwareFoundation/OpenColorIO#1607]
I’m building OCIO 2.1.1 with the example OFX plug-ins on macOS 12.2.1.

After following the instructions [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/docs/quick_start/installation.rst#environment-variables) i.e.
```
.. envvar:: OFX_PLUGIN_PATH
 
When building the OCIO OpenFX plugins, include the installed
``OpenColorIO/lib`` directory (where ``OpenColorIO.ofx.bundle`` is located)
in this path. The path to a shared OpenColorIO lib (*.so, *.dll, *.dylib)
should also be present on ``PATH``.
```
The example plug-ins do not load in Nuke 13.1v2.

To get them to load I had to manually add an rpath to the OFX plug-in e.g.
``` 
install_name_tool -add_rpath /path/to/lib/libOpenColorIO.2.1.dylib /path/to/lib/OpenColorIO.ofx.bundle/Contents/MacOS-x86-64/OpenColorIO.ofx
```

I had a chat with @michdolan and he pointed out @remia also mentioned this in relation to DaVinci Resolve [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1371#issuecomment-821853156) (I haven't yet tested in Resolve).

@michdolan suggested I log an issue for further investigation to see if this can be fixed during the build.

**Comment by remia** [comment]
Hi @mjtitchener-fn,

By default we use relative RPATH so that the built package can be relocated (moved) easily. For OFX plugin it's a slightly different use case because the plugin itself is typically moved to a different location than the library installation path. I guess we could either make the RPATH absolute for OFX plugins or actually ship the OpenColorIO library within the OFX bundle.

For my OFX tests I only build OpenColorIO in static mode to avoid these kind of issues, is there a reason you don't want to do that?

**Comment by mjtitchener-fn** [comment]
Hi Remi,

I don’t have a specific reason to not build static in this case. It’s just that I was following the instructions and the default is to build shared.
Building static does solves the problem for me and it makes sense in hindsight. 

As a non-developer I’m not sure what the expectation is here, would most people know to do this upfront? 

Perhaps this is something we should document? 

Thanks,
Mark

**Comment by remia** [comment]
What about editing the documentation to this?

```
.. envvar:: OFX_PLUGIN_PATH

    When building the OCIO OpenFX plugins, include the installed 
    ``OpenColorIO/lib`` directory (where ``OpenColorIO.ofx.bundle`` is located) 
    in this path.

    It is recommended to build OFX plugins in static mode 
    (``BUILD_SHARED_LIBS=OFF``) to avoid any issue loading the OpenColorIO
    library from the plugin once it has been moved. Otherwise, please make sure
    the shared OpenColorIO lib (*.so, *.dll, *.dylib) is visible from the
    plugin by mean of ``PATH``, ``LD_LIBRARY_PATH`` or ``DYLD_LIBRARY_PATH``
    for Windows, Linux and macOS respectively. For systems that supports it,
    it is also possible to edit the RPATH of the plugin to add the location of
    the shared OpenColorIO lib.
```

**Comment by mjtitchener-fn** [comment]
Looks good Remi. Thanks for doing this.

Sorry I didn't get back to you sooner!
