### ISSUE TITLE
How is the 3D LUT's 1D data constructed into 3D textures?

### ISSUE THREAD

**Issue by tdbe** [AcademySoftwareFoundation/OpenColorIO#1622]
I have extracted a 3D lut from an ocio profile and I'm trying to make it into a 3D texture and sample it in my glsl shader. 

The LUT is a 65x65x65 file but it's a 1D column of data like this:

> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00000421566983277443796396255493
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00017824899987317621707916259766
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00064588000532239675521850585938
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00150797003880143165588378906250
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00289885001257061958312988281250
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00473794993013143539428710937500
> 0.00000000000000000000000000000000
> 0.00000000000000000000000000000000
> 0.00706929014995694160461425781250
> 

Does it start with all the x values, then all the y values then all the z values? or how should it be set up?

The sampler looks like this it's from the dumped gpu shader from ocio --gpuinfo; so it should be correct; but it outputs very wonky results which means I'm not building the 3D texture correctly:

    // Add LUT 3D processing for ocio_lut3d_1
    
    {
        vec3 coords = outColor.rgb * vec3(64., 64., 64.); 
        vec3 baseInd = floor(coords);
        vec3 frac = coords - baseInd;
        vec3 f1, f4;
        baseInd = ( baseInd.zyx + vec3(0.5, 0.5, 0.5) ) / vec3(65., 65., 65.);
        vec3 v1 = texture(ocio_lut3d_1Sampler, baseInd).rgb;
        vec3 nextInd = baseInd + vec3(0.0153846154, 0.0153846154, 0.0153846154);
        vec3 v4 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
        if (frac.r >= frac.g)
        {
        if (frac.g >= frac.b)
        {
            nextInd = baseInd + vec3(0., 0., 0.0153846154);
            vec3 v2 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            nextInd = baseInd + vec3(0., 0.0153846154, 0.0153846154);
            vec3 v3 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            f1 = vec3(1. - frac.r, 1. - frac.r, 1. - frac.r);
            f4 = vec3(frac.b, frac.b, frac.b);
            vec3 f2 = vec3(frac.r - frac.g, frac.r - frac.g, frac.r - frac.g);
            vec3 f3 = vec3(frac.g - frac.b, frac.g - frac.b, frac.g - frac.b);
            outColor.rgb = (f2 * v2) + (f3 * v3);
        }
        else if (frac.r >= frac.b)
        {
            nextInd = baseInd + vec3(0., 0., 0.0153846154);
            vec3 v2 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            nextInd = baseInd + vec3(0.0153846154, 0., 0.0153846154);
            vec3 v3 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            f1 = vec3(1. - frac.r, 1. - frac.r, 1. - frac.r);
            f4 = vec3(frac.g, frac.g, frac.g);
            vec3 f2 = vec3(frac.r - frac.b, frac.r - frac.b, frac.r - frac.b);
            vec3 f3 = vec3(frac.b - frac.g, frac.b - frac.g, frac.b - frac.g);
            outColor.rgb = (f2 * v2) + (f3 * v3);
        }
        else
        {
            nextInd = baseInd + vec3(0.0153846154, 0., 0.);
            vec3 v2 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            nextInd = baseInd + vec3(0.0153846154, 0., 0.0153846154);
            vec3 v3 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            f1 = vec3(1. - frac.b, 1. - frac.b, 1. - frac.b);
            f4 = vec3(frac.g, frac.g, frac.g);
            vec3 f2 = vec3(frac.b - frac.r, frac.b - frac.r, frac.b - frac.r);
            vec3 f3 = vec3(frac.r - frac.g, frac.r - frac.g, frac.r - frac.g);
            outColor.rgb = (f2 * v2) + (f3 * v3);
        }
        }
        else
        {
        if (frac.g <= frac.b)
        {
            nextInd = baseInd + vec3(0.0153846154, 0., 0.);
            vec3 v2 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            nextInd = baseInd + vec3(0.0153846154, 0.0153846154, 0.);
            vec3 v3 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            f1 = vec3(1. - frac.b, 1. - frac.b, 1. - frac.b);
            f4 = vec3(frac.r, frac.r, frac.r);
            vec3 f2 = vec3(frac.b - frac.g, frac.b - frac.g, frac.b - frac.g);
            vec3 f3 = vec3(frac.g - frac.r, frac.g - frac.r, frac.g - frac.r);
            outColor.rgb = (f2 * v2) + (f3 * v3);
        }
        else if (frac.r >= frac.b)
        {
            nextInd = baseInd + vec3(0., 0.0153846154, 0.);
            vec3 v2 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            nextInd = baseInd + vec3(0., 0.0153846154, 0.0153846154);
            vec3 v3 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            f1 = vec3(1. - frac.g, 1. - frac.g, 1. - frac.g);
            f4 = vec3(frac.b, frac.b, frac.b);
            vec3 f2 = vec3(frac.g - frac.r, frac.g - frac.r, frac.g - frac.r);
            vec3 f3 = vec3(frac.r - frac.b, frac.r - frac.b, frac.r - frac.b);
            outColor.rgb = (f2 * v2) + (f3 * v3);
        }
        else
        {
            nextInd = baseInd + vec3(0., 0.0153846154, 0.);
            vec3 v2 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            nextInd = baseInd + vec3(0.0153846154, 0.0153846154, 0.);
            vec3 v3 = sampleTex3D(ocio_lut3d_1Sampler, nextInd);
            f1 = vec3(1. - frac.g, 1. - frac.g, 1. - frac.g);
            f4 = vec3(frac.r, frac.r, frac.r);
            vec3 f2 = vec3(frac.g - frac.b, frac.g - frac.b, frac.g - frac.b);
            vec3 f3 = vec3(frac.b - frac.r, frac.b - frac.r, frac.b - frac.r);
            outColor.rgb = (f2 * v2) + (f3 * v3);
        }
        }
        outColor.rgb = outColor.rgb + (f1 * v1) + (f4 * v4);
    }

Thanks

**Comment by Dithermaster** [comment]
The "1D" list are the RGB values as you walk the 3D grid. It looks like B is moving fastest in your example.
So for example, a 2x2x2 3D LUT would be listed in "1D" as these 3D indexes:
[0][0][0]
[0][0][1]
[0][1][0]
[0][1][1]
[1][0][0]
[1][0][1]
[1][1][0]
[1][1][1]

It looks like you're implementing the Tetrahedral interpolation mode. I'd start with Trilinear mode first for simplicity, then move to Tetrahedral after.

**Comment by tdbe** [comment]
> The "1D" list are the RGB values as you walk the 3D grid. It looks like B is moving fastest in your example. So for example, a 2x2x2 3D LUT would be listed in "1D" as these 3D indexes: [0][0][0] [0][0][1] [0][1][0] [0][1][1] [1][0][0] [1][0][1] [1][1][0] [1][1][1]
> 
> It looks like you're implementing the Tetrahedral interpolation mode. I'd start with Trilinear mode first for simplicity, then move to Tetrahedral after.

Ah dang.. Thanks a lot for that :) So you're saying in this case, the first 3 values in the file / the 1d list, would be r g and b for point [0][0][0], the next 3 values for point [0][0][1] etc. Cool.
I'll try trilinear. Or I'll build a 3d texture properly from that data with this knowledge.

PS: I've attached the first 195 values of the 3d lut here
[3dlut_65_65_65_first_195values.txt](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/8319620/3dlut_65_65_65_first_195values.txt)

**Comment by doug-walker** [comment]
Closing.  This was a question rather than an issue with OCIO.
