### ISSUE TITLE
errno checks break musl compatibility

### ISSUE THREAD

**Issue by tibequadorian** [AcademySoftwareFoundation/OpenColorIO#1624]
In the 'from_chars' function, it's first checked if errno != 0 and immediately returns with std::errc::result_out_of_range aka ERANGE.
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/4fa94918c2cf572dcaf61ca07016f3b5c231c14c/src/utils/NumberUtils.h#L71-L74

According to `strtod(3p)`, if no conversion could be performed, errno may be set to EINVAL.
Unlike glibc which doesn't do this, musl does. This leads to an incorrect return value (ERANGE != EINVAL).

I discovered this through failing tests on musl.

**Comment by thesamesam** [comment]
@tibequadorian seems to have written a patch for this at: https://inbox.vuxu.org/voidlinux-github/20220415165812.WIf9xdfnApCy_0So7fM1SoqKt8otlLfcokk5uD2d_E0@z/.

**Comment by tibequadorian** [comment]
Yes here is the original: https://github.com/tibequadorian/void-packages/blob/openimageio/srcpkgs/opencolorio/patches/musl.patch
It's a minimal patch so I don't know if it's the best solution but it works.
