### ISSUE TITLE
[python][feature-request] `GradingRGBM` : fail to assertEqual 2 similar instances

### ISSUE THREAD

**Issue by MrLixm** [AcademySoftwareFoundation/OpenColorIO#1641]
Hello,

When using `ocio.GradingRGBM()`, creating two instances with similar values will result in two instances that can not be matched equally like `instance1==instance2`.

This can bee seen in the following snippet where both tests will fail :

```python
import unittest

import PyOpenColorIO as ocio


class OcioGradingRGBM(unittest.TestCase):
    def test_equal1(self):

        grgbm1 = ocio.GradingRGBM()
        grgbm1.master = 0.5

        grgbm2 = ocio.GradingRGBM()
        grgbm2.master = 0.5

        self.assertEqual(grgbm1, grgbm2)

    def test_equal2(self):

        grgbm1 = ocio.GradingRGBM(0.1, 0, 0, 0.5)
        grgbm2 = ocio.GradingRGBM(0.1, 0, 0, 0.5)

        self.assertEqual(grgbm1, grgbm2)


if __name__ == "__main__":
    unittest.main()
```

CONTEXT: Windows10, OCIO 2.1.0

Cheers.
Liam.

**Comment by remia** [comment]
That's a good point @MrLixm, I think the bindings are currently lacking in terms of equality check for types. The only one I see explicitly defining this is `ColorSpaceSet` at this time. It would be nice to add support for other types where this would make sense.

Probably a good candidate for next release.
