### ISSUE TITLE
Spi3d format is not working in ociobakelut

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1660]
As reported on ocio-user, ociobakelut is not working for the format "spi3d".  It gives an error message: "OCIO Error: File format spi3d does not support baking."  This is a bug because FileFormatSpi3D.cpp indicates it claims to support baking, and the code is present for it to do so.

I tested .clf, .3dl, .csp, and Iridas cube in ociobakelut, all of which worked.  So it seems the problem is not an overall ociobakelut problem.

**Comment by remia** [comment]
The support for baking .spi3d LUTs has not been released yet and was added only recently as part of the work on ociobakelut support for viewing transform. I tested on main and it seems to work, on which version did you test? Also worth noting is that calling ociobakelut without args also print the supported formats.

**Comment by doug-walker** [comment]
You are totally right Remi!   My apologies, I was mistakenly running the released version of ociobakelut rather than the one in the main branch.   The spi3d format does indeed work in main, closing this issue.
