### ISSUE TITLE
Release 2.1.1 and 2.1.2 from Github does not build

### ISSUE THREAD

**Issue by kermitdafrog8** [AcademySoftwareFoundation/OpenColorIO#1665]
Missing #include <string> in src/OpenColorIO/FileRules.cpp

https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/06601f0e435bed79c792c2627ad19145b287ca38/src/OpenColorIO/FileRules.cpp#L6

It is included in the master branch but for some reason not in the release packages.

**Comment by remia** [comment]
Hi @kermitdafrog8,

Can you give more details on your build environment?

**Comment by kermitdafrog8** [comment]
Slackware 15.0+ GCC 12.1.0 CMake 3.23.2.  What other information do you need?  I see the include is in the main branch but it doesn't look like it's there in the release packages here on Github.

**Comment by tanuki-no** [comment]
Hi there! I successfully build 2.1.2 with OpenEXR-3.1.5 using on Gentoo from source. My patch attached to the post.
[opencolorio-cumulative-OpenExr3.zip] (https://github.com/AcademySoftwareFoundation/OpenColorIO/files/9739259/opencolorio-cumulative-OpenExr3.zip)

Hope it could help.
