### ISSUE TITLE
Custom LUT

### ISSUE THREAD

**Issue by dalinagraphics** [AcademySoftwareFoundation/OpenColorIO#1670]
Hello, dear colleagues. Thanks for OCIO! It is great. In this webinar, I saw a «shotlut» on the display. Please tell me how I can do the same in my studio? We use ACES 1.2.
 
[https://youtu.be/d_LZsd_F_0g?t=726](url)

![Capture](https://user-images.githubusercontent.com/109650663/179914688-512234f1-b3b3-4a24-a414-6bac09a257fd.PNG)

**Comment by MrLixm** [comment]
Hello, i'm not very familiar with this workflow but you best get started by having a look at the documentation :

> https://opencolorio.readthedocs.io/en/latest/guides/authoring/authoring.html#contexts-example

**Comment by dalinagraphics** [comment]
> Hello @dalinagraphics i'm not very familiar with this workflow but you best get started by having a look at the documentation :
> 
> > https://opencolorio.readthedocs.io/en/latest/guides/authoring/authoring.html#contexts-example

Thanks, I did it!

**Comment by MrLixm** [comment]
Glad to hear ! You can close this issue if you consider it resolved.
