### ISSUE TITLE
FileTransform: load from memory

### ISSUE THREAD

**Issue by MrKepzie** [AcademySoftwareFoundation/OpenColorIO#1675]
FileTransform currently loads the LUT from a file no matter what. 
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/src/OpenColorIO/transforms/FileTransform.cpp#L549

This may be useful for applications to wrap LUTs in memory files along with other data.
However, this requires  currently a copy of the memory blog to a temporary file so that OCIO can read it. Making a "proxy" API such as what OpenImageIO does would enable such use case.

**Comment by SonyDennisAdams** [comment]
I believe Doug and team are currently working on adding this feature to OCIO v2. I shared our private v1 implementation with him as a reference. In our implementation the host can provide a callback so it can provide an istream for assets being read.

**Comment by doug-walker** [comment]
The ability to source FileTransforms from somewhere other than the file system has been implemented in PR #1696.  Please see the ConfigIOProxy class.  Any feedback is welcome.

**Comment by MrKepzie** [comment]
Thanks for pinging, we'll take a look the next month when possible. For what I've read in the PR description this looks like it fills all the need we have

**Comment by doug-walker** [comment]
Closing this as fixed via PR #1696.
