### ISSUE TITLE
`ociodisplay` inconsistency between tetrahedral interpolation and linear sampling

### ISSUE THREAD

**Issue by num3ric** [AcademySoftwareFoundation/OpenColorIO#1676]
With tetrahedral interpolation, the gpu processor generates manual interpolation code in [Lut3DOpGPU.cpp](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/src/OpenColorIO/ops/lut3d/Lut3DOpGPU.cpp#L63-L69) and specifies the use of `GL_NEAREST`.

However, the [SetTextureParameters](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/src/libutils/oglapphelpers/glsl.cpp#L62-L71) function used by `ociodisplay` still sets the texture to `GL_LINEAR` in this case. Shouldn't this if-statement also set the texture to `GL_NEAREST` if the incoming interpolation is tetrahedral as well?

**Comment by remia** [comment]
Thanks for raising that @num3ric, I think this does indeed look suspicious. It should probably be the Lut3DOpGPU.cpp code that need fixing to set the LUT interpolation scheme to NEAREST when TETRAHEDRAL is used on the GPU? It sounds like a serious issue?

**Comment by SonyDennisAdams** [comment]
Still, even if sampling on a grid point, an implementation might do extra work (reads and blending math) in `GL_LINEAR` mode so it could be a performance hit.
