### ISSUE TITLE
Tetrahedral Lut3D CPU SIMD Optimizations

### ISSUE THREAD

**Issue by markreidvfx** [AcademySoftwareFoundation/OpenColorIO#1681]
I added SIMD optimizations to FFmpeg's lut3d filter a while ago and recently set up a small project to measure the performance of various tetrahedral Lut3D implementations with different compilers.

https://github.com/markreidvfx/lut3d_perf

The FFmpeg implementation was done in x86_64 assembly, but I've since ported it to SSE2, AVX and AVX2 intrinsics and have come up with a few more optimizations.

![Random_lut_1024x1024_windows](https://user-images.githubusercontent.com/814966/186297018-7dd1f0ba-4aa6-4f46-ab54-506c920fe8fa.png)

Compared to OCIO's implementation, my branchless approach appears to be more performant, at least on the platforms I've tested.

**Comment by KevinJW** [comment]
My results running on CentOS VM on an AMD EPYC 7F72 24-Core Processor with devtoolset-6 and devtoolset-9 compilers

![image](https://user-images.githubusercontent.com/1186170/186384117-da0a76a1-568d-43e6-b8d9-4a77bc52faf1.png)

![image](https://user-images.githubusercontent.com/1186170/186384164-88e88c3f-9e17-400c-b31b-889b6ef463a2.png)

![image](https://user-images.githubusercontent.com/1186170/186384227-d3f221eb-b12c-4662-9405-dddb1e975295.png)

**Comment by markreidvfx** [comment]
Wow, didn't expect AVX to out perform AVX2 that much! Even SSE2 does in LUT2.  The main difference is AVX2 is using the `vgatherdps` instruction. I guess the way I changed the gather in SSE2/AVX is more cache friendly. AMD's `vgatherdps` might also not be as optimal as Intel's. I'll try changing the AVX2 version to use the AVX technique, if it doesn't improve perf, there might not be much need for a AVX2 version.,

**Comment by markreidvfx** [comment]
I look a bit more into this. According to [FFmpeg](https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/x86/cpu.c#L204), AMD Zen 3 and earlier have slow gather, same with intel Haswell.
AMD EPYC 7F72 is a Zen 2 [architecture](https://en.wikipedia.org/wiki/Epyc#Second_generation_Epyc_(Rome)), so I think the performance in `AVX2` makes sense.  The `cpuid` instruction can be used to identify these cpus and not use the AVX2 version.

**Comment by doug-walker** [comment]
Closing as this was implemented in PR #1687.
