### ISSUE TITLE
vcpkg install failure

### ISSUE THREAD

**Issue by xchen31u** [AcademySoftwareFoundation/OpenColorIO#1683]
getting this when installing from the vcpkg install mentioned in the official documentation:
```
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/src/vcpkg/buildtrees/openimageio/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\openimageio\config-x64-windows-CMakeCache.txt.log
      C:\src\vcpkg\buildtrees\openimageio\config-x64-windows-CMakeCache.txt.log
      C:\src\vcpkg\buildtrees\openimageio\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  ports/openimageio/portfile.cmake:43 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building openimageio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openimageio
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openimageio]+Build+error
Include '[openimageio] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: acc3bcf76 2022-08-15 (2 weeks ago)

You can also use the prefilled template from C:\src\vcpkg\installed\vcpkg\issue_body.md.
```

Running the failed command manually, seems to be a version conflict with Imath.
```
--     PNG_INCLUDE_DIRS = C:/src/vcpkg/installed/x64-windows/include;C:/src/vcpkg/installed/x64-windows/include
--     PNG_LIBRARIES = optimized;C:/src/vcpkg/installed/x64-windows/lib/libpng16.lib;debug;C:/src/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib;optimized;C:/src/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/src/vcpkg/installed/x64-windows/debug/lib/zlibd.lib
-- Found BZip2 1.0.8
--     BZIP2_INCLUDE_DIR = C:/src/vcpkg/installed/x64-windows/include
--     BZIP2_INCLUDE_DIRS = C:/src/vcpkg/installed/x64-windows/include
--     BZIP2_LIBRARIES = optimized;C:/src/vcpkg/installed/x64-windows/lib/bz2.lib;debug;C:/src/vcpkg/installed/x64-windows/debug/lib/bz2d.lib
-- Not using Freetype -- disabled
-- Found OpenColorIO 2.1.2
--     OPENCOLORIO_LIBRARIES = OpenColorIO::OpenColorIO
CMake Error at src/cmake/externalpackages.cmake:172 (message):
  OpenColorIO and OpenEXR use incompatible versions of Imath.  You cannot use
  openimageio[opencolorio] for this configuration.
Call Stack (most recent call first):
  CMakeLists.txt:141 (include)
```

What could be the issue? Is there something incompatible with my environment? Are the official docs from https://opencolorio.readthedocs.io/en/latest/quick_start/installation.html#installation outdated? Was there a recent breakage?

Also the link to "homebrew homepage"  is broken on that page.

**Comment by cedrik-fuoco-adsk** [comment]
Hello @xchen31u,

Could you list the steps that you have done? e.g. the commands that you did, etc.

Are you trying to install OpenColorIO with Vcpkg or are you trying to build it from source?

**Comment by xchen31u** [comment]
Hi,

I'm trying to install OCIO following the instructions. The command is:
```
vcpkg install openimageio[opencolorio,tools]:x64-windows --recurse
```

**Comment by xchen31u** [comment]
bump!

**Comment by EvanAW** [comment]
Hi @xchen31u. This is an issue with vcpkg’s repository currently having incompatible versions of Imath and OpenEXR. I am looking to see if I can help move OpenEXR’s update forward to fix it. 

> You can install both ports at the same time, but you can't use them at the same time.
For this reason, you currently cannot install openimageio[opencolorio] with the latest versions of these ports, because opencolorio was updated to use the new imath while openimageio still uses the outdated openexr.

https://github.com/microsoft/vcpkg/pull/26513#issuecomment-1227053580

**Comment by xchen31u** [comment]
Thanks @EvanAW !

Would using brew mitigate this issue?
Or using another platform such as linux / mac?

**Comment by doug-walker** [comment]
Recent testing shows that this now succeeds:
`vcpkg install openimageio[opencolorio]:x64-windows --recurse`

But the install with the tools option (needed to get oiiotool) still fails due to a QT problem:
`vcpkg install openimageio[opencolorio,tools]:x64-windows --recurse`

However, that is a problem that doesn't seem to have anything to do with OCIO and would be more appropriately logged to vcpkg or oiio.

I don't want to remove it from our installation page, since it is in theory a valid option.  Hopefully it will be fixed on their side soon.
