### ISSUE TITLE
Missing library dependencies when building static libs 

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1698]
I'm having trouble building _static_ OpenImageIO libs against _static_ OpenColorIO builds. 

```
CMake Error at /sw/dev/zlewis/packages/OpenColorIO/2.2.0.dev21/platform-linux/arch-x86_64/python-3.8/.shared-0/lib64/cmake/OpenColorIO/OpenColorIOTargets.cmake:61 (set_target_properties):
  The link interface of target "OpenColorIO::OpenColorIO" contains:

    expat::expat

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /sw/dev/zlewis/packages/OpenColorIO/2.2.0.dev21/platform-linux/arch-x86_64/python-3.8/.shared-0/lib64/cmake/OpenColorIO/OpenColorIOConfig.cmake:12 (include)
  src/cmake/modules/FindOpenColorIO.cmake:31 (find_package)
  src/cmake/checked_find_package.cmake:127 (find_package)
  src/cmake/externalpackages.cmake:177 (checked_find_package)
  CMakeLists.txt:151 (include)
```

@lgritz recently [merged a PR](https://github.com/OpenImageIO/oiio/pull/3552) that seems to address a very similar issue when building other libraries against OIIO.

**Comment by remia** [comment]
Thanks for raising that and sharing the OIIO fix Zach, I think it's something that was already mentioned in other places, including https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1581 and would be good to fix for the upcoming release.

**Comment by doug-walker** [comment]
@zachlewis , could you please try this again with OCIO 2.2.1?  We think this should be fixed.
