### ISSUE TITLE
Add icc2ocio utility

### ISSUE THREAD

**Issue by jeremyselan** [AcademySoftwareFoundation/OpenColorIO#170]
Add a utility that will take 2 icc profiles, and bake out a 3d transform that maps from the 1st into the 2nd.  This is essentially the inverse of ocio2icc, and will be the current workaround for now allowing icc profiles to be used for calibration 'live'.  This may require a new transform type representing an 'in memory' 3dlut, to allow for the existing baker output code to be used.

**Comment by michdolan** [comment]
#541 should make this possible. Do you agree @hodoulp ?

**Comment by doug-walker** [comment]
@michdolan , #541 is the first step towards allowing ICC profiles to be incorporated into a ColorSpace and thus used in Views/Displays.  We have some additional work planned as part of v2 to make this more practical to use.

However, #541 does not provide the icc2ocio utility.  Such a utility would need a lot more work if it needs to support arbitrary ICC transform constructs (e.g. A2B0, B2A0 tags, etc.).

**Comment by michdolan** [comment]
Do you think it would make sense though to target this functionality as a part of ociobakelut instead of adding another app? Assuming ICC is eventually fully supported within a colorspace.

**Comment by doug-walker** [comment]
The user would need to specify two ICC profiles, the rendering intents they want to use, and perhaps other information, so it would be a lot of arguments to add to ociobakelut just for that one use-case.

Correct me if I'm wrong, but it seems that this utility was largely proposed as a workaround to enable better use of ICC monitor profiles within OCIO.  We are on track to enabling that through a more direct integration (i.e., allowing the configs themselves to refer to them), and so the need for this utility is probably reduced.  Once we add the remaining display-related v2 functionality we may want to close this issue.

**Comment by michdolan** [comment]
I agree. I was completely vague in my initial comment, but that's sort of where my thought process was going. Less, can we support icc2ocio, and more, does #541 negate the need for it. The comment about #87 above was a first pass at an ICC transform, so it seemed to align with your work there.

We can revisit it following your further ICC work.
