### ISSUE TITLE
Expose RRT as builtin transform

### ISSUE THREAD

**Issue by SRHMorris** [AcademySoftwareFoundation/OpenColorIO#1732]
Forgive me if this is already possible, I'm fairly new to OCIO and ACES.

My use case is that I have a render engine, currently Direct3D12 and Metal, that I want to make ACES aware. The swapchain in D3D12 is set to fp16 and assumed to be linear rec709/sRGB. In Metal we set it to fp16 and specify the color space as ACEScg. As color is handled by the graphics api I don't want to run an ODT. However I still want to run the RRT (and inverse RRT on any display referred input files). Currently I'm just converting the primaries and whitepoint from ACES2065-1 to rec709 or ACEScg depending on the platform (i.e. without the RRT).

Of course it's quite possible I've missed or misunderstood something.

**Comment by doug-walker** [comment]
> As color is handled by the graphics api I don't want to run an ODT. However I still want to run the RRT 

I'm not aware of anyone applying the RRT on its own.  It doesn't make sense unless you are rendering to a device with unlimited dynamic range and gamut in a cinema viewing environment.

Please keep in mind that the tone-mapping in ACES is split between the RRT and ODT.  For example, the RRT doesn't do any highlight roll-off.  If you are simply looking to apply the tone-mapping but avoid the conversion to a specific set of primaries and gamma, then the Built-in ACES View Transforms will do that for you.

**Comment by SRHMorris** [comment]
Most of the media that will be imported is display referred. I want this to pass through the pipeline more or less unchanged so that it displays correctly after the RRT/ODT. For image files I'm not using OCIO but littleCMS to convert as it seems to have far wider support for different ICC profiles. For video files I can use the metadata or assume Rec709. This means it's essentially just converting the primaries to ACES2065-1. It then seems to make sense to me that I'd need to apply the inverted RRT (I'm aware that it's not completely invertible) to cancel out the RRT which would normally be combined in with the ODT.

So assuming I do use the combined RRT/ODT (with a DisplayViewTransform?) it seems to me I'd still have a use case for exposing the (inverted) RRT to go from display referred to scene referred (without hardcoding or requiring user interaction in the majority of cases). So e.g. a display referred sRGB image running through when using a sRGB DisplayViewTransform should look more or less identical to the original. I've seen discussion online saying to use an inverted display transform as an IDT, however this requires user interaction in the best case, and is impossible if the source media has a different color profile to any of the displays in the config.

**Comment by doug-walker** [comment]
You may use a DisplayViewTransform in the inverse direction to convert display-referred imagery back to a scene-referred space such as ACES2065-1.  The recently released ACES Studio or CG configs are available for that purpose.  

Keep in mind that an inverse RRT does not really convert display-referred imagery, in any practical sense, to scene-referred.  The RRT was a useful abstraction during the development of ACES but does not serve any useful purpose on its own.

**Comment by SRHMorris** [comment]
> Keep in mind that an inverse RRT does not really convert display-referred imagery, in any practical sense, to scene-referred

I'm aware it's not really scene-referred, I just want it to display correctly for the user after the RRT+ODT.

> You may use a DisplayViewTransform in the inverse direction to convert display-referred imagery back to a scene-referred space such as ACES2065-1. The recently released ACES Studio or CG configs are available for that purpose.

Yeah and that would work if I could guarantee that the input media was in one of the known display color spaces (sRGB, P3, Rec2020 etc). But I can't. I did think of converting to a wide space like Rec2020 and then hardcoding DisplayViewTransform. But it's quite possible the source is in a larger space (e.g. ProPhoto).

I had thought what might work is to create a new color space labelled as OCIO::REFERENCE_SPACE_DISPLAY using all the attributes from the aces_interchange role, convert the source to the ACES2065-1 space by just converting primaries/whitepoint using littleCMS, and then convert from the new space to aces_interchange. However that seems to lead to broken highlights.

**Comment by doug-walker** [comment]
Are there any ICC profiles you are loading with lcms that OCIO won't read?  Most profiles used for monitors or for tagging images should load in an OCIO FileTransform.  (OCIO won't read printer profiles, but I'm guessing that is not something you're interested in.)  You could then create virtual displays for them and use them in a DisplayViewTransform with the existing built-in view transforms.  The virtual display feature was specifically built to be able to do things like integrate ICC display profiles into an ACES workflow.

**Comment by SRHMorris** [comment]
I was under the impression that non rgb input profiles (e.g. CMYK or Lab) or specific tone response curves wouldn't work. At any rate it looks like FileTransform can't be created with an in-memory blob? Also if an image doesn't have an embedded profile but sets something like AdobeRGB or linear sRGB in the metadata I'd probably have to add these color spaces to the config. I'm still inclined to think that a better way would be to convert to a display referred space using the AP0 primaries and then use OCIO to do the psuedo display referred to scene referred conversion, i.e. from this space to aces_interchange.

Maybe I'm coming about this the wrong way, I'm more familiar with more traditional color management.

**Comment by doug-walker** [comment]
It looks like you left out a step in your first example, to call setDefaultViewTransformName("ACES 1.0 - SDR Video").  If I do that, I'm able to reproduce your numbers.  However, "my_color_space" is not AP0, as your example seems to imply.  It is the display-referred reference space, which is CIE-XYZ-D65 for that config.

Your color[3] value produces a pretty extreme ACES2065-1 value of [46.5, 284.5, 1.3] after proc1.  During the computation, the values go outside the AP1 triangle and get clamped.  That is a known issue with the ACES 1.x Output Transform.  However, if you started with the CIE-XYZ-D65 values of the green sRGB primary, your color[3] value would be [0.357592, 0.715185, 0.119197] and that round-trips to [0.358354, 0.715453, 0.123967] which is much closer.  But most values directly on the sRGB gamut will not round-trip exactly due to that known ACES 1.x issue.

**Comment by SRHMorris** [comment]
Excellent, looks like it was a misunderstanding on my part then, I'll close this issue. I can confirm that I'm getting color values that (at least visually if not numerically) look much closer to what I was expecting. It's a shame it can't currently roundtrip precisely up to machine precision though. I guess that's an issue with ACES rather than OCIO though.

Thanks for your time!
