### ISSUE TITLE
TSC Nomination: Thomas Mansencal, WetaFX

### ISSUE THREAD

**Issue by carolalynn22** [AcademySoftwareFoundation/OpenColorIO#1756]
Per the guidelines of the OCIO GOVERNANCE.md, this issue is to nominate adding Thomas Mansencal (@KelSolaar) as a voting member of the OCIO TSC, and as an official representative on the TSC for WetaFX.

Thomas has been a longstanding contributor and leader in the community - from maintaining the original ACES OCIO configs as part of the colour-science for python library, to being the main developer for the new ACES configs for OCIO 2.0. In addition to OCIO, Thomas is the lead and main developer of colour-science, an ACES Architecture TAC member and active ACES WG participant, and much more. Let's make it "official!" :)

**Comment by KelSolaar** [comment]
Thank you! :)

**Comment by mjtitchener-fn** [comment]
+1 from me. Thomas would be a great addition to the TSC!

Surprised it has taken this long 😃 

Mark

**Comment by doug-walker** [comment]
Implemented in PR #1803.
