### ISSUE TITLE
TSC Nomination: Zach Lewis, Method Studios

### ISSUE THREAD

**Issue by carolalynn22** [AcademySoftwareFoundation/OpenColorIO#1757]
Per the guidelines of the OCIO GOVERNANCE.md, this issue is to nominate adding Zach Lewis (@zachlewis) as a voting member of the OCIO TSC, and as an official representative on the TSC for Method Studios.

Zach has been an OCIO contributor and active community member for many years now. He has been an active participant in the Config, UX, and Documentation working groups, and is always willing to jump in and test new features, report issues, and answer questions on slack. Zach is thorough in his thought process, and always bringing ideas and solutions to the table. We look forward to welcoming him in an official capacity to the TSC!

**Comment by KelSolaar** [comment]
This is awesome and well deserved!

**Comment by zachlewis** [comment]
Likewise, my friend :)

Thanks Carol!

**Comment by KevinJW** [comment]
I agree, but because of our affiliation between Framestore and Method I will hold my +1

Kevin

**Comment by mjtitchener-fn** [comment]
+1 from me, Zach would be a great addition to the TSC!

Mark

**Comment by doug-walker** [comment]
Implemented in PR #1803.
