### ISSUE TITLE
Apply Reference Gamut Compression in Nuke 13.2

### ISSUE THREAD

**Issue by Bahloowee** [AcademySoftwareFoundation/OpenColorIO#1760]
Hi everyone !

For a project, I'm currently working under ACES 1.3 on Nuke 13.2 and I have cursed all old and new Gods trying to figure out how to make everything go smoothly.

I managed importing OCIO 2.0 via my custom color settings and all went well until...I tried rendering some shots in a Rec.709 MOV file and had this famous Gamut Compression issue.

After a bit of looking around the web, I found that it's a common problem who can be taken care of by using the Reference Gammut Compression in a OCIOLookTransform node, if I'm right. But I can't found how to call the RGC inside this node...Have I to type a specific code in the "look" window ? Is it cause of my nuke version ? I could use a hand right now. I feel I'm close to get my renders in the right colors !

**Comment by nick-shaw** [comment]
You need to type the full name of the look, which is "ACES 1.3 Reference Gamut Compression" (hover over the field and it with show you the names of the available looks in your config.)

However the RGC is only available in OCIOv2.1, which I believe was not introduced until Nuke 14. In earlier versions of Nuke you need to use the stopgap version posted on the [Academy repo](https://github.com/ampas/aces-vwg-gamut-mapping-2020/tree/master/reference/Nuke).

**Comment by doug-walker** [comment]
Closing, thanks for the investigation.
