### ISSUE TITLE
Fails to find zstd

### ISSUE THREAD

**Issue by berniyh** [AcademySoftwareFoundation/OpenColorIO#1761]
Hi,

I'm trying to build OpenColorIO on Exherbo Linux and it fails to configure due to not finding zstd, even though it is installed (and also found by other packages, e.g. via pkg-config).
I've tried both recent git main as well as the latest release, both behave the same way.
The cmake error message is:
```
CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findzstd.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "zstd", but
  CMake did not find one.

  Could not find a package configuration file provided by "zstd" with any of
  the following names:

    zstdConfig.cmake
    zstd-config.cmake

  Add the installation prefix of "zstd" to CMAKE_PREFIX_PATH or set
  "zstd_DIR" to a directory containing one of the above files.  If "zstd"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/host/lib64/cmake/minizip-ng/minizip-ng-config.cmake:30 (find_dependency)
  share/cmake/modules/Findminizip-ng.cmake:41 (find_package)
  share/cmake/modules/FindExtPackages.cmake:141 (find_package)
  CMakeLists.txt:270 (include)
```
(In case you're wondering about the odd library path: /usr/host/lib64 is a symlink to /usr/host/lib and there is also a symlink /usr/lib to /usr/host/lib, also /usr/host is a symlink to /usr/x86_64-pc-linux-gnu. It's more or less random which path is shown by scripts. In any case, all of this is irrelevant here and most certainly not the problem.)

Indeed, there is no cmake module Findzstd.cmake in /usr/share/cmake/Modules. I don't think you can rely on the system providing this, so it should possibly be provided by the project itself.
For reference, you can have a look at the Findzstd.cmake that llvm uses:
https://github.com/llvm/llvm-project/blob/main/llvm/cmake/modules/Findzstd.cmake

**Comment by cedrik-fuoco-adsk** [comment]
Hi @berniyh,

You are correct. It is a known limitation currently.
As of now, unfortunately, if you provide your own minizip-ng, it has to be built like OCIO wants it - which is everything turned off and with ZLIB support.

If you don't need specific versions of any dependencies, you could set OCIO_INSTALL_EXT_PACKAGES=ALL when building OCIO. It will download, build and install the required dependencies. 

Would that work for you? @berniyh

**Comment by doug-walker** [comment]
We discussed this and there is no simple way to improve this.  It's really up to the user to follow the installation directions and build minizip-ng appropriately.

**Comment by berniyh** [comment]
Ok, thanks for letting me know. I'll set the requirements accordingly.
