### ISSUE TITLE
Are 3D LUTs really non-invertible with ociobakelut --invlut?

### ISSUE THREAD

**Issue by vaisest** [AcademySoftwareFoundation/OpenColorIO#1766]
I noticed this line in [the documentation](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/docs/tutorials/baking_luts.rst#reversing-a-1d-lut):

"You can apply a LUT in reverse, and write this to a new LUT (this does not work for 3D LUT's, but will for 1D LUT's):"

However, I saw a message in some random thread (can't find link anymore) that says v2 added support for 3D LUT inversion. Now, that's no proof, but I also managed to inverse a Resolve 3DLUT just fine. Is this line really true or is it outdated?

Any related source code didn't seem to care to check if the LUT is 3D or 1D. Also, just as a disclaimer I really don't know what I'm doing with this tool so this might all be a misunderstanding.

**Comment by zachlewis** [comment]
Good catch! Yeah, that part of the documentation is outdated; the "--invlut" flag totally works for 3D LUTs, as of OCIO-2.0. Anecdotally, we've been using this in production at work to generate LUTs for our OCIO-1 pipeline for a couple of years now. It's awesome.

(I'd once run into an issue with inverting (some?) .csp concatenated 1D shaper + 3D lattice LUTs -- need to definitively test if this is still the case, but I think Remi fixed whatever was causing the problem I was having).

**Comment by KevinJW** [comment]
It depends what you mean, the v2 tools will produce an output that is valid given certain constraints on the input LUT, but there are no guarantees, e.g. if you made a LUT that desaturated the output to a monotone output - don't expect it to add back the colour correctly!

For most reasonable display transform LUTs, the algorithm will produce a reasonable result within the core of the LUT, but it will be limited by any clipping or limits the LUT has. It can also have issues if the LUT produces the same output values for 2 different areas of your input colour space - e.g. if the LUT emulates a hue keyed region being adjusted in a grading tool like could be used to despill where you move "this area of blues" towards yellow, then the inverse can't know if a bunch of yellow pixels were originally yellow or blue.

**Comment by doug-walker** [comment]
The documentation should be updated to remove "(this does not work for 3D LUT's, but will for 1D LUT's)".
