### ISSUE TITLE
OCIO for SPEC CPU v8

### ISSUE THREAD

**Issue by heshpdx** [AcademySoftwareFoundation/OpenColorIO#1768]
Hi friends,

I’m a CPU architect at Ampere Computing where I do performance analysis and workload characterization. I also serve on the [SPEC CPU](https://spec.org/cpu2017/) committee, searching for CPU benchmarks for the next version of the suite.  We try to find computationally intensive workloads in diverse fields, to help measure performance across a wide variety of behaviors and application domains.  

I'm also an independent filmmaker - I edit with Vegas and color grade with Resolve. However I have no experience with VFX.

Based on my experience in CPU workloads and my cursory knowledge of media pipeline workflows, I think it would be really cool to craft a benchmark based on OpenColorIO. You all have a very active and supportive community here, and the ASWF has done a great job of bringing content creation folks across the industry to work together. I would love to shine a light on this work through inclusion in the next set of marquee benchmarks in SPEC CPU. I did some cursory work to download and build `ocioperf` but I don't have the experience to create a useful or representative cmdline. Is ocioperf even the right way to exercise the important and common parts of the code? How can we properly exercise colorimetry, tetrahedral LUTs, grading, conversion, etc? Would we use raw images or would we need raw videos? If anyone is interested in helping, read on...
 
The SPEC committee is running a “search program” or contest, where anyone can submit their benchmark ideas. I am humbly asking if one of you can please submit OCIO for consideration. The main criteria for a benchmark is that it should be CPU bound (no GPU offload), can build and run on multiple platforms, and completes in about 3 minutes on a modern machine with a reproducible and verifiable result. You might know of even better candidates to offer from the ASWF, and that is great! I just chose this one since it uses C++ and I was able to build it easily. You can see all the details of the contest at [https://spec.org/cpuv8/](https://spec.org/cpuv8/), along with the [submission form](https://www.spec.org/cpu/cpuv8/entry_form.html).  **There are monetary rewards for the submitter if the entry is chosen to move forward.** An individual can submit but a company or group cannot.

Full disclosure: Since I am on the committee, I cannot submit entries for winning prizes. But one of you can, and I encourage you to do so. I promise you will enjoy the collaboration and we would all learn something. The development would happen over the course of a month, maybe ten hours total on your part depending on how complex we craft the workload, and how quick our back-and-forth is. I have completed other CPU benchmarks in less time, so that estimate is conservative.

There will be portability issues that we may find along the way, which we would push back to the mainline (you can check my github history for how this was done with other projects).  The compilers we test with are gcc-{8,10,12,13}, nvhpc, icpc, aocc, msvc, llvm-{13,14,15}, cray, and maybe some others.  The platforms are arm, x86, powerpc, risc-v, cray, on linux, windows, and sometimes aix. So that process is also part of the journey. 

Anyway, if this sounds interesting, please discuss and let me know. There is about one month left before the deadline of the first step, which is submitting the [entry form](https://www.spec.org/cpuv8/entry_form.html). This is a tremendous opportunity to have a lasting impact on the CPU industry and put a spotlight on the work done by the Academy Software Foundation.

Cheers,
Mahesh

**Comment by doug-walker** [comment]
Hi @heshpdx , I'm attaching a zip file with a LUT file that exercises many of the transform types OCIO uses.  
[heavy_transform.clf.zip](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/11024108/heavy_transform.clf.zip)

To apply this using the ocioperf command-line tool, the command would look like:
`ocioperf --test 0 --iter 50 --transform heavy_transform.clf `

You wrote above you were looking for something that takes about 3 minutes to run.  The transform I've attached is heavier than what people typically apply in OCIO.  And ocioperf is processing an internally-generated RGBA image that is 3840x2160 through that transform.  On my laptop, it does that in about 1/4 of a second.  So to get a 3 minute task, it would require doing a lot of repetitive processing.  (The ocioconvert tool is similar to ocioperf and could be used by pointing it at a large sequence of frames to process, although then the disk I/O would be a significant part of the overall time and I'm suspecting that's not desirable for a CPU benchmark.)  But ocioperf has an --iter option that may be used to repeat the processing an arbitrary number of times (maybe 72k would be about what it would take?).

I don't have the bandwidth at the moment to submit an entry for the contest, but hopefully the above information will be useful if you or another contributor wants to do that.

**Comment by heshpdx** [comment]
Hi friends,
I wanted to share that this project is complete, SPEC CPU2026 is out the door, and OCIO is in the floating point suite. You can read about the benchmark selection process in our paper here: https://arxiv.org/abs/2605.01575

And you can learn more about the suite here: https://spec.org/cpu2026/

The one addition I added to ocioperf was to generate 8k-UHD images, so there is longevity in the benchmark. Thank you @doug-walker and the rest of the community. 

-Mahesh

**Comment by heshpdx** [comment]
Here is the documentation page for 736.ocio_r.

https://spec.org/cpu2026/docs/benchmarks/736.ocio_r/736.ocio_r.html

**Comment by doug-walker** [comment]
@heshpdx, thank you for updating the community on this initiative! I'm glad to see OCIO including in the SPEC benchmark so that hardware designers are testing with workloads that are relevant for this community.
