### ISSUE TITLE
Named Transform Validation - small bug

### ISSUE THREAD

**Issue by carolalynn22** [AcademySoftwareFoundation/OpenColorIO#1798]
Hi, 

I've already discussed this with @doug-walker, but putting here for posterity and tracking: we've found an issue with calling NamedTransforms in config files (via ColorSpaceTransform). The calls work via the library, but the validation fails, so the config cannot pass ociocheck or load into any applications that run validation on config files. 

Doug already has a fix proposed, and would love if this could be patched back to 2.1 as well. 
Example:

`- !<ViewTransform>
    name: test_view
    description: |
      test for named transform validation bug
    from_scene_reference: !<ColorSpaceTransform> {src: test_space, dst: ACES2065-1}`
    
`- !<NamedTransform>
    name: test_space
    aliases: [ts]
    description: |
      test named transform 
    family: test
    categories: [file-io]
    encoding: scene-linear
    transform: !<GroupTransform>
      children:
        - !<MatrixTransform> {matrix: [1.49086870465701, -0.268712979082956, -0.222155725704626, 0, -0.0792372106028327, 1.1793685831111, -0.100131372460806, 0, 0.00277810076707935, -0.0304336146315336, 1.02765551391237, 0, 0, 0, 0, 1]}
        - !<MatrixTransform> {matrix: [1.11390097603689, -0.143391711690682, 0.0294907356537945, 0, -0.0330507612244472, 1.01678383525227, 0.0162669259721728, 0, -0.0533364871460785, 0.0222685264666346, 1.03106796067944, 0, 0, 0, 0, 1]}`

ociocheck error:
`** Validation **
ERROR:
Config failed validation. This config references a color space, 'test_space', which is not defined.
failed`

**Comment by doug-walker** [comment]
Closing as fixed by PR #1829.
