### ISSUE TITLE
CPUProcessor hasDynamicProperty() missing

### ISSUE THREAD

**Issue by remia** [AcademySoftwareFoundation/OpenColorIO#1799]
Hi,

Are we missing an API call to get the available dynamic properties  on a CPUProcessor instance?

It seem to be documented in [OpenColorTransforms](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/include/OpenColorIO/OpenColorTransforms.h#L671) but I don't find the corresponding method in the CPUProcessor class.

**Comment by doug-walker** [comment]
Good point Remi.  Given that CPUProcessor has getDynamicProperty, it seems like it should have hasDynamicProperty too.  

For the benefit of others reading this, the workaround is to use the hasDynamicProperty method on the Processor object that the CPUProcessor was generated from.
