### ISSUE TITLE
PyOpenColorIO: ImportError: DLL load failed while importing PyOpenColorIO: The specified module could not be found.

### ISSUE THREAD

**Issue by Pixel-Minions** [AcademySoftwareFoundation/OpenColorIO#1804]
Hi,

It seems the Python bindings are having issues loading in version 2.2.1. It builds fine, no errors, all DLLs are in the PATH but still I am getting:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing PyOpenColorIO: The specified module could not be found.
```

Is there any list of all the expected DLLs that should be in the PATH or is this a bug?

I have all these:

![image](https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/1145623/ccf2e0dd-059b-4764-9835-2b9c3d971522) + zlib.dll

Edit:

It seems that the files need to be next to the PYD file, else, even in the PATH it won't find the DLLs. Is there a way around?

Best,

**Comment by doug-walker** [comment]
@Pixel-Minions , are you aware of the changes to library paths that was made for Python 3.8+ on Windows? There are a bunch of other issues here related to that. We implemented a fix but are planning on modifying that, as described in issue #1785.

**Comment by Pixel-Minions** [comment]
Thank you for the information, I was not aware, for now, I will continue then adding the DLLs next to the python bindings.

Best,
