### ISSUE TITLE
Add VFX Platform 2023 to CI build matrix

### ISSUE THREAD

**Issue by jfpanisset** [AcademySoftwareFoundation/OpenColorIO#1807]
There is now a VFX Platform 2023 version of the ci-ocio aswfdocker build container available:

https://hub.docker.com/layers/aswf/ci-ocio/2023/images/sha256-ed653ea01cb89449ee01c2946ecef080cc8de478436cfd80d2c13bf6cb08f4ce?context=explore

It could now be added to the CI build matrix:

https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/6bf2dc0bb8be9192a404e52ab5894047834d5f51/.github/workflows/ci_workflow.yml#L62

There has been a fair number of changes to these containers since VFX Platform 2022, feedback welcome if any issues crop up.

**Comment by remia** [comment]
Thanks for the notice @jfpanisset, I can have a go at this but if someone else wants to, please reply here!
