### ISSUE TITLE
PyPI package contains dev dependencies

### ISSUE THREAD

**Issue by beatreichenbach** [AcademySoftwareFoundation/OpenColorIO#1811]
The current [PyPI package](https://pypi.org/project/opencolorio/) contains development dependencies that add a lot of unneeded data for everyday installations.

Currently the [setup](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/setup.py#L155) includes tests and test data that is not needed by normal users and should only be made available for developers.

Could it be possible to consider an approach with optional dependencies, where [setuptools](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) is used to specify dev dependencies?
For example: `pip install opencolorio[dev]`

If that is too much work, I think it would make more sense to just include the dev dependencies in the github repo and not distribute it to every installation to keep the package more light weight.

**Comment by remia** [comment]
Thanks for reporting @beatreichenbach! We are currently working on updating the Python wheels to include the command line apps, as part of that work the layout of the package is going to be updated and test code / data removed, this is happening in #1802.

I think we can expect wheels roughly half the size after this is completed.

**Comment by beatreichenbach** [comment]
Amazing! Thank you for your work on updating that and looking forward to the new lean packages. 👍
