### ISSUE TITLE
OSL shading language option not exposed in Python

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/OpenColorIO#1820]
It seems that from Python the specifier `OCIO.GpuLanguage.LANGUAGE_OSL_1` is not available as an option and thus it's not possible to set this as the output language for the GPUProcessor.

Appears to be an oversight in the Python wrappers [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/src/bindings/python/PyTypes.cpp#L510)

If exposed is it possible to indicate which version of OSL is available as part of the naming as there is no minor version as with the other languages ?

**Comment by doug-walker** [comment]
Fixed via PR #1832.
