### ISSUE TITLE
inactive roles

### ISSUE THREAD

**Issue by kenmcgaugh** [AcademySoftwareFoundation/OpenColorIO#1831]
Could support please be added for deactivating roles similar to the way colorspaces can be deactivated via the “inactive_color_spaces” config setting?

**Comment by doug-walker** [comment]
Hi Ken, I'm not clear on what you're trying to accomplish.  There is already a way to delete a role from the API.  What would be the purpose of making one inactive?  Please keep in mind that roles are not supposed to be user-facing items like color spaces.  (I know some applications have exposed the roles, but the UX working group discussed this topic and agreed that roles should not be exposed to users in menus.)

**Comment by kenmcgaugh** [comment]
Hi Doug, this request was indeed for limiting the roles shown in UI’s. By default nuke presents the roles above everything else and it is quite messy. Nuke can be configured to bury them under a submenu though. I wasn’t aware of the recommendation to keep them away from end users so please disregard this request. Thanks.
