### ISSUE TITLE
Replace Carbon with ApplicationServices

### ISSUE THREAD

**Issue by SRHMorris** [AcademySoftwareFoundation/OpenColorIO#1843]
This is macOS only.

Rather than linking to the Carbon framework, I'm pretty sure you can just link to the ApplicationServices framework, and in SystemMonitor_macos.cpp replace the include with ApplicationServices/ApplicationServices.h. I think that's the only usage of Carbon anyway.

Similarly, linking to this framework ([here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/caa20dd1962f0d659a9214ac28815a1b904d4118/src/OpenColorIO/CMakeLists.txt#L323)) only needs to be done if OCIO_HEADLESS_ENABLED is not defined (on another note, I couldn't find if this is enabled by CMake, I've been enabling it manually by adding it to the compiler flags).

I could submit a PR, but it might take time to go through legal.

**Comment by doug-walker** [comment]
A PR would certainly be welcome @SRHMorris.
