### ISSUE TITLE
v2.3.0 Python bindings source builds failing to load libOpenColorIO

### ISSUE THREAD

**Issue by remia** [AcademySoftwareFoundation/OpenColorIO#1846]
Filing this following report by @mjtitchener-fn during today's TSC meeting for tracking purpose.

On the latest release 2.3 and main branch, when building the Python package from source, there is an issue with RPATH not correctly installed preventing the import of PyOpenColorIO when using shared build.

The issue is most likely [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/src/bindings/python/CMakeLists.txt#L173), `CMAKE_INSTALL_RPATH` is indeed always defined at this point because it is set globally [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/share/cmake/utils/CompilerFlags.cmake#L140).

This does not affect the wheels because RPATH are defined independently [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/setup.py#L164).

**Comment by KevinJW** [comment]
My build on Linux, sets an rpath based on the top level setting e.g.  cmake command

`cmake \
    -DCMAKE_INSTALL_PREFIX="$DEST" \
    -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
    -DOCIO_INSTALL_EXT_PACKAGES=ALL \
    -DPython_EXECUTABLE=$PYTHON_EXECUTABLE \
    -DPYTHON=$PYTHON_EXECUTABLE \
    -DOCIO_USE_OPENEXR_HALF=ON \
    -Dyaml-cpp_STATIC_LIBRARY=ON \
    -DHalf_STATIC_LIBRARY=ON \
    ${BASE}/${SOURCE}
`

and then near the end of the build we see:

`-- Set runtime path of "/<my local install path>/opencolorio.v2.3.0-python2.7/bin/ociodisplay" to "$ORIGIN/../lib64:$ORIGIN"`
`-- Set runtime path of "/<my local install path>/opencolorio.v2.3.0-python2.7/lib64/python2.7/site-packages/PyOpenColorIO/PyOpenColorIO.so" to "$ORIGIN/../lib64:$ORIGIN"`

So the python bindings DSO is using the same rpath as the executables rather then the override, as @remia is suggesting.

This occurs for both Python 2.7 and 3.

**Comment by mjtitchener-fn** [comment]
I was chatting to @remia about this on Slack after the TSC call yesterday.
It does appear to be that simple, the following fixed it for me.
```
- if (UNIX AND NOT CMAKE_SKIP_RPATH AND NOT CMAKE_INSTALL_RPATH)
+ if (UNIX AND NOT CMAKE_SKIP_RPATH)
```

**Comment by KevinJW** [comment]
Indeed, I left the `AND CMAKE_INSTALL_RPATH` as the variable is used inside the if 'block', but I'm in no way a cmake expert, around the effects of the variable being not set/false, etc
