### ISSUE TITLE
opencolorio 2.3.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [AcademySoftwareFoundation/OpenColorIO#1897]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  -- Could NOT find pystring (minimum version: "1.1.3", recommended version: "1.1.3")
  --    pystring_ROOT was: /opt/homebrew/opt/pystring
  CMake Error at share/cmake/macros/ocio_handle_dependency.cmake:220 (message):
    pystring is required, will abort at the end.
  -- Could NOT find minizip-ng (minimum version: "3.0.6", recommended version: "3.0.7")
  CMake Error at share/cmake/macros/ocio_handle_dependency.cmake:220 (message):
    minizip-ng is required, will abort at the end.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6094230289/job/16535428119
relates to Homebrew/homebrew-core#141062

**Comment by remia** [comment]
Hi @chenrui333,

Thanks for the report, I noticed something similar while trying to build OCIO with `OCIO_INSTALL_EXT_PACKAGES=NONE` and homebrew packages, it seems this is the same thing going on here. I managed to have something working with the modifications in the last 2 commits of this [PR](https://github.com/remia/OpenColorIO/pull/52) though it probably need a bit more testing, note that I include the change from this other [PR](https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1796) which is also needed.
