### ISSUE TITLE
2.3.1 release build issue

### ISSUE THREAD

**Issue by chenrui333** [AcademySoftwareFoundation/OpenColorIO#1920]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  /tmp/opencolorio-20231211-6437-rqqe1t/OpenColorIO-2.3.1/src/OpenColorIO/ConfigUtils.cpp:6:10: fatal error: pystring/pystring.h: No such file or directory
      6 | #include "pystring/pystring.h"
        |          ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
```

</details>

relates to Homebrew/homebrew-core#156951

**Comment by doug-walker** [comment]
Thanks for the report, I'll submit a fix for this ASAP.

**Comment by chenrui333** [comment]
Thanks @doug-walker!

**Comment by wahn** [comment]
Changing the include line:
```diff
% git diff
diff --git a/src/OpenColorIO/ConfigUtils.cpp b/src/OpenColorIO/ConfigUtils.cpp
index 2e774726..b4228ff7 100644
--- a/src/OpenColorIO/ConfigUtils.cpp
+++ b/src/OpenColorIO/ConfigUtils.cpp
@@ -3,7 +3,7 @@
 
 #include "ConfigUtils.h"
 #include "MathUtils.h"
-#include "pystring/pystring.h"
+#include "pystring.h"
 #include "utils/StringUtils.h"
 
 namespace OCIO_NAMESPACE
```
Seems to fix the problem (at least on my machine) ...

```zsh
% make -j 4
...
[100%] Linking CXX shared module PyOpenColorIO/PyOpenColorIO.so
[100%] Built target PyOpenColorIO
```

**Comment by wahn** [comment]
All other places seem to use `include <...>` instead anyway:
```zsh
% rg -tcpp "pystring.h"
src/OpenColorIO/ConfigUtils.cpp
6:#include "pystring.h"

src/OpenColorIO/Config.cpp
15:#include <pystring.h>

src/OpenColorIO/transforms/FileTransform.cpp
12:#include <pystring.h>
...
```

So the diff should probably be:

```diff
% git diff
diff --git a/src/OpenColorIO/ConfigUtils.cpp b/src/OpenColorIO/ConfigUtils.cpp
index 2e774726..90e90449 100644
--- a/src/OpenColorIO/ConfigUtils.cpp
+++ b/src/OpenColorIO/ConfigUtils.cpp
@@ -3,7 +3,7 @@
 
 #include "ConfigUtils.h"
 #include "MathUtils.h"
-#include "pystring/pystring.h"
+#include <pystring.h>
 #include "utils/StringUtils.h"
 
 namespace OCIO_NAMESPACE
```

**Comment by chenrui333** [comment]
yeah, like @wahn, for `pystring` ti would be installed into the system path, and it is does not have `pystring/`. Use system include also works for me.

**Comment by doug-walker** [comment]
Thank you both.  Yes, I was aware of the problem introduced with ConfigUtils.h (it started in a branch that predated the pystring changes and I was too quick to accept git's merge of main).  What I'm wondering about is how to prevent this sort of break again in the future since neither our CI or my local builds detected the error.  We could change OCIO's local install to mimic the install structure used by, e.g. brew, but I was wondering if there are other variations out there.  (The pystring project itself doesn't seem to install the header, so maybe that contributes to the ambiguity about where it should go.)  Anyway, thanks for the PR!

**Comment by wahn** [comment]
You could use the **language server protocol** with basically any text editor which supports it. To make `CMake` spit out a `compile_commands.json` file you could use e.g.:
```zsh
% cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
After that I could for example use Helix (as described [here](https://www.janwalter.org/jekyll/lsp/2022/10/01/language-servers.html) and [there](https://www.janwalter.org/rnd/blog/rnd-helix-001/)) to see some useful messages within Helix:
<img width="1440" alt="Screenshot 2023-12-20 at 11 53 11" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/1074865/8ac0aeac-f7d3-4f8c-b502-1a4d5351d736">

Should work with MS Code as well and any text editor which supports the **language server protocol**. Things might be platform dependent, but I use it on MacOS and Linux. Should work on Windows as well ...
