### ISSUE TITLE
Implement new ACES 2.0 Output Transforms as Built-Ins

### ISSUE THREAD

**Issue by carolalynn** [AcademySoftwareFoundation/OpenColorIO#1934]
This is a starter issue to be filled in with more information as we have it.

ACES is getting ready to release its version 2.0, and with that will come a set of new Output Rendering Transforms. These will need implemented in the OCIO library similar to the v1 ACES transforms as built-ins. 

The goal is to release support for ACES 2.0 in our 2.4 release this year. @KevinJW (OCIO TSC member) has been co-chairing the ACES Output Transforms working group, and will be a resource, along with the rest of ACES leadership, to help OCIO developers get these implemented.

**Comment by doug-walker** [comment]
Closing as fixed via PR #1983.
