### ISSUE TITLE
Add a utility program to print out which CPU feature sets are supported on a machine

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1937]
OCIO uses some CPUInfo code to check which SIMD intsruction sets are supported on a given machine and this is used to decide which Lut1D and Lut3D evaluation code to use. It would be nice to have a command-line tool included with OCIO that users could run that would print out the various flags to assist in troubleshooting.

This could be a stand-alone app under src/apps.  Or the CPUInfo could be made accessible through the Python binding and then a script could be added under share/troubleshooting.

**Comment by catrinalim** [comment]
Hi! Can I take on this issue?

**Comment by carolalynn22** [comment]
Absolutely, @catrinalim - let us know if you have questions.

**Comment by doug-walker** [comment]
This is still available for someone to work on.
