### ISSUE TITLE
Add a helper function to check if an extension is supported by FileTransform

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1938]
The FileTransform class has several static methods such as GetFormatExtensionByIndex that will allow client programs to iterate over all of the supported formats to check if a given extension is supported by OCIO. However, it would be nice to have a helper function to just take the extension and return true/false.  Such as:

```
class FileTransform
    /// Returns true if the extension corresponds to a format supported by FileTransform.
    /// The argument is case-insensitive, and a leading dot, if present, is ignored.
    static bool IsFormatExtensionSupported(const char * ext);
```

**Comment by doug-walker** [comment]
Absolutely, thank you @corey-f1009 !

**Comment by Dundy703** [comment]
Could I give this a shot as well?

**Comment by doug-walker** [comment]
@Dundy703 , there is so much to do, it would be better for you to find a different issue. There are quite a few that are labelled "good first issue" or "help wanted".

**Comment by doug-walker** [comment]
This is still available for someone to work on.

**Comment by meimchu** [comment]
I would like to give this a look if possible. Might have some questions to ask :) Thank you!

**Comment by doug-walker** [comment]
Thank you @meimchu !
