### ISSUE TITLE
TSC / Committer Nomination: Mark Reid, Animal Logic

### ISSUE THREAD

**Issue by carolalynn** [AcademySoftwareFoundation/OpenColorIO#1943]
Per the guidelines of the OCIO GOVERNANCE.md, this issue is to nominate adding Mark Reid (@markreidvfx) as a voting member of the OCIO TSC, and as an official representative on the TSC for Animal Logic.

Mark's contributions to OCIO have been valuable and useful - including SIMD optimizations for 1D and 3D LUTs. He has been attending the TSC meetings for around a year now, and always offers valuable insight and quick feedback. 

I also propose we add Mark to our Committers group, so he can review and approve PRs.

Thank you for all of your contributions, Mark, and looking forward to making it official!

**Comment by KelSolaar** [comment]
Thumbs up!

**Comment by doug-walker** [comment]
Awesome!
