### ISSUE TITLE
Add new icon for TouchDesigner under Supported Application

### ISSUE THREAD

**Issue by mbechard** [AcademySoftwareFoundation/OpenColorIO#1951]
I think the correct categories would be:
2D, 3D, Animation, Compositing, Editing, Lighting, Playback, Render, Simulation, Texture, Tracking
Website is www.derivative.ca
attached is the icon.
Thanks!

![TouchDesigner](https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/3588417/c257699d-809a-4ff4-9113-43f8fc8eac70)

**Comment by sumana-2705** [comment]
Shall I work on this issue? @carolalynn

**Comment by doug-walker** [comment]
@sumana-2705 , did you have a particular interest in this issue, or are you just looking for a "good first issue" to help with? If the latter, you might want to just introduce yourself on the OCIO Slack to tell us a bit about your skill set and then we could recommend one for you. But if you already have found the issue you want to work on, please proceed. Thanks!

**Comment by doug-walker** [comment]
Closing as fixed by PR #2037.
