### ISSUE TITLE
Make display EOTFs in built-in transforms mirrored and unclamped to preserve sub-black and super-white

### ISSUE THREAD

**Issue by nick-shaw** [AcademySoftwareFoundation/OpenColorIO#1968]
In broadcast scenarios it is necessary for all processing to pass both sub-black and super-white values. BT.2111 test patterns, for example, include PLUGE, and the ramp goes from -7 to 109%. Broadcast engineers expect conversion to pass these values, so a config for broadcast use cannot currently be created using the built-in XYZ-D65 to display transforms.

**Comment by doug-walker** [comment]
@nick-shaw could you please review PR#2029 to make sure the math is what you expect for the PQ and HLG functions?

**Comment by nick-shaw** [comment]
The PQ and HLG curves appear to be correctly mirrored about zero to the best of my understanding (see my comment in #1969 regarding the OOTF). However since `LINEAR_TO_PQ(0.0) != 0.0` I am not sure if there is a standard way to remove the discontinuity resulting from a simple mirroring. I have in the past used an approach similar to the ACES "stretch black" to join a mirrored PQ curve at zero. But there may be other approaches that I am not aware of.

**Comment by doug-walker** [comment]
@nick-shaw , thanks for having a look.  Regarding your comment about 0, LINEAR_TO_PQ(0.0) does equal zero, so I'm not following you about a discontinuity at 0.

**Comment by nick-shaw** [comment]
By my calculations is close to zero but not zero. 
![image](https://github.com/user-attachments/assets/4890f027-4f59-4d0d-8de5-d8a248aa1aeb)
For input of zero the PQ value is `c_1^m_2`.

**Comment by doug-walker** [comment]
@nick-shaw , what you wrote is true, but that is a PQ value of 0.836^78.84 = 7.36e-07.  A single 16-bit code value in PQ would be 1/65536 = 1.53e-05.   So we're talking about a value in PQ that is over 20x smaller than a single 16-bit code value.  To me, that is 0, for all practical purposes.  Are there any real-world situations you're aware of where that causes a problem?

**Comment by nick-shaw** [comment]
No. I am not aware of any actual problem. I am just a pedant, for which I apologise!

**Comment by doug-walker** [comment]
Ha ha, don't apologize Nick!  You raised a valid point.  In fact, you made me realize that the CPU and GPU paths are giving slightly different results at 0 due to how the mirroring is done. It is way below visual threshold, but it still warrants a comment in the code to make people aware of the issue.  So thank you again for raising the question.

**Comment by doug-walker** [comment]
@nick-shaw , the fix for the OOTF (and hence the EOTF) is in PR #2051.

Once these are merged, it would be great to get feedback on whether all your HLG issues are addressed.

**Comment by doug-walker** [comment]
This should be fixed via PR #1992.  Assigning to @nick-shaw to confirm it meets his expectations.

**Comment by nick-shaw** [comment]
My testing confirms that with the new changes configs can be built for broadcast use which are able to pass sub-black and super-white values.

**Comment by doug-walker** [comment]
Thanks for checking Nick!  Closing this as fixed.
