### ISSUE TITLE
Add BT.2100 HLG OETF as a BuiltinTransform

### ISSUE THREAD

**Issue by nick-shaw** [AcademySoftwareFoundation/OpenColorIO#1969]
There is already a built-in `CURVE - LINEAR_to_ST-2084` transform, but no HLG curve exists. Only `DISPLAY - CIE-XYZ-D65_to_REC.2100-HLG-1000nit` which, being display-referred cannot be used for scene light conversions to and from HLG. As per #1968, this curve should be mirrored about zero.

**Comment by nick-shaw** [comment]
Thanks @doug-walker . I'm not fully au fait with reading C++ code, but as far as I can tell the maths for mirroring the HLG OETF seems correct. In order to support negative values through the HLG EOTF, the OOTF also needs to include mirroring. Is that already the case? I couldn't see a change to that in that PR.

**Comment by doug-walker** [comment]
Closing as fixed via PR #2029.
