### ISSUE TITLE
Improve Lut3D GPU unit test to not create temporary files

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#2017]
The module: OpenColorIO/tests/gpu/Lut3DOp_test.cpp, uses a function createTempFile to execute some tests with various test LUTs. These are not later cleaned up. These LUTs could be added to the test file directory and read from there so that no temp files are created. The createTempFile function could then be removed.

**Comment by ananthb** [comment]
I'll tackle this in the upcoming dev days event.

**Comment by carolalynn** [comment]
Sounds great, @ananthb - looking forward to having you participate! Please reach out on slack and say hello, or if you have any questions!

**Comment by ananthb** [comment]
Will do.

**Comment by carolalynn** [comment]
Hi @ananthb - just wanted to do a quick follow-up and see if you are still planning on tackling this issue? We'd love to have you participate - but either way, just let us know! :)

**Comment by ananthb** [comment]
I was a bit held up on the actual day of, but I'm working on it right now actually. I should be able to get some code across very soon.

**Comment by carolalynn** [comment]
No problem, sounds great! Feel free to reach out if you've got questions on slack.
