### ISSUE TITLE
Fix the view menu in the ociodisplay app

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#2057]
This would be a great first issue for someone!

Under the src/apps directory, OCIO comes with a few applications that allow people to test out various aspects of the software. One of these applications is "ociodisplay" which allows the user display an image in a window with OCIO processing applied.

In an OCIO config, there are a series of "displays" and each display has a series of "views". In general, each display may have a different set of views. For example, the views associated to an SDR display is usually different than for an HDR display.

Unfortunately, the primitive menu system in ociodisplay assumes that each display has exactly the same views. To see this, run the app with the -v option so it prints the actual display and view being used to the shell (they will be different from what you see in the menus).  Use the control-click menu to select various options from the "Device" menu (these are the displays), and then select options from the "Transform" menu (these are the views). (While you're at it, you could rename those menus to be "Display" and "Views".)

The built-in Studio config is an example config that shows the problem. Set the OCIO environment variable to "ocio://studio-config-latest" before launching ociodisplay to use that config.  

For test images, you could use one of the OpenEXR ACES test images from `[here](https://www.dropbox.com/scl/fo/zbrp6siai5r9wgasdlmle/ABYNKw5mO_aYdDn3m59c6cs/ACES?dl=0&rlkey=41zj6by2t39ckzt0caydb7s91&subfolder_nav_tracking=1)`.

**Comment by hannahmkrasnick** [comment]
I would love to tackle this issue for Dev Days!

**Comment by doug-walker** [comment]
Thank you Hannah, I've assigned this to you!

**Comment by carolalynn** [comment]
Hi @hannahmkrasnick -  just wanted to do a quick follow-up and see if you are still planning on tackling this issue? We'd love to have you participate - but either way, just let us know! :)

**Comment by hannahmkrasnick** [comment]
Hey @carolalynn ! I am, I will put up a PR this morning :) I don't think I have the right permissions yet but I'll throw it up anyway!

**Comment by carolalynn** [comment]
Sounds great, @hannahmkrasnick - feel free to reach out on our slack if you need anything!

**Comment by doug-walker** [comment]
Closing as fixed via PR #2068 during Dev Days 2024. Thank you Hannah!
