### ISSUE TITLE
Incorrect version in 2.4.0 release

### ISSUE THREAD

**Issue by SRHMorris** [AcademySoftwareFoundation/OpenColorIO#2073]
- Download the zip/tar from the 2.4.0 release in the releases page in github, or checkout the 2.4.0 tag.
- Open the top level CMakeLists.txt and scroll to the project() line.

The version is set as 2.5.0 (dev) rather than 2.4.0.

**Comment by remia** [comment]
Good catch @SRHMorris ! Will be sure to fix that, thank you for reporting.

**Comment by doug-walker** [comment]
Thank you @SRHMorris for flagging this. I've updated the v2.4.0 tag to point to the correct commit. The Releases page now looks correct, including the downloadable zip/tar assets.

Closing this as fixed.

**Comment by darix** [comment]
instead of repeating the tag as  2.4.0 , wouldnt it have been cleaner to tag it as 2.4.1 and mark 2.4.0 as a bad tag. e.g.  packager might have already grabbed the 2.4.0 tarball before the tag was fixed and then safety checks would trigger an alert about changed tarballs.
