### ISSUE TITLE
FTBFS w/ MSYS2 MinGW

### ISSUE THREAD

**Issue by kmilos** [AcademySoftwareFoundation/OpenColorIO#2100]
Both GCC and Clang fail w/ `_mm_pow_ps` error on Windows:

https://github.com/msys2/MINGW-packages/actions/runs/12086725004/job/33706625136?pr=22697#step:11:512
https://github.com/msys2/MINGW-packages/actions/runs/12086725004/job/33706625435?pr=22697#step:11:510

2.3.x was building just fine w/o patching.

Note that [MSYS2 targets `-march=nocona -msahf`](https://www.msys2.org/news/#2022-10-18-new-minimum-hardware-requirements-cpus-from-20067) (so no SSSE3, SSE4.2, AVX...)

**Comment by lazka** [comment]
Similar code is guarded differently, compare:

* https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/0f06f044bf94b3ca670ce74824f94cd462622086/src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp#L1792-L1801
* https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/0f06f044bf94b3ca670ce74824f94cd462622086/src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp#L1847-L1856

**Comment by lazka** [comment]
I noticed that the guard is fixed as part of #2089

**Comment by lazka** [comment]
@kmilos with #2089 merged this can be closed, right?
