### ISSUE TITLE
Config override in Nuke nodes?

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#230]
It might be useful to be able to specify a config file in the Nuke nodes.

In each node, there would be a file-knob to specify a config, which would override `$OCIO`. Also each node would have a "reload config" button, which would be useful even without the override.

Could maybe also have a config-override knob in the project settings, as a convenient way to load a config in env-var unfriendly setup, as it would mean you could set the config with something like:

```
nuke.knobDefault("root.ocio_config_override", "/path/to/my/config.ocio")
```

This would be similar to the [Mari<>Nuke bridge parameters](http://imgur.com/J7QsG) (err, screengrab'd from the [demo video](http://vimeo.com/22989271))

**Comment by zachlewis** [comment]
Did anything ever come of this? It seems like The Foundry kinda dropped the ball for all things color-related after they were pretty much gifted OCIO... for my part, I was gonna begin investigating creating a "mini-ocio" node that takes a config and exposes the transforms and looks for use in general nuke compositing. Provided they all have a "D65_XYZ_HANDOFF" role or something similar, I don't see why this wouldn't work (unless PyOpenColorIO can only open one config handle per session or something stupid).

**Comment by alexfry** [comment]
That would be pretty great. 

Especially when dealing with shots shared between facilities. 

Alex
