### ISSUE TITLE
Solve ACES highlight banding issue

### ISSUE THREAD

**Issue by jeremyselan** [AcademySoftwareFoundation/OpenColorIO#240]
In ACES, RRT+ODT will produce 'scalloped' artifacts when trilinear interpolation is used.  Gradient -> ADX10->RRT sRGB.  Test 3dlut tetrahedral interpolation vs. trilinear.
- What to do about the GPU codepath?  Add support for trilinear lookups, to the OCIO fragment code?
- What to do about the ACES ocio profile.  It would obviously be nice to switch the default to tetrahedral, but this would screw up people on versions of OCIO that dont support it...

**Comment by KevinJW** [comment]
As note, tetrahedral does not completely fix the problem but helps considerably.

https://www.researchgate.net/publication/305278559_A_retrospective_on_the_adoption_of_the_ACES_technology_at_Framestore

**Comment by scoopxyz** [comment]
@KevinJW was this successfully addressed by #441 ?

**Comment by KevinJW** [comment]
I have not looked - but I would suspect not as the scalloping is more related to the low sampling rate and "high curvature" miss-match, than a precision loss.

Kevin
