### ISSUE TITLE
fix compile warning on gcc46

### ISSUE THREAD

**Issue by jeremyselan** [AcademySoftwareFoundation/OpenColorIO#266]
309/home/vagrant/builds/jeremyselan/OpenColorIO/src/core/PathUtils.cpp: In function ‘std::string OpenColorIO::v1::pystring::os::getcwd()’:
310/home/vagrant/builds/jeremyselan/OpenColorIO/src/core/PathUtils.cpp:121:39: warning: ignoring return value of ‘char\* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]

**Comment by hodoulp** [comment]
Not anymore a gcc version supported. `master` branch does have the warning.
