### ISSUE TITLE
CMake'ify After Effects plugin

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#279]
Months ago, as mentioned in #272, I got somewhere with using CMake for the AE plugin (instead of needing the Xcode/VisualStudio projects), but got sidetracked..

In case it's of any use to whoever picks this up later: [this gist](https://gist.github.com/3897458) contains what I ended up with (needs an `add_subdirectory(src/aftereffects)` line in the root CMakeLists, which I enabled with an `OCIO_BUILD_AE` option)

Can't remember exactly how far I got with it - think it's mostly there (either it's missing something to register the plugin properly with AE, or it was crashing because something wasn't linked fully.. don't recall)

**Comment by richardlalancetteyoui** [comment]
Been looking for this for a few days! I'm stuck with problem on cocoa.h.

Thanks for sharing dbr!

**Comment by SamuelMarks** [comment]
Maybe this will assist? - https://github.com/luofalei/VTM/blob/master/cmake/CMakeBuild/cmake/modules/FindAdobeSDK.cmake

**Comment by richardlalancetteyoui** [comment]
One of CMake subject matter expert did the cmake intergration.
Thank god :) ahah
They also added notorization which is another step to consider to publish a production plugin.

**Comment by SamuelMarks** [comment]
Great to see @carolalynn
