### ISSUE TITLE
Compiling static and shared on windows

### ISSUE THREAD

**Issue by chadf** [AcademySoftwareFoundation/OpenColorIO#307]
Currently (as of 1.0.8) when building both static and shared libs the static .lib file overrides the shared one (since they both are OpenColorIO.lib).

Here is a patch that would add a postfix to the static lib when both are enabled:

 -<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-
--- src/core/CMakeLists.txt.orig    2012-12-11 15:21:23 -0800
+++ src/core/CMakeLists.txt 2013-01-23 21:57:30 -0800
@@ -65,12 +65,17 @@
             debug ${EXTERNAL_DEBUG_LIBRARIES}
             optimized ${EXTERNAL_OPTIMIZED_LIBRARIES}
             general ${EXTERNAL_GENERAL_LIBRARIES})
+
-   # Avoid name conflicts
-       if(OCIO_BUILD_SHARED AND NOT OCIO_STATIC_POSTFIX)
-       set(OCIO_STATIC_POSTFIX "-static")
-   endif()
   else()
       target_link_libraries(OpenColorIO_STATIC ${EXTERNAL_GENERAL_LIBRARIES})
   endif()
   set_target_properties(OpenColorIO_STATIC PROPERTIES
-        OUTPUT_NAME OpenColorIO
- ```
     OUTPUT_NAME OpenColorIO${OCIO_STATIC_POSTFIX}
   COMPILE_FLAGS "${EXTERNAL_COMPILE_FLAGS}"
   LINK_FLAGS "${EXTERNAL_LINK_FLAGS}")
  ```
  
   message(STATUS "Setting OCIO SOVERSION to: ${SOVERSION}")
  -<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-<>-

This would add "-static" to the end (by default) when both are enabled. It should also allow a user to choose a custom postfix by setting OCIO_STATIC_POSTFIX ahead of time (whether doing shared builds or not). It only does this by if both set as not to break any existing static-only builds that assume the normal name. Another option also used in other projects is to use the 'lib' prefix for the static one (i.e. libOpenColorIO.lib), which i believe can be done via a standard CMAKE var (instead of adding a new OCIO var), but may be less obvious.

Hopefully this isn't a redundant submission, as I also had two other patches ready (one for external tinyxml include dirs, and one for OCIO_STATIC_BUILD), but #300 seemed to already cover them, so I dropped them out.

**Comment by hodoulp** [comment]
Following the major `cmake` file refactoring done last year, only static or dynamic library is now built (not both) in `master`.
