### ISSUE TITLE
Why does processor.applyRGB return list instead of array in python bindings?

### ISSUE THREAD

**Issue by apetrynet** [AcademySoftwareFoundation/OpenColorIO#330]
Hi!
I'm writing a tool for slating images and applying colorspace conversions for internal and client review.
Read and writes are done through OpenImageIO with numpy arrays. My problem is that the call to processor.applyRGB is a real bottle neck. Since applyRGB accepts these arrays I'm a bit surprised that it returns a list. Are lists faster then arrays?

Am I off in suspecting the list issue of slowing down the process or is it the actual processing time that makes the biggest impact?

Thanks,
-Daniel

**Comment by jamesnewland** [comment]
Sorry to dig up this old thread, but I'm currently running into the same issue.  Could something like Cython be a possible solution for the unpacking problem with Numpy? 

Also I'm curious if anyone has had any luck with OIIO.  I ran a few simple tests, but I was getting about the same speed with a full OIIO solution as with Numpy and OCIO.

-James

**Comment by apetrynet** [comment]
Hi James!

The reason for the same speed is because they both (OIIO and OCIO) use the
same solution for converting the array.

I worked around this by spawning multiple processes. At least then
utilizing the full potential of the CPU.

-Daniel

**Comment by jamesnewland** [comment]
Bummer.  I was hoping I was doing something wrong.  

Thanks for the quick reply!

-James
