### ISSUE TITLE
Doc update: Nuke Vectorfield now matches OCIO applying CSP LUT

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#339]
http://opencolorio.org/FAQ.html#what-are-the-differences-between-nuke-s-vectorfield-and-ociofiletransform

..is now outdated - was true of Nuke 6.2, but the Vectorfield in 6.3v8 appears to match the OCIOFileTransform almost exactly.

Should update the documentation to reflect this

**Comment by scoopxyz** [comment]
I assume so, but this is for all the listed file formats?
