### ISSUE TITLE
OS X build problems for 1.0.9

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#340]
I finally got around to building 1.0.9

Using the changes from #321 worked nicely on Linux \o/

However I had to patch a few other things to make it work on OS X:

1) In yaml-cpp's CMakeLists.txt, the `FILES_MATCHING_PATTERN` made the yaml-cpp headers fail to install for some reason (the build died at `#include <yaml-cpp/yaml.h>` in `OCIOYaml.cpp`)

```
install(
    DIRECTORY ${header_directory}
    DESTINATION ${INCLUDE_INSTALL_DIR}
    FILES_MATCHING PATTERN "*.h"
)
```

2) Using `add_library(... MODULE)` for the Nuke plugins will unhelpfully produce `OCIOLogTransform.so`, the extension should be `.dylib` on OS X which is done with `add_library(... SHARED)`. Both are identical on Linux

Shall make a pull-request for these changes at some point (easiest when #321 is merged), but here's some diffs for now:

https://gist.github.com/dbr/7700532

**Comment by scoopxyz** [comment]
Current CI is showing that MacOS builds pass, are there still lingering issues there from your perspective?

I also don't have a MacOS machine on my end to test the Nuke plugin builds, so I'd have to trust your usage here. Could you wrap this into simple PR?

**Comment by doug-walker** [comment]
Closing as probably not relevant anymore.
