### ISSUE TITLE
Issues with non-ascii folders on Windows

### ISSUE THREAD

**Issue by sergeyvfx** [AcademySoftwareFoundation/OpenColorIO#406]
It is not possible to use configuration file which is located in a folder with non-ASCII characters on Windows. This is because simple `char*` is used to communicate filepath to a config file in `Config::CreateFromFile()`.

In order to have full Unicode support it seems adding similar `Config::CreateFromFile(wchar_t*)` will be needed. Or at least will need to be done some ASCII->UTF conversion in the function itself.

In order to reproduce the issue it should be enough to simply call `Config::CreateFromFile()` with a filepath which has non-ascii characters, such as German umlauts for example.

**Comment by hsdk123** [comment]
Hi, would it be possible to request an update to this? This has major impact on loading from non-english environments on Windows. The fix doesn't seem to be too difficult either.

**Comment by EvanAW** [comment]
I am looking to get a pull request in for this hopefully later this week.

**Comment by Dithermaster** [comment]
BTW, the way we solved this host-side was to call `GetShortPathName` Windows API to convert paths to something that OCIOv1 can eat.
