### ISSUE TITLE
ociolutimage --colorconvert doesn't work with --extract

### ISSUE THREAD

**Issue by sobotka** [AcademySoftwareFoundation/OpenColorIO#417]
Summary says it all. ociolutimage doesn't appear to transform the input RGB image when using colorconvert with extract.

**Comment by scoopxyz** [comment]
What is the use case here? You're trying to add a color space transform on top of an already generated LUT image, is this to string multiple operations together?

**Comment by sobotka** [comment]
I believe it was to prime the values to a certain state to test the transform in question.
