### ISSUE TITLE
INTERPOLATION: "Best" defaults to linear?

### ISSUE THREAD

**Issue by sobotka** [AcademySoftwareFoundation/OpenColorIO#422]
https://github.com/imageworks/OpenColorIO/blob/67a4f21db960bc1ce2ee040ff3264d3a9262af53/src/core/Lut3DOp.cpp#L674-L676

https://github.com/imageworks/OpenColorIO/blob/67a4f21db960bc1ce2ee040ff3264d3a9262af53/src/core/Lut1DOp.cpp#L555-L557

This appears by design, however should it not default to tetrahedral for the 3D LUT sampling?

**Comment by dbr** [comment]
I think "best" was left as linear to avoid changing the behaviour of existing configs at the time,

https://github.com/imageworks/OpenColorIO/pull/232

It could definitely be changed in a future non-patch release

**Comment by dekekincaid** [comment]
This may also be the default because the gpu implementation doesn't currently support tetrahedral.
