### ISSUE TITLE
Documentation and tests non-existent/outdated

### ISSUE THREAD

**Issue by pyalot** [AcademySoftwareFoundation/OpenColorIO#423]
I had a lot of trouble today with your library, and in part this is caused by a virtual lack of any documentation worthy of that name and a complete lack of any tests and examples.

**Comment by scoopxyz** [comment]
Agreed. We are in a sorry state at the moment, but if you have any questions for the time being our google group is somewhat responsive, or you can email myself directly, or post them here. Outside opinion is always useful.
