### ISSUE TITLE
lookup formats are undocumented

### ISSUE THREAD

**Issue by pyalot** [AcademySoftwareFoundation/OpenColorIO#424]
There's various lookup formats that the library uses, they're all undocumented.

**Comment by scoopxyz** [comment]
Agreed / Confirmed.

The provided list is via the ociobakelut app, which displays this on help:
flame (.3dl), lustre (.3dl), cinespace (.csp), houdini (.lut), iridas_itx (.itx), icc (.icc)

But ICC's can only be created at the moment, not read. This also doesn't include that it can read SPI (.spi1d), (.spi3d), (.cc), (.ccc), (.cdl)...

But yes this is a large oversight.

**Comment by pyalot** [comment]
In the case where you're referring an externally defined format such as icc etc. I don't think it needs documentation. But the formats that opencolorio itself defines, should be.

**Comment by dbr** [comment]
http://opencolorio.org/FAQ.html#what-lut-formats-are-supported

Although it would be good to expand that, mainly to provide short examples of what the files look like, and links to external documentation on the format

**Comment by scoopxyz** [comment]
Thanks for the correct link. I'm not certain if there is documentation on the spi1d/3d LUT formats, apart from the reference implementations in OpenColorIO-Configs?
