### ISSUE TITLE
Transform methods entirely undocumented

### ISSUE THREAD

**Issue by pyalot** [AcademySoftwareFoundation/OpenColorIO#425]
There's various transforms that can be configured in, they're all undocumented.

**Comment by scoopxyz** [comment]
http://opencolorio.org/developers/bindings/PythonTransforms.html

Is this not sufficient? Please point out specific cases for where documentation is lacking.

**Comment by pyalot** [comment]
It lists API calls, it does not list what values functions take, and what those mean.

**Comment by pyalot** [comment]
For example say a transform is listed as: - !<AllocationTransform> {allocation: uniform, vars: [0, 0.66]}. The configuration syntax documentation doesn't list what that does. The same goes for !<AllocationTransform> {allocation: lg2, vars: [-12.473931188, 12.526068812], direction: inverse} or !<FileTransform> {src: BT.1886_to_Linear.spi1d, interpolation: linear}. I can guess half of what they do, but it doesn't say so in the documentation. It also doesn't say where the difference is between interpolation methods like "best" or "linear". I guess best is a cubic spline, or something, again, not in the documentation.

**Comment by scoopxyz** [comment]
Allocation "documentation" exists here: http://opencolorio.org/configurations/allocation_vars.html

I agree they should be centralized, and logically organized. I cannot find documentation on the interpolation methods.

**Comment by pyalot** [comment]
I think that's what threw me off, I glanced at it, and could not find some logical listing of "you can use this directive with these options".

**Comment by dbr** [comment]
http://opencolorio.org/userguide/config_syntax.html#available-transforms
