### ISSUE TITLE
Python API is inconsistent and confusing (and in general the API is confusing)

### ISSUE THREAD

**Issue by pyalot** [AcademySoftwareFoundation/OpenColorIO#426]

**Comment by scoopxyz** [comment]
Again, specifics are helpful.

**Comment by pyalot** [comment]
For instance the config object has a getRoleName, but no getRole, instead, it has a setRole. Lots of those kinds of things around. Questions with that are: isn't the name of a role a property of a role? Why can you set a role, but not get one?
