### ISSUE TITLE
No way of adding a look to a processor

### ISSUE THREAD

**Issue by pyalot** [AcademySoftwareFoundation/OpenColorIO#439]
There is no way to set a look on a processor.

The config has these entry points capable to set looks:

- addLook
- clearLooks

The processor has this API with no entry points for looks:

- ctor/dtor
- isNoOp
- hasChannelCrosstalk
- getMetaData
- applyRGB
- applyRGBA
- getCpuCacheID
- getGpuShaderText
- getGpuShaderTextCacheID
- getGpuLut3D
- getGpuLut3DCacheID

The processor metada has this API with no entry point to set a look:

- ctor/dtor
- getFiles
- getLooks

A test program attempting to "add" a look to the config in the hopes that the processor uses it fails:

```python
import PyOpenColorIO as OCIO, cPickle

config = OCIO.GetCurrentConfig()
config = config.CreateFromFile('filmic/config.ocio').createEditableCopy()

def generate(look=None):
    #look = 'Base Contrast'
    
    colorspace = 'Filmic Log Encoding'
    display = config.getDefaultDisplay()
    assert display == 'sRGB / BT.709'
    config.setActiveDisplays(display)
    config.setActiveViews('Filmic Log Encoding Base')
    
    if look:
        look = config.getLook(look)
        config.addLook(look)

    processor = config.getProcessor('Linear', colorspace)
    print 'processor looks: ', processor.getMetadata().getLooks()
    gpuConfig = {
        'language'      : 'glsl_1.3',
        'lut3DEdgeLen'  : 16,
    }
    shader = processor.getGpuShaderText(gpuConfig)
    lut = processor.getGpuLut3D(gpuConfig)
    return cPickle.dumps({'shader':shader, 'lut':lut})
    
result1 = generate('Base Contrast')
result2 = generate()

print result1 == result2
```

The output of this script is:

> [OpenColorIO Info]: Color management disabled. (Specify the $OCIO environment variable to enable.)
> processor looks:  []
> processor looks:  []
> transforms equal:  True

As is evident, the processor does not pick up a look, and the results of both transforms are identical.

**Comment by dbr** [comment]
I think you need to construct a DisplayTransform or LookTransform to use a look, they aren't set directly on a processor

**Comment by pyalot** [comment]
Then getLooks of processor should not exit shouldn't it?
