### ISSUE TITLE
Python binding setRole, cannot unset role

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#448]
The documentation suggests that within `Config.setRole` for Python:
"setting the colorSpaceName name to a null string unsets it."

However, this appears to just set the role to a null string, and errors because there is no ColorSpace with the name `''`

**Comment by YashAgrawal0** [comment]
@scoopxyz 

Is this issue still open?

**Comment by doug-walker** [comment]
@YashAgrawal0, I would not recommend this one because @michdolan is currently upgrading the python bindings.  We should check once that is done if this is still a problem.

Looking at Config::setRole, it looks like the underlying C++ is correctly removing the role when the argument is empty.

**Comment by YashAgrawal0** [comment]
@michdolan  have you done upgrading the python bindings?

**Comment by YashAgrawal0** [comment]
> @michdolan have you done upgrading the python bindings?

Any updates @michdolan ?

**Comment by hodoulp** [comment]
@YashAgrawal0 Thanks to @michdolan, the Python bindings upgrade is currently in review #976 and should be merged soon (i.e. potentially this week). As mentioned by @doug-walker the `Config::setRole(const char * role, const char * colorSpaceName)` removes the `role` if `colorSpaceName` is null. Only the Python API call will need some test and a dedicated Python unit test if missing. 

For short-term, you need to wait for the Python Bindings merge.

**Comment by michdolan** [comment]
```
>>> import PyOpenColorIO as ocio
>>> config = ocio.Config()
>>> config.addColorSpace(ocio.ColorSpace(ocio.REFERENCE_SPACE_SCENE, "test"))

>>> config.setRole("my_role", "test")
>>> config.hasRole("my_role")
True
>>> list(config.getRoleNames())
['my_role']
>>> config.getColorSpace("my_role")
<PyOpenColorIO.ColorSpace object at 0x7fa22528e5b0>

>>> config.setRole("my_role", None)
>>> config.hasRole("my_role")
False
>>> list(config.getRoleNames())
[]
>>> config.getColorSpace("my_role")
None
```
This is working in the new Python bindings.
