### ISSUE TITLE
ociodisplay and/or ACES config related bug (banding/ precision issue)

### ISSUE THREAD

**Issue by KevinJW** [AcademySoftwareFoundation/OpenColorIO#456]
Using the stock ACES config and the following Nuke ramp
```
set cut_paste_input [stack 0]
version 10.0 v4
push $cut_paste_input
Ramp {
 p0 {0 0}
 p1 {{width-1} 0}
 color {0.1584472507 0.2402343601 0.3371581733 0.9999999404}
 color_panelDropped true
 name Ramp1
 selected true
 xpos 352
 ypos 43
}
```
saved out as an EXR

Add a new view:

    - !<View> {name: URD, colorspace: Utility - Rec.709 - Display}

Next open ociodisplay with the image, select an image colour space of ACEScg, and a the view transform 'URD'

![urd_direction_inverse](https://user-images.githubusercontent.com/1186170/28467078-95c8702c-6e26-11e7-9f35-86c9848ffce0.png)

The colour space is basically defined by a pair of 3x3 matrices and a 1D curve rec1886 (gamma 2.4) using the direction inverse:
```
    from_reference: !<GroupTransform>
      children:
        - !<MatrixTransform> {matrix: [0.952552, 0, 9.36786e-05, 0, 0.343966, 0.728166, -0.0721325, 0, 0, 0, 1.00883, 0, 0, 0, 0, 1]}
        - !<MatrixTransform> {matrix: [3.2096, -1.55743, -0.495805, 0, -0.970989, 1.88517, 0.0394894, 0, 0.0597193, -0.210104, 1.14312, 0, 0, 0, 0, 1]}
        - !<FileTransform> {src: rec1886_to_linear.spi1d, interpolation: linear, direction: inverse}
```

 If instead we directly calculate the inverse function and use that to define a new colourspace:
```
   from_reference: !<GroupTransform>
      children:
        - !<MatrixTransform> {matrix: [0.952552, 0, 9.36786e-05, 0, 0.343966, 0.728166, -0.0721325, 0, 0, 0, 1.00883, 0, 0, 0, 0, 1]}
        - !<MatrixTransform> {matrix: [3.2096, -1.55743, -0.495805, 0, -0.970989, 1.88517, 0.0394894, 0, 0.0597193, -0.210104, 1.14312, 0, 0, 0, 0, 1]}
        - !<FileTransform> {src: invgamma24.spi1d, interpolation: linear}
```
![urd_inverse_function](https://user-images.githubusercontent.com/1186170/28467079-95cadcea-6e26-11e7-8c34-3cb464f2d31e.png)

Having a quick glance at the code I guess this is a problem due to the precision for the 3D cube lookups in the GPU path, this is also seen in other 3rd party apps e.g. RV. The CPU path as tested in Nuke doesn't show the same issue.

**Comment by Nick-Shaw** [comment]
I can replicate the same effect in the OCIO plugin for After Effects.
[OCIO_GPU_test.zip](https://github.com/imageworks/OpenColorIO/files/1191676/OCIO_GPU_test.zip)
With GPU mode enabled, the buffer returned to the app appears to be 8-bit. While this may not be a major issue for display targeted transforms (although higher bit depth would be preferable to allow the possibility of dithering) it seems that perhaps a truncation to 8-bit is happening too early in the pipe.

**Comment by mjmvisser** [comment]
Sounds like #394 - which IIRC [is caused by the GPU path folding all LUTs into a single 3D LUT](https://groups.google.com/d/msg/ocio-dev/hcI5Fxc04Ko/wWe6HgrtEwAJ).

**Comment by devernay** [comment]
Same issue in Natron, where the GPU is used to apply transforms not only for display, but also in the whole compositing graph
[OCIO_GPU_bug.ntp.zip](https://github.com/imageworks/OpenColorIO/files/1766991/OCIO_GPU_bug.ntp.zip) (Natron 2.3.6 project)

**Comment by KevinJW** [comment]
I believe this was fixed in several ways:

ACES configs were switched to define the transform as suggested.
OCIO v2 implements these with built ins
OCIO v2 GPU path implements these analytically.

OpenRV/RV does not yet use the full analytical path but that is planned.
