### ISSUE TITLE
Add DX11 support

### ISSUE THREAD

**Issue by hodoulp** [AcademySoftwareFoundation/OpenColorIO#525]
The library currently supports OpenGL, OpenGL Core profile, and Cg.
It would be great to add the Dx11 support (i.e. Maya needs it).

**Comment by mundane140** [comment]
How to start with this one?

**Comment by hodoulp** [comment]
Hi @mundane140 ,

The best way to start the task is to implement a GPU unit test framework using Dx11 (with the existing OpenGL unit test framework as example). With the recent work done on `master` the HLSL support is now in without having anyway to test it.

Refer to #526.

**Comment by hodoulp** [comment]
Closing the defect as the HLSL support is now in.
