### ISSUE TITLE
Better documentation for default roles and what they mean

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#533]
The C++ API documentation for roles like ROLE_REFERENCE is currently only "reference",

https://github.com/imageworks/OpenColorIO/blob/f35a8ef0ac01c74b616ab0be3902155cc671f95d/export/OpenColorIO/OpenColorTypes.h#L357

Should make this a little more verbose (probably also make sure the Python binding docstrings include this too)

They are documented more completely in the config syntax section:
http://opencolorio.org/userguide/config_syntax.html#roles

This has been misinterpreted in the official ACES OCIO config, which specifies "reference: Utility - Raw"
https://github.com/imageworks/OpenColorIO-Configs/blob/0bb079c08be410030669cbf5f19ff869b88af953/aces_1.0.3/config.ocio#L17
..which makes sense as "colorspace for reference imagery" (whereas it is should be colorspace which `to_reference`/`from_reference` are defined relative to - i.e in the ACES space would be `ACES2065-1`)

**Comment by zachlewis** [comment]
Some miscellaneous related thoughts:
- Perhaps it's time to add "rendering" and "compositing_linear" role constants...?
- Maybe deprecate the"reference" role in future versions -- 
  - "reference" and "data" can be determined implicitly in v1 as it is... 
  - ...and OCIO v2 can define new "scene linear rgb reference" and "output device encoding reference"
- Maybe worth thinking about a schema for roles? Not exactly sure what that would look like, but there needs to be a standardized way for software vendors to declare which roles they're using, and how; or what the default alternative is, if not defined...
