### ISSUE TITLE
ociocheck doesn't fully validate views/looks?

### ISSUE THREAD

**Issue by KevinJW** [AcademySoftwareFoundation/OpenColorIO#572]
Adding this whilst I remember...

I have not looked into the cause but I sometimes run into errors when using configs that use looks on views, where the file name in a file transform used in the look has a typo. I guess that ociocheck doesn't actually validate the looks/views?

It would be nice if ociocheck could validate that the view can be used (or not), in this case that the FileTransform does refer to a file that actually exists (assuming I'm not using context variables obviously).

Kevin

**Comment by YashAgrawal0** [comment]
@KevinJW , @hodoulp  

I would like to work on this issue. can you help me how do I get started?

**Comment by KevinJW** [comment]
So as an example, I think when we run ociocheck against this file, it should complain that the look refers to a file transform that does not exist.


[ocio_check_look_config.ocio.txt](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/4274975/ocio_check_look_config.ocio.txt)

**Comment by YashAgrawal0** [comment]
@KevinJW Can you eleaborate a bit more as I am new to OCIO, I've installed OCIO as per the instructions given in 
`https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/docs/installation.rst`.

Now what do I need to do to tackle this issue?

**Comment by KevinJW** [comment]
so if you have a working build then you should have a tool called ociocheck, the first step would be to run the file I attached through ociocheck. There are a number of ways to do this but the simplest would be to pass the file in using the --iconfig <file> option.

The goal is to make this actually fail for the right reason, which is that there is no file called "file_that_does_not_exist.spimtx".

You will need to add some code roughly here - https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/apps/ociocheck/main.cpp#L211

You could setup a processor to convert apply each look and see if it errors. Obviously ideally we'd like a test that would detect this failure that ran automatically during the execution of the test suite, but that would be further down the line.

Next you might want to look at the definitions of the displays and views and also figure out how to iterate across them and try instance each of those as well.

There is code showing how to create DisplayTransform objects in the ociodisplay tool directory, which might be useful.

Kevin

**Comment by YashAgrawal0** [comment]
@KevinJW  Thanks for the update.


Currently I am getting the output for  ` ociocheck --iconfig ocio_check_look_config.ocio.txt `
which is shown in the [image](https://user-images.githubusercontent.com/24262584/76015762-b3aa0b00-5f41-11ea-8c4c-06a0ca73d7c5.png).
 

In the output I am getting this error in Sanity Check :

> The list of active displays [P3, Rec709] from the config file is invalid.

Can you help me with this?

**Comment by KevinJW** [comment]
Oops, that is my error, you should edit the line containing the
active_displays list and rewrite it to only contain display1 and remove the
P3 and Rec709 references.

But now at least you have a working binary :-)

Kevin

**Comment by YashAgrawal0** [comment]
@KevinJW , Please review the Pull Request.

Thanks,
Yash

**Comment by YashAgrawal0** [comment]
@KevinJW  I messed up in the previous PR as I was solving other issues which also get included in that PR so I've closed that PR.

Please review this new Pull Request and now ociocheck throws an error if the file is not present which is defined in the FileTransform.

The Error thrown is shown in the [image](https://user-images.githubusercontent.com/24262584/76139532-c7a35900-6076-11ea-8627-24ecd5f5dfb5.png)


Thanks
Yash
