### ISSUE TITLE
ocioconvert freezes at the end of conversion on windows

### ISSUE THREAD

**Issue by maximd** [AcademySoftwareFoundation/OpenColorIO#585]
Hi,

We are converting jpg and png files from srgb to acescg on windows and, for an unknown reason, the `ocioconvert` process never ends and we have to kill the process via the task manager.

The build used is https://github.com/imageworks/OpenColorIO/releases/tag/v1.1.0

Is it something that can be reproduced on your side (we face the problem on all computers here)?

**Comment by hodoulp** [comment]
Unfortunately, I also have that problem on Windows between OCIO and OIIO. Last time I did some investigations it was blocking around an OIIO mutex. As OCIO could not use the latest OIIO version (i.e. OCIO v1.1 is still C++98), I did not put much more effort.

Perhaps, you can use OIIO (compiled with OCIO support) makeTx or oiiotool tools?

**Comment by hodoulp** [comment]
To be tested again as master is now C++11 like OIIO.

**Comment by hodoulp** [comment]
Fixed in `master`.
