### ISSUE TITLE
missing apps

### ISSUE THREAD

**Issue by Shaunimsorry** [AcademySoftwareFoundation/OpenColorIO#594]
installed via homebrew im missing 3 out of the 5 tools only have bakelut and ociocheck
any way to fix this ?

**Comment by Shaunimsorry** [comment]
trying to convert linear exrs to alexa seems like a hyper difficult task unless my installation was bad ?

**Comment by michdolan** [comment]
There's currently  a circular dependency between OCIO and OIIO (OpenImageIO). Quite a few solutions been discussed, but for now, you'll need to use the following steps to build OCIO with all apps on Mac OSX:

**OpenColorIO**
brew install -vd opencolorio --with-python
**Update the homebrew repository of install scripts to make sure that OpenImageIO is included.**
brew tap homebrew/science
**Optional Dependencies for OpenImageIO**
brew install -vd libRaw
brew install -vd OpenCV
**OpenImageIO**
brew install -vd openimageio --with-python
**CTL**
brew install -vd CTL
**OpenColorIO, a second time. ociolutimage will build with openimageio installed.**
brew uninstall -vd opencolorio
brew install -vd opencolorio --with-python

**Comment by michdolan** [comment]
Here is the related ocio-dev discussion thread:
https://groups.google.com/forum/#!topic/ocio-dev/yoMB7Dl6xQ8

**Comment by Shaunimsorry** [comment]
Thanks for that Michael 
I’ll make a note I sent another question that I’ll
Copy you into im having a hard time with the pythonic mappings and getting my head around them 

Will reply to this with those questions shortly 
Resorting to the using os.system but is id to have it all in python

**Comment by michdolan** [comment]
I should clarify too that the **CTL** step above is only needed if you're going to be building an ACES OCIO config from the build scripts in OpenColorIO-Configs.

**Comment by Shaunimsorry** [comment]
This was the question

Trying to just do stuff under one tool
However if you guys recommend I have python call on the system I can do that too

**Comment by vvzen** [comment]
I tried what @michdolan suggested, but didn't work - none of the apps were compiled.
macOS 10.12.
Also, the install option `--with-python` doesn't seem to be working anymore.
Anybody has got any hints on how to get all the apps on mac?
Does compiling from the repo work?

**Comment by erichorwitz** [comment]
bump^^

I am encountering the same issue. --with-python is an invalid option.

**Comment by imusaba** [comment]
Hello gentlemen, hopefully there is a chance to warm this thread up. I run into the same issue. After following the instructions from @michdolan, ociolutimage is not available. Also the google discussion didn't help.
Homebrew refused to install opencolorio and openimageio with python - could this be a problem?
To uninstall opencolorio in the last step I needed to add --ignore-dependencies. 
Best

**Comment by doug-walker** [comment]
So much has changed since the advice above was provided in 2018 that I would recommend people first check the installation section of the current documentation and then, if there are still problems, ask in the #helpdesk channel on the OCIO Slack instance for advice.  Build advice depends on platform and other variables.  Closing this issue as it is more misleading than helpful at this point.
