### ISSUE TITLE
After the compilation, the unit test helper files are in two directories

### ISSUE THREAD

**Issue by hodoulp** [AcademySoftwareFoundation/OpenColorIO#608]
All the helper files used for the unit tests are now in:

- [project]/build_rls/testdata/build
- [project]/build_rls/testdata/dist

As these files should never be distributed, the second copy is useless.

**Comment by YashAgrawal0** [comment]
I'd like to work on this issue, help me get started?

**Comment by hodoulp** [comment]
That's not anymore a problem. All files are now only in the directory `[project]/build_rls/testdata`
