### ISSUE TITLE
Coding Style - Folders and files names for source code

### ISSUE THREAD

**Issue by BernardLefebvre** [AcademySoftwareFoundation/OpenColorIO#613]
Before the restructuring files names were camel case and folder names were lower case. Now there is no consistency for folder names.
src/OpenColorIO
src/OpenColorIO/ops/Allocation
src/OpenColorIO/ops/Exponent
...
I suggest using lower case folder names.

**Comment by hodoulp** [comment]
My suggestion would be to 'lower case' all the directory names to have consistency across the project.

**Comment by michdolan** [comment]
It seems like the `ops` subdirs are the casing exception (other than OpenColorIO, which I find a reasonable exception to a rule). I wonder if these subdirs are needed at all though. Under `transforms`, there are no subdirs, and there are a couple header files in there. Perhaps all op source/header files could live directly under `ops`.

**Comment by michdolan** [comment]
Good point about expansion of op file count. Makes sense to keep subdirs then.
