### ISSUE TITLE
Choosing fast or exact Lut3D inversion

### ISSUE THREAD

**Issue by BernardLefebvre** [AcademySoftwareFoundation/OpenColorIO#621]
An upcoming PR will add the ability to evaluate a Lut3DOp in the inverse direction.  There are two methods supported: a slow but exact method and a fast but approximate method.  This issue is to discuss how one may specify which method to use.  This is a question both at the config level and the API level.

One option would be to use the interpolation tag (e.g. set to "best" for exact), but this is already used to indicate the method of forward interpolation, so it is essentially a different thing.  The upcoming PR will always provide the inverse for a tetrahedral forward eval, but in principle a trilinear inverse could also be provided and so the interpolation tag could specify which to use.

The proposal is to add an optional "inversion" attribute at the Transform level that may be set to "best" or "fast".

At the API level, the proposal is to add a setInversionQuality method to the Processor class that would have an enum for best, fast, and default styles.  If there is interest, we could also go farther and provide a range of quality levels.  (These would be implemented by adjusting the size of the forward Lut3D that is used for the fast method.)

In the upcoming PR, the exact method is not supported on the GPU so for now the quality level will only be meaningful for the CPU.

**Comment by michdolan** [comment]
Would you carry the inversion quality enum all the way to the Lut3DOpData interface (replacing the InvStyle enum in #625 ), or were you thinking this would just be for the higher level interface? IMO setInversionQuality communicates its effects more clearly than setInvStyle. Even without knowing the possible enum values, the method's use is clear.

**Comment by doug-walker** [comment]
Yes, good point Michael, the setInvStyle method name is not very clear.  We should use the setInversionQuality name consistently.

**Comment by doug-walker** [comment]
The group discussed this during the v2 working group meeting today and decided that no control over inversion method/style will be provided at the config level at this time.  Also, the group decided there was no need to allow specifying a range of fast inversion style quality levels at this time.

As a side note, the group agreed that the fast style should be the default since that is the only method supported on both CPU and GPU.

We will submit a PR for the remaining part of the issue: adding the setInversionQuality method to the public API as a way for apps to have access to the exact style.

**Comment by KevinJW** [comment]
I think it was implicit in our discussion that the exact method should be
available within OCIO baking tools.

Kevin

**Comment by doug-walker** [comment]
This has now been implemented.  After further discussion, we decided to make control over fast vs. exact one of the OptimizationFlags, see OPTIMIZATION_LUT_INV_FAST in OpenColorTypes.h.
