### ISSUE TITLE
Update CONTRIBUTING.md with CLA requirements

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#659]
Given the updated CLA we should outline explicitly when/how one fills out and submits the CLA within the CONTRIBUTING.md doc.

**Comment by lgritz** [comment]
Good catch. Also will need to say the exact thing we need to do to refer to the DCO (each PR needs the commit to have had a "Signed-off-by: " tag naming somebody in the org who is authorized to make submissions.

**Comment by rashil2000** [comment]
@hodoulp @hodoulp Shouldn't this issue be closed given that this stuff has been implemented already?
