### ISSUE TITLE
Website is using GitHub ssl cert

### ISSUE THREAD

**Issue by s7726** [AcademySoftwareFoundation/OpenColorIO#669]
Need to obtain or update the certificate used for the opencolorio.org website

**Comment by jfpanisset** [comment]
GitHub Pages web sites can be set up to automatically generate and renew letsencrypt.org SSL certs. As per:

https://help.github.com/en/articles/setting-up-an-apex-domain

If you're updating an existing custom domain, first remove and then
re-add your custom domain to your GitHub account to trigger the
process of enabling HTTPS.

Also DNS A records for the opencolorio.org domain should be updated to:

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

and you can use a CNAME record to point www.opencolorio.org to opencolorio.org

That should be sufficient (after an hour or two) to get opencolorio.org to default to / redirect to HTTPS and present a valid SSL certificate.

**Comment by doug-walker** [comment]
It looks like this was fixed after opencolorio.org was migrated to the Linux Foundation. Looking at the certificate reported by browsers by clicking the lock next to the address shows the certificate is being updated regularly.
