### ISSUE TITLE
OCIO_ACTIVE_VIEWS does not filter view list

### ISSUE THREAD

**Issue by jeremyselan** [AcademySoftwareFoundation/OpenColorIO#67]
The ACTIVE_DISPLAYS envvar is used to both filter, and prioritize, the list of allowed displays. The ACTIVE_VIEWS envvars is only used for prioritization. Make it do both.

**Comment by doug-walker** [comment]
This was fixed in PR #875.  In OCIO 2.x, the Config getViews method only returns active views.
