### ISSUE TITLE
Add support for Autodesk CTF file format

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#676]
The Color Transform Format (CTF) is the native LUT format for Autodesk products including Maya, Flame, and Lustre.  

This format is a superset of the Academy/ASC Common LUT Format (CLF).  The extensions to CLF that comprise the CTF format were added primarily for two purposes:

1)  To provide more accurate color processing by avoiding the need to represent certain functions as LUTs.  This is particularly useful for providing compact and accurate ACES Output Transform implementations.

2)  To allow any OCIO operators to be serialized losslessly to a text-based (XML) format.  (CTF is the only format we're aware of that allows this.)

Adding CTF support would be useful for users whose workflows interact with Autodesk applications.  It is potentially also useful for scenarios that would require losslessly serializing an OCIO processor into an XML format.  For example, when debugging or when implementing cloud services.

**Comment by hodoulp** [comment]
@doug-walker being part of the ACES CLF WG, he proposed some ops/capabilities he designed for the Autodesk CTF format, be considered for the ACES CLF format.

**Comment by doug-walker** [comment]
Closing as this has now essentially been implemented.  There are a few edge cases of Autodesk CTFs that may not load, but those would be better tracked as separate issues.
