### ISSUE TITLE
About Container Image on Docker Hub

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO#716]
Hi,

As mentioned on Slack and given the problems described in #709, I was wondering if we should not have working container images on [Docker Hub](https://hub.docker.com/), along with continuous integration for the Dockerfile themselves.

We would also need to provide some wrappers for them to be fully useful but it should not be too hard.

Cheers,

Thomas

**Comment by michdolan** [comment]
Here is some interesting movement related to this:
https://github.com/AcademySoftwareFoundation/aswf-docker

In particular the ci-ocio image may be of interest (which we are using for Linux CI now. and will have a tag per VFX reference platform year). This image does not contain OCIO, but does contain a complete environment for building OCIO, including OIIO, etc.

This is the staging area for new image builds:
https://hub.docker.com/r/aswfstaging/ci-ocio/tags

They will eventually land here:
https://hub.docker.com/u/aswf

We've also recently built out our own ci scripts directory for building any other images we may need down the road: https://github.com/imageworks/OpenColorIO/tree/master/share/ci . There's an example Dockerfile in there that I was initially using for testing.

Hopefully these can lay the foundation for further work.
