### ISSUE TITLE
Enabling improved display transforms

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#741]
The DisplayTransform includes the ability to adjust the exposure and contrast to allow the user to interactively explore the full dynamic range of their images.  While the current design is fine for simple apps such as ociodisplay, it is not very efficient.  (And after all, real-world apps would typically like to have most of the compute resources available for tasks beyond color management.)

The DisplayTransform performance is not ideal since each change to the exposure or contrast requires the following steps (GPU case):
1) Create a new linearcc and displaycc and set on a DisplayTransform.
2) Create a Processor from the transform (which creates and finalizes the ops)
3) Generate a shader program
4) Compile the shader program and upload to the GPU
5) Apply the new shader to the image

For interactive adjustment of the controls, this needs to be done multiple times per second.

Steps 1-4 are wasteful and may be incompatible with typical real-time application design. They would be unnecessary with the proposed enhancement.

This issue proposes to add the concept of a "dynamic property" which is a parameter that may be modified even after the Processor has been built and finalized.  For example, this would allow a transform to provide exposure and contrast controls that applications could modify without requiring repeating the above steps 1-4.

For the GPU, these dynamic properties would be implemented as GLSL uniforms.  Applications may modify uniforms while continuing to use the original shader program.

This would allow real-world applications to implement interactive viewport adjustments such as exposure and contrast within OCIO rather than needing to implement them externally to OCIO.  Allowing it to be done in OCIO is preferable since it ensures the correct math will be used, the controls will be applied at the appropriate point in the viewing pipeline, and it will help encourage more uniform behavior among applications.

As part of this issue we also propose to implement an ExposureContrastTransform that would use the proposed new dynamic properties and allow the same type of controls provided in ociodisplay (in ociodisplay, these are named exposure and gamma and are adjustable using the arrow keys along with a modifier key).

Each dynamic property is similar to other parameters in that it has an initial value when the transform is created and finalized.  These are the values that would be used when interactive control is not happening (e.g. in ocioconvert).

**Comment by michdolan** [comment]
Having uniform support will be awesome! Very excited about this.

Sorry if this was discussed in the working group meeting, but regarding the new ExposureContrastTransform, would the "contrast" portion of the transform by the typical exponent adjustment (i.e. "gamma"), or are you planning something fancier? I'm curious about the naming choice of contrast vs. gamma.

And regarding the inclusion of both exposure and gamma in a single transform (if I'm interpreting your description correctly); in the current "cononical" display transform implementation (as it's described in the code), exposure is applied in the LinearCC, and gamma in the DisplayCC. The rest of the DisplayTransform's ops are applied in-between. Would this transform follow that behavior? I was wondering how the injection of the other ops would work into the middle of a single transform.

Just curious questions without seeing the implementation.

**Comment by doug-walker** [comment]
Great questions Michael.  The goal is to be able to emulate what DisplayTransform does -- an exposure in scene-linear space, and a gamma in display space.  So the way it would work is there would be one ExposureContrastTransform before the view/display transform and another one after.  The first one would respond to dynamic exposure, the second one to dynamic gamma.  In addition, we've found it useful to have the option of having a third control which is a contrast that happens at the same place in the pipeline as exposure that allows simulating a "log view".  Mathematically, the gamma and contrast controls are the same but they are separate dynamic parameters ("Exposure", "Contrast", and "Gamma") so that a single Processor could respond to all three (if desired).  The pivot point of the contrast/gamma is also settable on the transform.  As to the naming, we thought that ExposureContrastGammaTransform was perhaps too long and not really adding anything and we were worried about ExposureGammaTransform possibly being misinterpreted.  Bernard is preparing a PR, should be up later today!

**Comment by michdolan** [comment]
That explanation makes total sense. Thanks! Given that info, I think ExposureContrastTransform makes sense as well.

**Comment by michdolan** [comment]
Thinking on this more. I think there would be great value in adding dynamic parameter support for some other transforms as well. CDLTransform in particular would be useful, since it is often used for "real time" adjustments in reviews.
