### ISSUE TITLE
[v1.1.1] Compilation with -Wall fails in PyAllocationTransform.cpp

### ISSUE THREAD

**Issue by sobotka** [AcademySoftwareFoundation/OpenColorIO#745]
Compilation fails with GCC 8.2.0+ with:
```
OpenColorIO/src/pyglue/PyAllocationTransform.cpp:56:20: error: ‘PyObject* OpenColorIO::v1::{anonymous}::PyOCIO_AllocationTransform_equals(PyObject*, PyObject*)’ declared ‘static’ but never defined [-Werror=unused-function]
         PyObject * PyOCIO_AllocationTransform_equals(PyObject * self,  PyObject * args);
```

https://github.com/imageworks/OpenColorIO/blob/ebdec4111f449bea995d01ecd9693b7e704498fe/src/pyglue/PyAllocationTransform.cpp#L56

**Comment by matthewdcong** [comment]
I think this issue was addressed in https://github.com/imageworks/OpenColorIO/commit/1c624651b7ef414353c8ab790595b1db89f59616 and can be closed. I am no longer encountering the warning in GCC 9.
