### ISSUE TITLE
[v1.1.1] Compilation with -Wall fails with -Werror=deprecated-declarations

### ISSUE THREAD

**Issue by sobotka** [AcademySoftwareFoundation/OpenColorIO#746]
With GCC 8.2.0+ there are many failures in the tag v1.1.1 branch. Adding `-Wno-error=deprecated-declarations` appears to squelch and solve.

**Comment by YashAgrawal0** [comment]
@sobotka I'd like to contribute to this issue. Can you help me how do I get started with this?

**Comment by sobotka** [comment]
I believe it would involve adjusting the `cmake` in a non-invasive manner. Then test across platforms to make sure the change doesn’t break some combination?

**Comment by YashAgrawal0** [comment]
Can you elaborate a bit more as I am new to OCIO community. 

How do I make changes in cmake for this and test it across different platforms?
