### ISSUE TITLE
[v1.1.1] Compilation with -Wall fails with -Werror=cast-function-type

### ISSUE THREAD

**Issue by sobotka** [AcademySoftwareFoundation/OpenColorIO#747]
Compilation in the tag v1.1.1 branch with GCC 8.2.0+ fails with -Werror=cast-function-type.

**Comment by hodoulp** [comment]
Based on investigations done by @matthewdcong for #838, these warnings should be gone.
@sobotka Could validate the point and close the issue?

**Comment by sobotka** [comment]
Looks like `RB-1.1` needs the C11 flags set on a clean compile. It errors our with extensive output, first being:
```
/src/apps/ocioconvert/main.cpp:36:
/usr/include/c++/8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

**Comment by hodoulp** [comment]
`RB-1.1` is not C++11, and the error (line 36 of `[]/src/apps/ocioconvert/main.cpp`) is related to an OIIO header file. So, the warnings could only be related to the OIIO version you are using. The OIIO library already transitioned to C++11 or higher long-time ago which could explain the warnings.

Anyway that does not seem to be an OCIO issue if `line 36` is the only trigger of all the warnings.

**Comment by sobotka** [comment]
Not sure. I tried a clean compile after a clean clone of the repository, and flipping to the `RB-1.1` branch. Compiled OCIO for years, and can't recall this issue.

The YAML now simply triggers a warning, but the rest of the compilation bombs out with `gcc (Debian 8.3.0-6)`.

**Comment by sobotka** [comment]
OIIO is master. Is there a means to negotiate the conflict?

OCIO seems to have nerfed the original error, but hard to be certain it compiles cleanly.

**Comment by hodoulp** [comment]
> OIIO is master. Is there a means to negotiate the conflict?

Yes. Even if OCIOv1 is not C++11, you could compile it (apps only or apps & core) with the C++11 flag (i.e. add `set(CMAKE_CXX_STANDARD 11)` to the appropriate `CMakeLists.txt`). I would personally limit the change to the apps in order to avoid other potential warnings from the core library.

**Comment by sobotka** [comment]
So I've added that C++11 setting to three apps and it compiles RB-1.1, which dovetails into meaning that this issue is also closed due to the warnings as errors.

**Comment by michdolan** [comment]
Can this be closed?

**Comment by sobotka** [comment]
Sincere apologies for the delay here peeps. Compiling on Debian Buster on a fresh clone compiles perfectly 100%, no errors.

Huge thanks and tremendous effort.

**Comment by michdolan** [comment]
Thanks @sobotka !
