### ISSUE TITLE
mingw compilation failures.

### ISSUE THREAD

**Issue by hodoulp** [AcademySoftwareFoundation/OpenColorIO#787]
@Alexpux faced some compilation issues when compiling with mingw.
The master pull request is #786 

He raised the point to back-port the changes to RB-1.1

**Comment by Alexpux** [comment]
@hodoulp there are more patches needed for 1.1. See - https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-opencolorio

**Comment by hodoulp** [comment]
The changes are also valid ones for the RB-1.1 branch.

However, the define order to declare `OCIOEXPORT` & `OCIOHIDDEN` are slightly changed in the new `include/OpenColorIO/OpenColorABI.h.in` file (which is part of the OCIO public API). It should not have any impacts on the C++ ABI compatibility.

If accepted, I would suggest to move to the next release version to 1.2 (instead of 1.1.2) to highlight the backward compatible change so that devs could adjust their code if they developed a workaround.

Any comments/suggestions?

**Comment by hodoulp** [comment]
@Alexpux From your patch list:
* 1, 5, 6, 7 & 8  are already in PR #786 
* 2, 3, & 4 are not clear for me (i.e. back-port or not)

The goal of RB-1.1 is only to fix bugs, and not to add new things (i.e. new compiler or platform support for example). At least that's my understanding of the branch.

**Comment by Alexpux** [comment]
@hodoulp 
Patch 002:
- mingw not sippor fPIC flag
- fix between MSVC/MINGW
- install OpenColorIO.cmake and *-target.cmake int right location to be able find by cmake from other modules.  Right location is PREFIX/lib/cmake/OpenColorIO

Patch 003 - mingw alreaady have right strtok_r function

Patch 004 - Fix conditions in cmake that only for MSVC compiler

**Comment by Alexpux** [comment]
There are no any new things

**Comment by hodoulp** [comment]
Hi @Alexpux

> The TSC welcomes any contribution to increase the platform/compiler support for the OCIO v1 release if it has no impact of the public API (and the C++ ABI compatibility) and knowing that the TSC does not commit itself to maintain to the new platform/compiler. The same rule also applies to the master branch i.e. OCIOv2.

So you can create a pull request for a better support of `mingw` in RB-1.1.
