### ISSUE TITLE
Support versioned docs on opencolorio.org

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#790]
At the last TSC meeting ( #788 ) we discussed the License page of opencolorio.org being out of date (since it is tracking the RB-1.1 branch vs. master). Ideally the site would support choosing a release version and update the GH-sourced docs accordingly. This would aid in helping users learn about new functionality available in the OCIO v2 work, while also maintaining docs for current releases. 

Perhaps something like this: https://www.colour-science.org/api-reference/
Or the RTD version dropdown approach.

**Comment by rashil2000** [comment]
Can this issue be closed in lieu of #512?

**Comment by doug-walker** [comment]
Closing as the OCIO ReadTheDocs site now does allow choosing the version.
