### ISSUE TITLE
Minimum gcc version/code license query

### ISSUE THREAD

**Issue by KevinJW** [AcademySoftwareFoundation/OpenColorIO#804]
Whilst looking at one of the pull requests I noticed the following code : https://github.com/imageworks/OpenColorIO/blob/e8a0513a661ef570097a35d66f66d05c0378b789/src/OpenColorIO/SSE.h#L48

It begs two (real) questions:

1) What is the minimum gcc version we should support in v2

2) Are there any license implications from the "Copy & Paste"

3) is the code from 4.1.2 or 4.1.1 :-)

Kevin

**Comment by KelSolaar** [comment]
The VFX Reference Platform recommends 6.3.1 for 2018, 19 and 20 with some notes: https://vfxplatform.com/#footnote-gcc6

**Comment by hodoulp** [comment]
Good catch @KevinJW , these lines could be removed.
