### ISSUE TITLE
Nuke nodes should have better support for roles

### ISSUE THREAD

**Issue by mike1158** [AcademySoftwareFoundation/OpenColorIO#818]
As far as I can tell, there is currently no way to specify a role in the OCIODisplay or OCIOColorSpace nodes.

The utility of being able to do this is clear--the OCIOLogConvert node is effectively just the OCIOColorSpace node that uses the compositing_log and scene_linear roles.

It would be nice to be able to use other, user-specified, roles in Nuke....

**Comment by michdolan** [comment]
I believe support for roles is coming in Nuke 12, which is still in beta (using Foundry's version of the OCIO plugins, which differ from those in this repo).

**Comment by michdolan** [comment]
Confirmed in Nuke 12 (toward the bottom of feature list):

https://www.foundry.com/products/nuke/new-releases#link1013
