### ISSUE TITLE
Update Compatible Software list

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#819]
This page is quite out of date: https://opencolorio.org/CompatibleSoftware.html

Some integrations:

- have been overhauled by vendors: Mari, Nuke, etc. 
- have been assimilated: Hiero.
- are not included yet: Maya, Houdini, Clarisse, Unreal Engine, DJV, etc.

**Comment by YashAgrawal0** [comment]
@michdolan I am taking this issue. Can you tell me how do I get started?

**Comment by michdolan** [comment]
This page is intended to outline all software, libraries and DCCs (digital content creation applications), which support OpenColorIO. This includes commercial and open source products/projects. There are quite a few new DCCs in particular that are not reflected on this list (some of which I outlined in my initial comment, but that list is not exhaustive. Substance Designer now supports OCIO for example).

Each entry in the compatible software page should mention where it is supported (with links), and provide some indication for **how** it is supported, similar to the existing entries. Some Google searching should be able help fill in the gaps, but you could also poll the ocio-dev mail list to collect some of this info. Many of the supporting software packages/projects have representatives in this list.

Here is the actual source file you would need to update:
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/docs/CompatibleSoftware.rst

Thanks for your interest in contributing!

**Comment by michdolan** [comment]
Also, to clarify:

> have been overhauled by vendors: Mari, Nuke, etc.
Software that is already listed, but whose integration has matured since this document was written (so is out of date in its explanation)

> have been assimilated: Hiero.
Software that has moved/changed. Hiero is now a part of Nuke Studio, for example.

> are not included yet: Maya, Houdini, Clarisse, Unreal Engine, DJV, etc.
New integrations since this document was written. There are lots of these.

**Comment by YashAgrawal0** [comment]
@michdolan Thanks for the reply. I've posted in the ocio-dev mail list to collect info.
 
Shall I remove the softwares that are overhauled or assimilated?

**Comment by michdolan** [comment]
Thanks @YashAgrawal0 . Perhaps they could just be moved into a deprecated section toward the bottom of the document.

**Comment by dbr** [comment]
This list seems like it would be more practical using the GH wiki system or similar? Could be linked to from the compatible software page of course, makes it easier to edit, and more importantly is not versioned with the code itself (good thing for API docs etc, not good for documenting third-party things like this)

**Comment by YashAgrawal0** [comment]
@michdolan , @hodoulp , @lgritz 

Sorry for messing up the previous Pull Request But now I've closed that PR and created a new pull request with all the changes sugeested. 

Please review it.


Thanks 
Yash
