### ISSUE TITLE
OCIO 1.1.2 cherry-pick list

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#858]
Let's keep a list of all PRs to master that need to be cherry-picked into RB-1.1 for the upcoming 1.1.2 release. This way we won't forget these when the PRs get merged.

#856

**Comment by hodoulp** [comment]
Here are new candidates for OCIOv1: #854 #855

***Note*** that most of the time the `git cherry-pick` fails because of the directory structure differences. So it could end up to be a copy & paste requiring more attention.

**Comment by michdolan** [comment]
#540 - Add ability to write Iridas cubes
