### ISSUE TITLE
Creating ICC profiles using the python bindings

### ISSUE THREAD

**Issue by vvzen** [AcademySoftwareFoundation/OpenColorIO#897]
Hi,
I'm using OCIO for my studio libraries and I haven't been able to find a via to create ICC profiles using the python bindings.
I've been using the `PyOpenColorIO.Baker` class to bake LUTs, but I'm still subprocessing to `ociobakelut` cli whenever ICC profile generation is needed.
Is there a way to create icc from the bindings, instead of subshelling?

Thanks!

**Comment by michdolan** [comment]
You can shell out to ociobakelut with subprocess, and wrap that up with a Python function as a workaround. ICC write support is currently exclusive to ociobakelut, and does not use Baker internally. 

OCIO v2 (master branch development) adds ICC support to FileTransform, but currently for read only.
