### ISSUE TITLE
Metal support

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#907]
Add Metal (or another macOS-supported GPU rendering interface) support to accomodate future effects of Apple OpenGL deprecation.

**Comment by Dithermaster** [comment]
I'll be adding our OpenCL kernel generation to OCIOv2 when it's ready. They might be a good starting point for Metal kernel generation. We wrote them for OCIOv1 but only locally.

**Comment by hodoulp** [comment]
The MSL (Metal Shading Language) is a work-in-progress thanks to Apple support. A first step is already merged in `main`. Refer to #1520

**Comment by Dithermaster** [comment]
I understand this is about kernel generation and so probably Metal APIs are not called. However, if they are, or for hosts that are interested, Apple just released Official C++ bindings for Metal! https://developer.apple.com/metal/cpp/

**Comment by hodoulp** [comment]
Thanks @Dithermaster for the hint but OCIO MSL translation (as well as all the other translations) remains independent from any GPU related APIs or libraries.

**Comment by doug-walker** [comment]
This work was merged in PR #1520 and PR #1538.  Closing as fixed.
