### ISSUE TITLE
Confused to how to install PyOpenColorIO for Windows.

### ISSUE THREAD

**Issue by ghost** [AcademySoftwareFoundation/OpenColorIO#911]
As the title mentions. I've read though all the docs that I know off, for 3 hours and I'm clueless to how you're supposed to install PyOpenColorIO as a module for python 2.x. 

(the official build from source doc made it even more confusing)

Looking through the internet for clues led me to nowhere. It seems very vacant about this topic but I managed to find one place where someone had asked the same question but I think there was some sort miscommunication..? https://community.foundry.com/discuss/topic/93985/opencolorio-installing-module-for-python-2-x-on-windows

Any help/clue would greatly be appreciated. Thank you.
(The main reason I'm trying to do this is because of the lut to lut python script.)

**Comment by hodoulp** [comment]
Hi @sillycalvin 

You can have a look to [tests/python/CMakeLists.txt](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/tests/python/CMakeLists.txt) and [tests/python/OpenColorIOTestSuite.py](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/tests/python/OpenColorIOTestSuite.py#L13) to see how python unit tests are working.

Otherwise, the traditional way is to have `PYTHONPATH` defined to your python modules.

Hoping it could help you.
Patrick

**Comment by hodoulp** [comment]
_Note_:  As this is more a question than a bug or feature request, you should use to OCIO user forum `https://lists.aswf.io/g/ocio-user/topics` to ask your question. Having a wider audience will certainly help you to have the right answer.

**Comment by sillycalvin** [comment]
Thank you for the response and help. I will be sure to check out the forum. I'm sorry if it seemed as if I had already built the module. Whats troubling me is where I can find it or how I can build it in windows in order be then used for python. 

Quick question is there a pre-built one I can find? like maybe a .whl file for pip to be installed of some sort. Thank you for your time.

**Comment by hodoulp** [comment]
> Quick question is there a pre-built one I can find?

That's a discussion at the TAC level i.e. nothing for short-term to help you.

Concerning the library compilation, the documentation [here](https://opencolorio.org/installation.html#building-from-source) explains how to build (i.e. unfortunately a little bit old). Below are some lines to help you as the 'Python Bindings' are only built if `python` is found:
```
set PYTHON_PATH=C:\Python27
set PATH=%PYTHON_PATH%;%PATH%

REM cmake -G "Visual Studio 14 2015 Win64"
REM cmake -G "Visual Studio 15 2017 Win64"
cmake -G "NMake Makefiles JOM" ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DOCIO_BUILD_PYTHON=ON ^
    ../.
```
And double-check the line below:
```-- Found PythonLibs: C:/Python27/libs/python27.lib (found suitable version "2.7.16", minimum required is "2.7")```

**Comment by simonbjork** [comment]
Jumping in here as it might be related. Has anyone tried to build the python bindings with vcpkg? With the latest patch everything works great, execpt for the python bindings. I reported the issue [here](https://github.com/microsoft/vcpkg/issues/9657).

In the vcpkg portfile.cmake, the variables are USE_PYGLUE. Is that not relevant anymore? Also, I tried adding DOCIO_BUILD_PYTHON, but still no luck.

Any idea?

**Comment by michdolan** [comment]
What version of OCIO are you building? 1.1.1?

**Comment by simonbjork** [comment]
Yes, 1.1.1

**Comment by michdolan** [comment]
If you want a quick fix, pre-built wheels are available here (bundled with OpenImageIO Python bindings): https://www.lfd.uci.edu/~gohlke/pythonlibs/#openimageio

But in general, if you pass the following option to cmake, the bindings should build:
-DOCIO_BUILD_PYGLUE=ON

If your Python install is not being found (or it's finding only Python 3, which is not supported currently), you can inform cmake of your python.exe to force Python 2 with:
-DPYTHON=C:\Python27\python.exe (or wherever your python.exe lives)

The result of building and installing should be a ...\lib\site-packages\. directory under your defined CMAKE_INSTALL_PREFIX path, which will contain a PyOpenColorIO.pyd file. It's a .dll, but named for Python to see it as an extension. For a quick and dirty Python package (there are better ways of doing this, which we should explore providing with our updated bindings via a setup.py script, but in the name of simplicity):

1. Create a "PyOpenColorIO" directory under C:\Python2.7\Lib\site-packages\.
2. Drop PyOpenColorIO.pyd and OpenColorIO.dll (assuming you built a shared library) into this folder
3. Create a __init__.py file in the same folder containing the line "from PyOpenColorIO import *"

Now if you launch that verison of Python in a shell, you should be able to do:
import PyOpenColorIO as OCIO

I'm working on the next generation Python bindings for OCIO, and will make note to offer a bundled install mechanism for those who want it.

**Comment by simonbjork** [comment]
Thanks for the breakdown @michdolan 

I use vcpkg and tried adding the those variables but still no luck. Not sure why it does'nt work but I guess it must be a vcpkg issue then? All the dlls etc are generated correctly.

By the way, the vcpkg port uses python3 as default, is that even supported? I changed to Python2, but still the same issue.

**Comment by michdolan** [comment]
No Python 3 support yet unfortunately. And sorry I somehow read around your mention of vcpkg. I'm not sure of the details of that support currently.

**Comment by doug-walker** [comment]
Closing this as the Python binding is now available via the Python Package Installer (pip install opencolorio).  Thanks to Remi!
