### ISSUE TITLE
[RFC] Explicit Context section similar to roles

### ISSUE THREAD

**Issue by KevinJW** [AcademySoftwareFoundation/OpenColorIO#917]
I was wondering about the idea of supporting an explicit section in the config file to support externally passed context in to the config.

<pre>
contexts:
  -! <Context> { name: show_grade_cs, var: SHOW_GRADE_CS, default: ACES - ACEScg}
  -! <Context> { name: some_context_that_must_be_provided, var: MANDITORY}
</pre>

The idea being we could have an explicit declaration of the expected contexts, optionally provide a default, etc. And could help with improving the validation/sanity checking when using configs that rely on context variables.

**Comment by KevinJW** [comment]
Apparently #322 does this!

**Comment by doug-walker** [comment]
Closing as this feature has been implemented.
