### ISSUE TITLE
Restore OCIO Java bindings

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#950]
The OCIO Java language bindings have not yet been updated to support the newly developed OCIO v2 API. Java provides additional Android platform support, but needs some effort to revive. Additionally, adding Java unit test support to OCIO's CI infrastructure would help maintain the functionality as OCIO continues to evolve.

**Comment by michdolan** [comment]
In response to @MOFD308:

> If I want to take "Restore Java bindings" as my Google Summer of Code project, can any members tell me where to start? Thanks!

The existing Java bindings are here:
https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/src/bindings/java

The updated OCIO public API is represented by the header files here:
https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/include/OpenColorIO

This project involves updating the existing Java bindings to account for the updated API, which has changed quite a lot, and will continue to evolve into the summer. The second part of this task involves running the Java binding test suite as a part of our cloud-based CI system, to help preserve its reliability. The test suite is here (also needs to be updated):

https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/tests/java

I would also suggest that this project could involve some research to get a feel for who is or has used these bindings in the past, and get feedback on the current implementation's effectiveness.

Before you get to full on proposal though, if you're interested, you'll want to find a small issue to solve and get a PR into the project, which is a prerequisite for applying to GSoC with the ASWF. There are some good first issues available here:

https://github.com/AcademySoftwareFoundation/OpenColorIO/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

We also have a Slack workspace where some GSoC discussion has been taking place. I can send you an invite if you give me your email.

**Comment by Popeyes-bit** [comment]
I am  interested in this project,  can you add me on the slack workspace my email id is ankursoni037@gmail.com

> In response to @MOFD308:
> 
> > If I want to take "Restore Java bindings" as my Google Summer of Code project, can any members tell me where to start? Thanks!
> 
> The existing Java bindings are here:
> https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/src/bindings/java
> 
> The updated OCIO public API is represented by the header files here:
> https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/include/OpenColorIO
> 
> This project involves updating the existing Java bindings to account for the updated API, which has changed quite a lot, and will continue to evolve into the summer. The second part of this task involves running the Java binding test suite as a part of our cloud-based CI system, to help preserve its reliability. The test suite is here (also needs to be updated):
> 
> https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/tests/java
> 
> I would also suggest that this project could involve some research to get a feel for who is or has used these bindings in the past, and get feedback on the current implementation's effectiveness.
> 
> Before you get to full on proposal though, if you're interested, you'll want to find a small issue to solve and get a PR into the project, which is a prerequisite for applying to GSoC with the ASWF. There are some good first issues available here:
> 
> https://github.com/AcademySoftwareFoundation/OpenColorIO/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
> 
> We also have a Slack workspace where some GSoC discussion has been taking place. I can send you an invite if you give me your email.

**Comment by MOFD308** [comment]
@michdolan Thanks for your reply and my email is [xguo262@wisc.edu](url).

**Comment by diptanshumittal** [comment]
@michdolan  Can you please add me to the slack workspace ?
My email id is - diptanshu18232@iiitd.ac.in
