### ISSUE TITLE
Need better installation documentation + clear statement of purpose

### ISSUE THREAD

**Issue by jeremyselan** [AcademySoftwareFoundation/OpenColorIO#99]
A very respected user has brought it to our attention that our installation docs are atrocious...

To quote, 
"I’ve never been shy about building and installing from source code but this is painful.  It’s extremely unclear to me how to setup OCIO and what the tools do once it is setup.  My only insight is from conversations with you and seeing your examples.  If I were coming to this cold I’d have no idea.

Besides the installation documentation you should probably have a clear statement of the intended purpose of OCIO and all the supplementary tools."

Installation of OCIO - including all utilities - should be as simple as possible. Also, OCIO and all utilities should have a clear description on the front page of the website to make it obvious what this project solves.

**Comment by rashil2000** [comment]
Hey @jeremyselan @dbr, any updates on this issue?

**Comment by hodoulp** [comment]
@michdolan @scoopxyz , Perhaps a defect to deprecate or at least to put on hold while waiting for the new documentation mechanism.

@rashil2000 I think that you should better look for another defect to start working in the OpenColorIO project.

**Comment by rashil2000** [comment]
That's alright @hodoulp! I'm thinking about working on #512, which integrates ReadTheDocs  with OCIO. Just waiting for approval there...
