### ISSUE TITLE
[CMAKE] FindPybind failure on Debian Buster

### ISSUE THREAD

**Issue by sobotka** [AcademySoftwareFoundation/OpenColorIO#998]
Platform: Debian Buster amd64

Summary: Build fails with:
```
PyOpenColorIO.h:51:8: error: 'polymorphic_type_hook' is not a class template
 struct polymorphic_type_hook<OCIO::Transform> 
```

Description: The FindPyBind is permitting the build to continue despite the PyBind11 library version being insufficient. As of now, the current version of PyBind11 reported on Debian Buster is:
```
Package: pybind11-dev                    
Version: 2.2.4-2
```
The required version minimum is:
```
# pybind11
# https://github.com/pybind/pybind11
set(pybind11_MIN_VERSION 2.4.3)
find_package(pybind11 ${pybind11_MIN_VERSION} REQUIRED)
```

**Comment by michdolan** [comment]
@sobotka is this working properly in your environment now?

**Comment by sobotka** [comment]
Need to give the Pleasures of Building another whirl...

**Comment by sobotka** [comment]
So sorry Michael for not hammering on this sooner.

I've tested a clean checkout against default cmake finding, and it finds 2.7 on Debian buster, and cleanly compiles.

I manually flipped it over to 3.7, and it too cleanly compiles.

Tremendous work. Thanks so much.

**Comment by michdolan** [comment]
No worries at all. Thanks for reporting the issue!
