### ISSUE TITLE
TSC Nomination: Carol Payne, Netflix

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#999]
Per the guidelines of the OCIO `GOVERNANCE.md`, this issue is to nominate adding Carol Payne as a voting member of the OCIO TSC, and as an official representative on the TSC for Netflix.

Carol has been actively participating in TSC meetings since September of 2019. She is currently an Imaging Specialist at Netflix, and was previously a Color and Imaging Scientist at ILM. She has taken initiative in helping to lead discussions around improving OCIO documentation, and expressed an interest in collaborating on these efforts with other TSC members. Carol's understanding of imaging and color science, her production experience, and her involvement in the streaming industry, make her a great candidate for helping to steer OCIO.

**Comment by doug-walker** [comment]
In addition to what Michael wrote, Carol is also a co-chair of the ACES Gamut Mapping VWG.  

I think this is a great idea and second the proposal.

**Comment by scoopxyz** [comment]
Just realized that...

> If there are no objections raised by any Committers two weeks after the issue is opened, the nomination will be considered as accepted

...means we don't have a way to override the two week wait time... but assuming no objections are raised, see you on the TSC in two weeks 😁

**Comment by carolalynn22** [comment]
Thanks all! Excited to continue :)
